### ISSUE TITLE
this lib does not work with expo

### ISSUE THREAD

**Issue by gvnc** [ammarahm-ed/react-native-admob-native-ads#1]
I tried to run it on expo, but it gives below error on adroid phone with expo client.

_> [01:59:51] requireNativeComponent: "RNGADNativeView" was not found in the UIManager.
> - node_modules\react-native\Libraries\ReactNative\getNativeComponentAttributes.js:30:4 in getNativeComponentAttributes
> - node_modules\react-native\Libraries\Renderer\shims\ReactNativeViewConfigRegistry.js:102:25 in exports.get_

I see that this view is included in the src folder of this repo, but somehow it doesn't findt it,

**Comment by ammarahm-ed** [comment]
https://docs.expo.io/versions/latest/introduction/faq/

> Managed Expo projects don't support custom native code, including third-party libraries which require custom native components. In a managed project, you only write JavaScript.
> In our SDK, we give you a large set of commonly desired, high-quality native modules. We recommend doing as much in JavaScript as possible, since it can immediately deploy to all your users and work across both platforms, and will always continue to benefit from Expo SDK updates.
> However, if you need something custom that isn't possible with the native modules provided in the SDK, like on-the-fly video processing or low-level control over the Bluetooth radio to do a firmware update and other features requested here, you can run expo eject and have full control over the underlying native projects.

I think expo does not support native modules directly according to the docs. If you want you can try the above, call expo eject and maybe this will work. I have not tested it with expo, but I will try it out tomorrow morning to see if there is a way to work this out. Till then you can check on how to run native modules with expo.

**Comment by ammarahm-ed** [comment]
https://docs.expo.io/versions/latest/expokit/eject/


read more here.
