### ISSUE TITLE
Issue on IOS 

### ISSUE THREAD

**Issue by aftabaminzoobiapps** [ammarahm-ed/react-native-admob-native-ads#101]
Task orphaned for request <NSMutableURLRequest: 0x2823172d0> { URL: https://lh3.googleusercontent.com/proxy/yJ_uUcMQY24FSFbannE6KRnl56KleIuwFkrugKZAFEA5sZZtLuNd6oghQpme-KyzPXKmKKsey9KL7yLltqUPqhV8w1esX9TERZ0TDapMQ1bY7oymPpGWjj-jUmwQuKOJnpxJMpqMBCnSsX8aCd_BBEQ6zQQNo8y6pQxxKRG_OnhKOa6gTKxFhPTyXxbSgGWBFmJrjrm9-G_id6X7Kxe5wfVZxqhG=w128-h128-n-e7-l80-rj }

**Comment by ammarahm-ed** [comment]
Please provide a complete log

**Comment by aftabaminzoobiapps** [comment]
> Please provide a complete log

when ever I tried to load an add. and the image comes from http link then it is showing the warning.

**Comment by ammarahm-ed** [comment]
fixed
