### ISSUE TITLE
 Invariant Violation: requireNativeComponent: "MediaView" was not found in the UIManager.

### ISSUE THREAD

**Issue by ajoykarmakar** [ammarahm-ed/react-native-admob-native-ads#104]
After update to the latest version of this plugin. I am facing this error.

![image](https://user-images.githubusercontent.com/32778214/100639196-dfd0ac00-335a-11eb-9094-5d21ba14b95d.png)
![Screenshot_1606755301](https://user-images.githubusercontent.com/32778214/100639223-e8c17d80-335a-11eb-9159-cdc44cd3bd94.png)

**Comment by ammarahm-ed** [comment]
clean your node_modules folder and clean android the build folders by running `./gradlew clean` inside `your_project/android/` folder.
