### ISSUE TITLE
"The ad request was successful, but no ad was returned due to lack of ad inventory" using test ID

### ISSUE THREAD

**Issue by Jean-Kenned** [ammarahm-ed/react-native-admob-native-ads#108]
The last release always returns this error from ad mob server. It is very strange because the first release (v0.1.0) that I have been using for months do not show this error, and when I upgraded the lib to the last release this error suddenly appears, and I am using the same test ID. Any ideas? I already cleaned the android build and removed the node_modules but anything worked. Thanksss!

**Comment by ammarahm-ed** [comment]
@Jean-Kenned Issue is not related to the library. Remove your app from android phone, remove all build folders in project/android and project/android/app folders too. Install it again and hopefully it will work. The error is just that admob server is not returning the ads. You can try the example app to test.
