### ISSUE TITLE
Ads keep refreshing even if they're in a screen that's not displaying 

### ISSUE THREAD

**Issue by bartzy** [ammarahm-ed/react-native-admob-native-ads#110]
Hi,

I see that ads keep getting refreshed even when they're in a screen that's currently in the navigation stack but not on top (several view controllers away even).

Am I doing something wrong? Otherwise, this seems very wasteful and problematic.

Thanks!

**Comment by ammarahm-ed** [comment]
@bartzy I think you are right, maybe we need to pause ad loading when user leaves the screen.

**Comment by ammarahm-ed** [comment]
fixed
