### ISSUE TITLE
Production ads not showing but requests are being sent to google!

### ISSUE THREAD

**Issue by b15h0y** [ammarahm-ed/react-native-admob-native-ads#111]
Hello, I have been using this package for a week now in an android app. the test banners are working fine but in the production mode, no ads are showing. When I check my google admob account, I find that requests are being made successfully but they aren't showing in the app. Anyone facing this issue?

![image](https://user-images.githubusercontent.com/57562898/103141669-32a24700-4700-11eb-9828-29998a5ca253.png)
![adsssss](https://user-images.githubusercontent.com/57562898/103141689-844ad180-4700-11eb-90dd-aff906d135b2.jpeg)

**Comment by Island-Life-Exotics** [comment]
I am facing the same issue. where its showing in Google Admob but the ads aren't shown in the app.

**Comment by Island-Life-Exotics** [comment]
For me I just recently released my application, I read that Google can take a while before they start sending adds so I will wait a couple more weeks and see if they start showing up.

**Comment by b15h0y** [comment]
I have been waiting for more than a week. is it a matter of time or how many people download your app?

**Comment by Island-Life-Exotics** [comment]
according to google support 

> This might be caused by no inventory available for that ad unit ID at that time. This is usually unrelated to your implementation if you are able to show ads with our test ad unit ID (Android, iOS, Unity). Sometimes this problem will be solved after you released your app and get more traffic.

**Comment by b15h0y** [comment]
Did your issue get solved? @Island-Life-Exotics

**Comment by ammarahm-ed** [comment]
@b15h0y and @Island-Life-Exotics The issue is not related to this library but Google. It usually takes some to to show ads. Also you should check if you have provided complete info in AdMob Console like name, location, phone etc. If some information is missing, ads might not show up.
