### ISSUE TITLE
 Is there a way to get a square ad instead of a rectangle?

### ISSUE THREAD

**Issue by cokepizza** [ammarahm-ed/react-native-admob-native-ads#112]
https://support.google.com/admanager/answer/7031536?hl=en
https://developers.google.com/admob/android/native/options?hl=en

According to the guidelines, I can receive ads by setting native ads in a 1:1 ratio. I have to use the setMediaAspectRatio method in order to receive only ads that fit the 1:1 ratio, but there is no way to set this in the current library.

If there is any way I can adjust the proportions of the ad, please let me know.
If there is no way to load ads from admob like this, can you tell me what you plan to add this feature to?

**Comment by ammarahm-ed** [comment]
Currently not supported

**Comment by ammarahm-ed** [comment]
support added in master
