### ISSUE TITLE
incompatible with expo/vector-icons

### ISSUE THREAD

**Issue by PlayNprovide** [ammarahm-ed/react-native-admob-native-ads#113]
I'm doing a project with expo in bare-project
the ads shows up without problems
but the icon is only visible when built in debug mode
when I start the app without debug I got this warning and got no icon on the screen
screenshots :
https://lh3.googleusercontent.com/8ELno9MLh9twfAgiqSKfv__Q6yq7ilu0gVJJXgKJwrIa-Ez-uJ3WCxrt_rNzUPeUg1KORIxgw2XnT_p74JuWiC8okKAagXdY9Vz_jSylFqHlZEXmgVZT0qc2Z5bOfHRfV-kcMoTDDr0u0mb5eSbxvDe6lN6HbIWWI0xEqVBfHgorv-EXLCuB7aDnhxKu4tqaZ9azB-qf2yTf7oXOPJUxifH0ABsnEPSJpe7m-_MPm0xYMkSd16gRyyzZSCwAwG7H1V4ooxNWO8OnijFIUpLN-3DPlOxNMm7FykUZZNyAwe8xFe2z29yNVO8WGZI66x0m0th8xUAOeQMh16FQKjfsMapP5hGRSGxRN9vcS2oZb4PSXcrTW2VnADCnH9B4t6L4duoAMaN952tXgIya8mLf7HATb5VY-rwYyk7UiqvFRpEk1fitbOGKJEgBHS6Uh2nXBf7LY5p9hqN-TnOwRMxM6XBUkf1vJS87_F_mNxfR7GKATuP8aJ90j3PeQwr2LX45T4vgx50pyx3jghQC8H9wlFjW4StKV7ffYkJh6aOAMDbSh4KiS3tvsRTyBLNbnFbBHJVYaPy3X8JlxwswDKT9GIYG4TAgf1O9bxqf2lWVp_CxVoZRxQrHD6sAjtb2xbPu6OJpNQ3RCr7vIO31XpW2CgHW1Jp-q5R5gagdBDa_oxA_kmocuqummADs6B9y=w495-h880-no?authuser=0

please refer to the source code too
It only contains two components, native ads and icon 
https://github.com/PlayNprovide/problem

Is there another way to work around except not doing expo?
It would be grateful If you suggest any idea

**Comment by ammarahm-ed** [comment]
I will look into it

**Comment by ammarahm-ed** [comment]
From the example it appears that you are using expo/vector-icons outside the AdView so the issue is not related to this library.
