### ISSUE TITLE
blank white screen on release mode

### ISSUE THREAD

**Issue by PlayNprovide** [ammarahm-ed/react-native-admob-native-ads#114]
everything works fine when built in debug mode
but  when I run release version It gives me white blank screen

when I tried this code to get more details
**gradlew assembleRelease --warning-mode all**  

It gives me this error message
> Configure project :react-native-admob-native-ads
The maven plugin has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the maven-publish plugin instead. Consult the upgrading guide for further information: https://docs.gradle.org/6.2/userguide/upgrading_version_5.html#legacy_publication_system_is_deprecated_and_replaced_with_the_publish_plugins

any idea?

**Comment by saricden** [comment]
@PlayNprovide how did you end up solving this?

I'm encountering it now, late 2021.
