### ISSUE TITLE
Failed to load UI in IOS simulator after library installation

### ISSUE THREAD

**Issue by oron11** [ammarahm-ed/react-native-admob-native-ads#116]
Hello, 

First I installed the expo-ads-admob successfully.
Afterwards, I installed the library as instructed:
- npm install react-native-admob-native-ads
- npx pod-install

The build finished but I cannot load any UI:
I can see the error: "Component 'ViewManagerAdapter_ExpoAdsAdMobBannerView' re-registered bubbling event 'topSizeChange' as a direct event
<img width="303" alt="Screen Shot 2021-01-03 at 9 37 12 pm" src="https://user-images.githubusercontent.com/24213091/103487152-f52e6f80-4e0b-11eb-9016-e0e37b80c723.png">

Expo diagnostics:
  Expo CLI 3.28.4 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.3.0 - /usr/local/bin/node
      npm: 6.14.10 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.3 => 0.63.3 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.4
    Expo Workflow: bare

"dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.11.1",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "expo": "~39.0.2",
    "expo-ads-admob": "~8.3.0",
    "expo-constants": "~9.2.0",
    "expo-in-app-purchases": "^9.1.0",
    "expo-localization": "~9.0.0",
    "expo-notifications": "~0.7.2",
    "expo-splash-screen": "~0.6.2",
    "expo-status-bar": "~1.0.2",
    "expo-store-review": "~2.2.0",
    "expo-updates": "~0.3.2",
    "i18n-js": "^3.8.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.3",
    "react-native-admob-native-ads": "^0.3.9",
    "react-native-elements": "^3.0.0-alpha.1",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.7.0",
    "react-native-reanimated": "^1.13.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.10.1",
    "react-native-unimodules": "~0.11.0",
    "react-native-web": "~0.13.12",
    "react-native-webview": "^11.0.2"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.13.1"
  },

**Comment by ammarahm-ed** [comment]
expo is not supported. I have never tested this lib with expo projects
