### ISSUE TITLE
Road to 0.4.0

### ISSUE THREAD

**Issue by ammarahm-ed** [ammarahm-ed/react-native-admob-native-ads#119]
After working on the preloading branch for some time i have stepped away from this feature until further research is done  so we can implement it properly. There are more important issues at the moment that need my attention.

 **Android**

- [x] mediaAspectRatio support . 
- [x] remove auto ad refreshing
- [x] Support mute/unmute a video
- [x] Support of video controller events / video duration etc and custom video controls and interface
- [x] Support mediation (Especially Facebook Ads)
- [x] Support for Custom Ad Targeting

**iOS**
- [x] mediaAspectRatio support 
- [x] remove auto ad refreshing
- [x] Support mute/unmute a video
- [x] Support of video controller events / video duration etc and custom video controls and interface
- [x] Support mediation (Especially Facebook Ads)
- [x] Support for Custom Ad Targeting

#
- [x] Update Documentation 
- [x] Improve the examples for loading ads in a list more efficiently 
- [x] Release 0.4.0

When: Hopefully in one week from now if I don't get stuck with something else and after this we can look into ad preloading too. 

Thanks to @yaroslavnikiforov for helping me out to fix mediation for facebook on Android and iOS for the past week.

**Comment by bartzy** [comment]
@ammarahm-ed Are you going to release 0.4.0 to npm only after finishing with documentation updates, or do you have more fixes/changes you need to do?

Thanks!

**Comment by ammarahm-ed** [comment]
@bartzy release after docs
