### ISSUE TITLE
Incompatible with gradle 7.0

### ISSUE THREAD

**Issue by illusi03** [ammarahm-ed/react-native-admob-native-ads#120]
Hello bro, thanks for build this package. 
But i have a problem with this package, can this package install in gradle 7.0 version ?
Thanks in advice

![image](https://user-images.githubusercontent.com/52351532/105618530-e2abc280-5e1a-11eb-8cb1-f94a8ab1ae07.png)

**Comment by sametpalitci** [comment]
Same problem, did you fixed?

**Comment by ammarahm-ed** [comment]
Share more details about the error. the example builds normally so compare your project files with it.

**This may help**
update your `android/build.gradle` file as follows:

```
dependencies {
        classpath("com.android.tools.build:gradle:3.5.4")
    }
```

**Comment by illusi03** [comment]
> Share more details about the error. the example builds normally so compare your project files with it.
> 
> **This may help**
> update your gradle version in `android/build.gradle` as follows:
> 
> ```
> dependencies {
>         classpath("com.android.tools.build:gradle:3.5.4")
>     }
> ```

Update gradle has fixed the issue, thanks in advance
