### ISSUE TITLE
onAdFailedToLoad Passes raw native event on error

### ISSUE THREAD

**Issue by CarlOmega** [ammarahm-ed/react-native-admob-native-ads#121]
Line 38 in src/index.js is 
`this.props.onAdFailedToLoad(event);`
But should be
`this.props.onAdFailedToLoad(event.nativeEvent);`
Otherwise you have to unwrap the event making it confusing to use. It helps debugging a lot if you know what the server is responding.

Sorry if this has been mentioned before but I needed to do this fix on newest release.

**Comment by ammarahm-ed** [comment]
i'll make this change, thanks for pointing it out.

**Comment by CarlOmega** [comment]
More than welcome thanks for creating the package.

**Comment by ammarahm-ed** [comment]
fixed on master
