### ISSUE TITLE
Ads Loading Issue 

### ISSUE THREAD

**Issue by zoobibackups** [ammarahm-ed/react-native-admob-native-ads#122]
I have the test ad ideas but it is giving the error below from the last 4 days. 
{"error": {"message": "The ad request was successful, but no ad was returned due to lack of ad inventory."}}
and sometimes this error 
` {"error": {"message": "Invalid ad request, possibly an incorrect ad unit ID was given."}}`
the same was working in my previous project now it is not working I have tried all the things. not event he example app 

[Example ](https://github.com/ammarahm-ed/react-native-admob-native-ads/tree/master/example)

**Comment by ammarahm-ed** [comment]
Not an issue with the library but AdMob server.

**Comment by zoobibackups** [comment]
solved
