### ISSUE TITLE
Call To Action text is has event trigger that opens Ad not the whole button.

### ISSUE THREAD

**Issue by CarlOmega** [ammarahm-ed/react-native-admob-native-ads#123]
Not sure if this is by design, but I read in policies that it can be either: "Button or text field that encourages user to take action". We wanted to use the whole button to make it more like our app design and got around this by only styling the textStyle prop. 

I could help write a prop to bind the action of the button or the text based on developers choice but thought I would bring this up.

**Comment by ammarahm-ed** [comment]
We use `<Text/>` as a button to register clicks because Buttons/Touchables provided by React Native cannot be registered as clickable in android and ios Native code and they do not work. One way is to use `react-native-gesture-handler`'s `RawButton` which can be clicked from native code.

**Comment by CarlOmega** [comment]
We just styled the text to fill the container to get around this. I was unaware of this restriction, Its all good for us now.
