### ISSUE TITLE
Can't build iOS with the latest version (8.1.0) of Google-Mobile-Ads-SDK

### ISSUE THREAD

**Issue by Long2k1708** [ammarahm-ed/react-native-admob-native-ads#127]
Please check this problem. It has been occurred after I upgraded Google-Mobile-Ads-SDK to 8.1.0 with `pod install --repo-update`
<img width="1512" alt="Screen Shot 2021-02-21 at 14 23 03" src="https://user-images.githubusercontent.com/18576670/108618430-af2b7a80-7450-11eb-90c3-256f24f1d4fa.png">

**Comment by benjaminfiliatrault** [comment]
+1

**Comment by ammarahm-ed** [comment]
@benjaminfiliatrault @Long2k1708 Its fixed on master for 0.4.0. You can use master as its complete, only docs are to be rewritten or use `7.69.0` version of google mobile-ads library on iOS
