### ISSUE TITLE
[Migrating to 0.4.0] Build failed in iOS: Semantic issue

### ISSUE THREAD

**Issue by tanwanjern** [ammarahm-ed/react-native-admob-native-ads#130]
Hi, I'm migrating 0.3.9 to 0.4.0, but I'm getting this error when I build the iOS app.

What I did
- Pod install
- Delete and rebuild the app
- Remove derived data folder

![image](https://user-images.githubusercontent.com/23072805/109931795-42439a80-7d04-11eb-8121-ce96bd91b17e.png)
![image](https://user-images.githubusercontent.com/23072805/109931475-dcefa980-7d03-11eb-9bd2-59685251ebff.png)

**Comment by ammarahm-ed** [comment]
update your Google Mobile Ads Library to `>=8.0.0` in Podfile.

Add these to your Podfile.
`
pod 'Google-Mobile-Ads-SDK'
pod 'GoogleMobileAdsMediationFacebook'
`
run `pod update Google-Mobile-Ads-SDK`

and it will build

**Comment by tanwanjern** [comment]
I see, but if I upgrade my Google Mobile Ads Library to >=8.0.0 in Podfile, I will be not able to use [react-native-admob](https://github.com/sbugert/react-native-admob) or [react-native-firebase/admob](https://github.com/invertase/react-native-firebase) to display banner and interstitial ads

Issue: https://github.com/sbugert/react-native-admob/issues/554

**Comment by ammarahm-ed** [comment]
Then you need to stay on 0.39 for now until they update their library to support the new version. @tanwanjern

**Comment by Hassan709** [comment]
undefined is not an object (evaluating '_utils.AdOptions.mediaAspectRatio[this.props.mediaAspectRatio]') in react-native-admob-native-ads

**Comment by Hassan709** [comment]
whats an issue please tell me i can use version 0.0.4 library

**Comment by Hassan709** [comment]
Getting this error on android =>Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by Hassan709** [comment]
there are multiple issues in 0.4.0

**Comment by ammarahm-ed** [comment]
@Hassan709 post your implementation of the library here. The code. Also check the example app since everything is working in the example.

**Comment by Hassan709** [comment]
i can use updated library but could not work for me.

**Comment by Hassan709** [comment]
i can also read migration guide and followed it.

**Comment by ammarahm-ed** [comment]
Compare your implementation with the example or post your code here.

**Comment by Hassan709** [comment]
ok

**Comment by Hassan709** [comment]
when i can install this lib  [Error: undefined Unable to resolve module `./src/MediaView` from `node_modules\react-native-admob-native-ads\index.js`:

**Comment by ammarahm-ed** [comment]
@Hassan709 If you read the Migration Guide. It says MediaView has been renamed to NativeMediaView

**Comment by Hassan709** [comment]
@ammarahm-ed  Thanks for Replying .... I can implements 0.4.0 library but issues is that when i can switch to next screen native ads is reload. I want ads is load before rendering screen. And when screen navigate immediately shown an ads  not coming delay.

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed  Thanks for Replying .... I can implements 0.4.0 library but issues is that when i can switch to next screen native ads is reload. I want ads is load before rendering screen. And when screen navigate immediately shown an ads  not coming delay.

Not possible. The ad loads from server so it will take time. No preloading

**Comment by Hassan709** [comment]
so you ca handle  this from loader

**Comment by Hassan709** [comment]
My boss requirement is ads pre load i can  try from 5 days but fails. please help me thanks

**Comment by Hassan709** [comment]
can i apply shimmer on container ?

**Comment by Hassan709** [comment]
place of loading

**Comment by Hassan709** [comment]
@ammarahm-ed  where we can apply shimmer place of loading tell me please
import React, { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, DeviceEventEmitter, Text, View } from 'react-native';
import NativeAdView, {
    AdvertiserView,
    CallToActionView,
    HeadlineView,
    IconView,
    StarRatingView,
    StoreView,
    TaglineView,
} from 'react-native-admob-native-ads';
import Shimmer from 'react-native-shimmer';
import { Events } from '../utils';
const NativeAds = React.memo(({ index, loadOnMount = true }) => {
    const [aspectRatio, setAspectRatio] = useState(1.5);
    const [loading, setLoading] = useState(false);
    const [loaded, setLoaded] = useState(false);
    const [error, setError] = useState(false);
    const nativeAdRef = useRef();

    const onAdFailedToLoad = (event) => {
        setError(true);
        setLoading(false);
        console.log('AD', 'FAILED', event.error.message);
    };

    const onAdLoaded = () => {
        console.log('AD', 'LOADED', 'Ad has loaded successfully');
    };

    const onAdClicked = () => {
        console.log('AD', 'CLICK', 'User has clicked the Ad');
    };

    const onAdImpression = () => {
        console.log('AD', 'IMPRESSION', 'Ad impression recorded');
    };

    const onUnifiedNativeAdLoaded = (event) => {
        console.log('AD', 'RECIEVED', 'Unified ad  Recieved', event);
        setLoading(false);
        setLoaded(true);
        setError(false);
        setAspectRatio(event.aspectRatio);
    };

    const onAdLeftApplication = () => {
        console.log('AD', 'LEFT', 'Ad left application');
    };

    const onViewableItemsChanged = (event) => {
        let viewableAds = event.viewableItems.filter(
            (i) => i.key.indexOf('ad') !== -1,
        );

        viewableAds.forEach((adView) => {
            if (adView.index === index && !loaded) {
                setLoading(true);
                setLoaded(false);
                setError(false);
                console.log('AD', 'IN VIEW', 'Loading ' + index);
                nativeAdRef.current?.loadAd();
            } else {
                if (loaded) {
                    console.log('AD', 'IN VIEW', 'Loaded ' + index);
                } else {
                    console.log('AD', 'NOT IN VIEW', index);
                }
            }
        });
    };

    useEffect(() => {
        if (!loadOnMount) {
            DeviceEventEmitter.addListener(
                Events.onViewableItemsChanged,
                onViewableItemsChanged,
            );
        }

        return () => {
            if (!loadOnMount) {
                DeviceEventEmitter.removeListener(
                    Events.onViewableItemsChanged,
                    onViewableItemsChanged,
                );
            }
        };
    }, [loaded]);

    useEffect(() => {
        if (loadOnMount) {
            setLoading(true);
            setLoaded(false);
            setError(false)
            nativeAdRef.current?.loadAd();
        }
        return () => {
            setLoaded(false);
        };
    }, []);

    return (
        <View
            style={{
                backgroundColor: 'green',
                width: '100%',
                alignItems: 'center',
            }}>
            <NativeAdView
                ref={nativeAdRef}
                onAdLoaded={onAdLoaded}
                onAdFailedToLoad={onAdFailedToLoad}
                onAdLeftApplication={onAdLeftApplication}
                onAdClicked={onAdClicked}
                onAdImpression={onAdImpression}
                onUnifiedNativeAdLoaded={onUnifiedNativeAdLoaded}
                style={{
                    width: '98%',
                    alignSelf: 'center',
                }}
                adUnitID=""
            >
                <View
                    style={{
                        width: '100%',
                        alignItems: 'center',
                    }}>
                    {loading && <Shimmer>

                    <View
                        style={{
                            width: '100%',
                            height: "100%",
                            backgroundColor: '#fff',
                            position: 'absolute',
                            justifyContent: 'center',
                            alignItems: 'center',
                            opacity: !loading && !error && loaded ? 0 : 1,
                            zIndex: !loading && !error && loaded ? 0 : 10
                        }}>
                        {/* {loading && <Shimmer />} */}
                        {error && <Text style={{ color: '#a9a9a9' }}>:-(</Text>}
                    </View>
                    </Shimmer>}
                    <View
                        style={{
                            height: 100,
                            width: '100%',
                            flexDirection: 'row',
                            justifyContent: 'space-between',
                            alignItems: 'center',
                            paddingHorizontal: 10,
                            opacity: loading || error || !loaded ? 0 : 1,
                        }}>
                        <IconView
                            style={{
                                width: 60,
                                height: 60,
                            }}
                        />
                        <View
                            style={{
                                width: '60%',
                                maxWidth: '60%',
                                paddingHorizontal: 6,
                            }}>
                            <HeadlineView
                                hello="abc"
                                style={{
                                    fontWeight: 'bold',
                                    fontSize: 13,
                                }}
                            />
                            <TaglineView
                                numberOfLines={2}
                                style={{
                                    fontSize: 11,
                                }}
                            />
                            <AdvertiserView
                                style={{
                                    fontSize: 10,
                                    color: 'gray',
                                }}
                            />

                            <View
                                style={{
                                    flexDirection: 'row',
                                    alignItems: 'center',
                                }}>
                                <StoreView
                                    style={{
                                        fontSize: 12,
                                    }}
                                />
                                <StarRatingView
                                    starSize={12}
                                    fullStarColor="orange"
                                    emptyStarColor="gray"
                                    containerStyle={{
                                        width: 65,
                                        marginLeft: 10,
                                    }}
                                />
                            </View>
                        </View>

                        <CallToActionView
                            style={{
                                minHeight: 45,
                                paddingHorizontal: 12,
                                justifyContent: 'center',
                                alignItems: 'center',
                                elevation: 10,
                                maxWidth: 100,
                                width: 80
                            }}
                            buttonAndroidStyle={{
                                backgroundColor: '#00ff00',
                                borderRadius: 5,
                            }}
                            allCaps
                            textStyle={{
                                fontSize: 13,
                                flexWrap: 'wrap',
                                textAlign: 'center',
                            }}
                        />
                    </View>
                </View>
            </NativeAdView>
        </View>
    );
});
export default NativeAds;

**Comment by Hassan709** [comment]
here is my code

**Comment by ammarahm-ed** [comment]
Ads cannot be preloaded using this library at the moment

**Comment by Hassan709** [comment]
ok but my android developer friends implements  this in android

**Comment by ammarahm-ed** [comment]
Its possible but not implemented in this library as of yet.

**Comment by Hassan709** [comment]
Ok

**Comment by devGuerra** [comment]
Any solution to use firebase adbmob and native-ads ?

**Comment by tanwanjern** [comment]
> Any solution to use firebase adbmob and native-ads ?
> 
> <img alt="Captura de Tela 2021-03-18 às 18 13 36" width="718" src="https://user-images.githubusercontent.com/6579736/111698563-beb29f00-8815-11eb-8eb3-4fe010ddbfb4.png">

I think the only way is to downgrade the version of the native ad to 0.3.9
`"react-native-admob-native-ads": "^0.3.9",`

https://github.com/ammarahm-ed/react-native-admob-native-ads/tree/v0.3.9

**Comment by huyhai** [comment]
same, i am using 0.4.0 no migration and using  firebase adbmob together with this lib

**Comment by haresh4d** [comment]
@ammarahm-ed I am using 0.3.9 version of this library because I have to use react-native-admob for Interstitial ads. Problem is in iOS 14.2 native ads are not shown. Interstitial and banners works just fine. Please help me.

**Comment by OooCleMooO** [comment]
Update Podfile with `pod 'Google-Mobile-Ads-SDK', '~> 8.4.0'` then pod install fixed this issue for me.

**Comment by Berezhnov** [comment]
Hey guys, I installed Google-Mobile-Ads-SDK 8.4.0 and 0.4.0 library version. I have such errors. Did anyone get the same?

<img width="1328" alt="Снимок экрана 2021-05-01 в 03 21 41" src="https://user-images.githubusercontent.com/21060845/116759681-5b2eaa80-aa2c-11eb-8c56-fcd476e28d8e.png">

**Comment by ammarahm-ed** [comment]
A month ago i updated the lib with the new api in v8.0.0 with a sh*t ton of breaking changes. And then again, they changed the api. I mean who does that honestly.....

Maybe we should go back go 7.69 until google is done playing around.

**Comment by Berezhnov** [comment]
> A month ago i updated the lib with the new api in v8.0.0 with a sh*t ton of breaking changes. And then again, they changed the api. I mean who does that honestly.....
> 
> Maybe we should go back go 7.69 until google is done playing around.

switched to 0.3.8. and 7.69. it is working both on android and ios

**Comment by ammarahm-ed** [comment]
> > A month ago i updated the lib with the new api in v8.0.0 with a sh*t ton of breaking changes. And then again, they changed the api. I mean who does that honestly.....
> > 
> > Maybe we should go back go 7.69 until google is done playing around.
> 
> switched to 0.3.8. and 7.69. it is working both on android and ios

I will release a new version that downgrades the google mobile sdk to 7.69

**Comment by Berezhnov** [comment]
> > > A month ago i updated the lib with the new api in v8.0.0 with a sh*t ton of breaking changes. And then again, they changed the api. I mean who does that honestly.....
> > > Maybe we should go back go 7.69 until google is done playing around.
> > 
> > 
> > switched to 0.3.8. and 7.69. it is working both on android and ios
> 
> I will release a new version that downgrades the google mobile ads sdk to 7.69

btw, you did amazing work!

**Comment by ammarahm-ed** [comment]
> > A month ago i updated the lib with the new api in v8.0.0 with a sh*t ton of breaking changes. And then again, they changed the api. I mean who does that honestly.....
> > 
> > Maybe we should go back go 7.69 until google is done playing around.
> 
> switched to 0.3.8. and 7.69. it is working both on android and ios

It's working but lacks a lot of optimizations and issues that were fixed in 0.4.0

**Comment by haresh4d** [comment]
> > > A month ago i updated the lib with the new api in v8.0.0 with a sh*t ton of breaking changes. And then again, they changed the api. I mean who does that honestly.....
> > > Maybe we should go back go 7.69 until google is done playing around.
> > 
> > 
> > switched to 0.3.8. and 7.69. it is working both on android and ios
> 
> I will release a new version that downgrades the google mobile ads sdk to 7.69

Please do it. We really need it.

**Comment by ammarahm-ed** [comment]
@haresh4d & @Berezhnov  I have downgraded the lib version on master branch. try the master branch in your project. Make sure you follow the guidelines to load ad in `v0.4.0`

```bash 
yarn add https://github.com/ammarahm-ed/react-native-admob-native-ads#master
```

then run pod install

```bash
cd ios && pod install
```

**Comment by haresh4d** [comment]
> @haresh4d & @Berezhnov I have downgraded the lib version on master branch. try the master branch in your project. Make sure you follow the guidelines to load ad in `v0.4.0`
> 
> ```shell
> yarn add https://github.com/ammarahm-ed/react-native-admob-native-ads#master
> ```
> 
> Update your podfile:
> 
> ```ruby
>   pod 'Google-Mobile-Ads-SDK', '7.69.0' #can be any version you require below 8.0.0
>   pod 'GoogleMobileAdsMediationFacebook', '6.2.1.0'
> ```
> 
> then run pod install
> 
> ```shell
> cd ios && pod install
> ```

Working like a charm. Thank you @ammarahm-ed

**Comment by hari-react** [comment]
ios  
 pod 'Google-Mobile-Ads-SDK',
  pod 'GoogleMobileAdsMediationFacebook',
  package  is added in podfile. and I tried Both pod install and pod install --repo -update. 
  but package is not installed. error install GoogleMobileAdsMediationFacebook'
  
  please help
