### ISSUE TITLE
Admob Mediation Facebook Doesnt Open

### ISSUE THREAD

**Issue by faz1993** [ammarahm-ed/react-native-admob-native-ads#131]
@ammarahm-ed  The facebook ads show up everything work well the only problem is when i try to open it it doesnt open at all 
maybe im wrong in implementation or maybe my code is wrong i have used only 

`const mediation = {
		nativeBanner: true
};`
`<NativeAdView ref={nativeAdViewRef} adUnitID={NATIVE_AD_ID} mediationOptions={mediation}>
</NativeAdView>`

if iam wrong please correct me

**Comment by ammarahm-ed** [comment]
Why have you set nativeBanner to true? Also is the problem on iOS or android

**Comment by faz1993** [comment]
@ammarahm-ed  no i did not add NativeMediaView

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed  no i did not add NativeMediaView i used only on android

Add it then try again

**Comment by faz1993** [comment]
@ammarahm-ed NativeMediaView is for video right ? when i enable mediationOptions its for video not for nativeBanner ad mediation?

**Comment by ammarahm-ed** [comment]
Yes, set native banner to false

**Comment by faz1993** [comment]
@ammarahm-ed i have removed it completly and i also choosed in facebook audience native banner its still doesnt open its show up the facebook native banner but when i press on blue button or on ad it doesnt open

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed i have removed it completly and i also choosed in facebook audience native banner its still doesnt open its show up the facebook native banner but when i press on blue button or on ad it doesnt open 

Not sure then why it's not working. Try showing video/image ads instead

**Comment by faz1993** [comment]
@ammarahm-ed its showing ads normal like of admob and its showing in status of admob mediation optimization in progress the facebook ads are showing i did not add any facebook sdk or something else can you show me or give me an exemple for enable admob mediation with facebook ?

**Comment by ammarahm-ed** [comment]
For mediation you have to follow guide on Google Admob Mediation for Facebook. Search on Google to find it.

Also once mediation is approved you can show ads that are clickable. Try to show test ads from Facebook until then

**Comment by faz1993** [comment]
@ammarahm-ed all what i did is i installed the package latest one react-native-admob-native-ads i enabled admob mediation from the platform and i created the ads from the facebook audience as mentioned in google for mediation created ad source etc.... thats all what i need ? and i wait till the optimisation finish for its be clickable ?

**Comment by ammarahm-ed** [comment]
Yes I think so that's all you need to do and it should work. Until then maybe try showing test ads from facebook ads instead of real ones

**Comment by faz1993** [comment]
@ammarahm-ed still same i tested with test ad still cant open facebook ads when i click on button CallToActionView

**Comment by ammarahm-ed** [comment]
Can you click on icon/headline etc to open the ad?

**Comment by faz1993** [comment]
@ammarahm-ed yes when i click on Adbadge it redirect me to facebook audience info but when i click on text or ad or button nothing happen i did posted my code

**Comment by ammarahm-ed** [comment]
`<View style={[adLoaded ?`

Remove this check and don't hide the ad and try again

**Comment by faz1993** [comment]
@ammarahm-ed i tried it still same

**Comment by ammarahm-ed** [comment]
Can you test using the AdView in the example?

**Comment by ammarahm-ed** [comment]
Also set nativeBanner to `true` in mediationOptions

**Comment by faz1993** [comment]
> Can you test using the AdView in the example?
> 
> What device are you testing on?

i have added example AdView still the same when i click nothing happen with facebook

**Comment by faz1993** [comment]
> Also set nativeBanner to `true` in mediationOptions

@ammarahm-ed can you give me example of set nativeBanner to true ? maybe i didnt set it the way it is

**Comment by yaroslavnikiforov** [comment]
Hi @faz1993, if your unit id is mapped to Native Banner then you should add this prop for NativeAdView:
`mediationOptions={{ nativeBanner: true }}` and it should have IconView to be clickable. If it is a simple Native ad then NativeMediaView is required to be clickable.

<img width="664" alt="Screenshot 2021-03-07 at 23 22 37" src="https://user-images.githubusercontent.com/42115630/110255381-04f93a00-7f9c-11eb-8c75-a7b254462dcb.png">

Check that, and if it still will not work, try to simplify your component -  remove conditional rendering, React.memo ect. This will help you to find the exact reason. On Android, Facebook ads work fine.

**Comment by faz1993** [comment]
@yaroslavnikiforov the Facebook ADs it show up and appear correctly but when i try to open it it doesnt open even when i press on button or anywhere the only thing which works on facebook ads when appear is the AD Info Icon

**Comment by yaroslavnikiforov** [comment]
I understand, try what I wrote in the previous comment.

**Comment by faz1993** [comment]
@yaroslavnikiforov  
````
import React, { useEffect, useState, useRef } from 'react';
import { View, DeviceEventEmitter } from 'react-native';
import PropTypes from 'prop-types';
import NativeAdView, {
	CallToActionView,
	IconView,
	HeadlineView,
	TaglineView,
	AdvertiserView,
	AdBadge,
	StarRatingView,
	StoreView
} from 'react-native-admob-native-ads';
import { themes } from '../../../constants/colors';

import styles from './styles';
import { adUnitIDs, Events, Logger } from './utils';

const AdmobView = React.memo(({
	theme, index, type
}) => {
	const [loading, setLoading] = useState(false);
	const [loaded, setLoaded] = useState(false);
	const [error, setError] = useState(false);
	const nativeAdRef = useRef();
	const loadOnMount = true;
	const onAdFailedToLoad = (event) => {
		setError(true);
		setLoading(false);
		/**
		 * Sometimes when you try to load an Ad, it will keep failing
		 * and you will recieve this error: "The ad request was successful,
		 * but no ad was returned due to lack of ad inventory."
		 *
		 * This error is not a bug or issue with our Library.
		 * Just remove the app from your phone & clean your build
		 * folders by running ./gradlew clean in /android folder
		 * and for iOS clean the project in xcode. Hopefully the error will
		 * be gone.
		 *
		 * [iOS] If you get this error: "Cannot find an ad network adapter with
		 * the name(s): com.google.DummyAdapter". The ad inventory is empty in your
		 * location. Try using a vpn to get ads in a different location.
		 *
		 * If you have recently created AdMob IDs for your ads, it might take
		 * a few days until the ads will start showing.
		 */
		Logger('AD', 'FAILED', event.error.message);
	};
	const onAdLoaded = () => {
		Logger('AD', 'LOADED', 'Ad has loaded successfully');
	};

	const onAdClicked = () => {
		Logger('AD', 'CLICK', 'User has clicked the Ad');
	};

	const onAdImpression = () => {
		Logger('AD', 'IMPRESSION', 'Ad impression recorded');
	};

	const onUnifiedNativeAdLoaded = (event) => {
		Logger('AD', 'RECIEVED', 'Unified ad  Recieved', event);
		setLoading(false);
		setLoaded(true);
		setError(false);
	};
	const onAdLeftApplication = () => {
		Logger('AD', 'LEFT', 'Ad left application');
	};

	const onViewableItemsChanged = (event) => {
		/**
		 * [STEP IV] We check if any AdViews are currently viewable.
		 */
		const viewableAds = event.viewableItems.filter(
			i => i.key.indexOf('ad') !== -1
		);

		viewableAds.forEach((adView) => {
			if (adView.index === index && !loaded) {
			/**
			 * [STEP V] If the ad is viewable and not loaded
			 * already, we will load the ad.
			 */
				setLoading(true);
				setLoaded(false);
				setError(false);
				Logger('AD', 'IN VIEW', `Loading ${ index }`);
			nativeAdRef.current?.loadAd();
			} else if (loaded) {
			/**
			 * We will not reload ads or load
			 * ads that are not viewable currently
			 * to save bandwidth and requests sent
			 * to server.
			 */ return (
					Logger('AD', 'IN VIEW', `Loaded ${ index }`)
				);
			} else {
				return (
					Logger('AD', 'NOT IN VIEW', index)
				);
			}
		});
	};
	useEffect(() => {
		/**
		 * for previous steps go to List.js file.
		 *
		 * [STEP III] We will subscribe to onViewableItemsChanged event in all AdViews in the List.
		 */
		if (!loadOnMount) {
			DeviceEventEmitter.addListener(
				Events.onViewableItemsChanged,
				onViewableItemsChanged
			);
		}

		return () => {
			if (!loadOnMount) {
				DeviceEventEmitter.removeListener(
					Events.onViewableItemsChanged,
					onViewableItemsChanged
				);
			}
		};
	}, [loaded]);
	useEffect(() => {
		if (loadOnMount) {
			setLoading(true);
			setLoaded(false);
			setError(false);
		nativeAdRef.current?.loadAd();
		}
		return () => {
			setLoaded(false);
		};
	}, [type]);
	return (
		<View>
			<NativeAdView
				style={styles.NativeAd}
				ref={nativeAdRef}
				adUnitID={adUnitIDs.image}
				// refreshInterval={6000 * 2}
				mediationOptions={{ nativeBanner: true }}
				onAdLoaded={onAdLoaded}
				onAdFailedToLoad={onAdFailedToLoad}
				onAdLeftApplication={onAdLeftApplication}
				onAdClicked={onAdClicked}
				onAdImpression={onAdImpression}
				onUnifiedNativeAdLoaded={onUnifiedNativeAdLoaded}
			>
				<View style={styles.SubAdContainer}>
					<View style={styles.IconAdView}>
						<IconView style={styles.IconView} />
						<View style={styles.AdvertiserContainer}>
							<View style={styles.AdvertiserSubContainer}>
								<AdvertiserView numberOfLines={1} style={[styles.AdvertiserView, { color: themes[theme].backdropColor }]} />
								<View style={styles.AdBageView}>
									<AdBadge style={styles.Adbage} textStyle={styles.AdbageFontStyle} />
								</View>
							</View>
							<HeadlineView numberOfLines={1} style={[styles.HeadLineViewFontStyle, { color: themes[theme].backdropColor }]} />
							<TaglineView numberOfLines={1} style={[styles.TagLineFontStyle, { color: themes[theme].backdropColor }]} />
						</View>
						<StoreView
							style={{
								fontSize: 12
							}}
						/>
						<StarRatingView
							starSize={12}
							fullStarColor='orange'
							emptyStarColor='gray'
							containerStyle={{
								width: 65,
								marginLeft: 10
							}}
						/>
						<CallToActionView
							numberOfLines={1}
							style={styles.CallToActionView}
							textStyle={styles.CallToActionViewFontStyle}
							buttonAndroidStyle={{
								backgroundColor: '#0099ff',
								borderRadius: 5
							}}
						/>
					</View>
				</View>
			</NativeAdView>
		</View>
	);
});
AdmobView.propTypes = {
	theme: PropTypes.string,
	index: PropTypes.number,
	type: PropTypes.string
};

export default AdmobView;

````

**Comment by yaroslavnikiforov** [comment]
I don't see anything wrong in your code if your unit id is mapped to Native Banner (double-check that please).

**Comment by faz1993** [comment]
@faz1993 i will try again

**Comment by faz1993** [comment]
@yaroslavnikiforov still same maybe because i didnt verified my facebook business ? or duo i didnt put it in live ?
