### ISSUE TITLE
refreshInterval on v0.3.9 is not working

### ISSUE THREAD

**Issue by tanwanjern** [ammarahm-ed/react-native-admob-native-ads#132]
I'm trying to show the native ad unit from the ad manager using v0.3.9.

The ad unit will auto-refresh every 1 minute to another ad unit. I wanted to pause the refresh, but it couldn't so I tried to increase the interval but it doesn't work (it's still refreshing every 1 minute)

```
<NativeAdView
  refreshInterval={60000*10} //10minutes
  ref={nativeAdRef}
  adUnitID={unitId}>
...
</NativeAdView>
```
From the Ad Manager, the refresh rate of the ad unit is already set to no refresh
![image](https://user-images.githubusercontent.com/23072805/110438320-33d4f480-80f1-11eb-8b90-f0168e7bfd09.png)

**Comment by Hassan709** [comment]
when i can move to next screen NativeMediaAds videos sound not stop Why???

**Comment by Hassan709** [comment]
import { NativeMediaView } from "react-native-admob-native-ads";

<MediaView
  style={{
    width: "100%",
    height: 250,
  }}
/>;
import is NativeMediaView  and use MediaView Why ???in offical document

**Comment by ammarahm-ed** [comment]
update to 0.4.1
