### ISSUE TITLE
NativeMediaView issue

### ISSUE THREAD

**Issue by Hassan709** [ammarahm-ed/react-native-admob-native-ads#133]
NativeMediaView issue Video not Stop when navigate to another screen  .....?

const MediaViewAds = React.memo(({ index, loadOnMount = true }) => {
    const [aspectRatio, setAspectRatio] = useState(1.5);
    const [loading, setLoading] = useState(false);
    const [loaded, setLoaded] = useState(false);
    const [error, setError] = useState(false);
    const nativeAdRef = useRef();

    const onAdFailedToLoad = (event) => {
        setError(true);
        setLoading(false);
        console.log('AD', 'FAILED', event.error.message);
    };

    const onAdLoaded = () => {
        console.log('AD', 'LOADED', 'Ad has loaded successfully');
    };

    const onAdClicked = () => {
        console.log('AD', 'CLICK', 'User has clicked the Ad');
    };

    const onAdImpression = () => {
        console.log('AD', 'IMPRESSION', 'Ad impression recorded');
    };

    const onUnifiedNativeAdLoaded = (event) => {
        console.log('AD', 'RECIEVED', 'Unified ad  Recieved', event);
        setLoading(false);
        setLoaded(true);
        setError(false);
        setAspectRatio(event.aspectRatio);
    };

    const onAdLeftApplication = () => {
        console.log('AD', 'LEFT', 'Ad left application');
    };

    const onViewableItemsChanged = (event) => {
        let viewableAds = event.viewableItems.filter(
            (i) => i.key.indexOf('ad') !== -1,
        );

        viewableAds.forEach((adView) => {
            if (adView.index === index && !loaded) {
                setLoading(true);
                setLoaded(false);
                setError(false);
                console.log('AD', 'IN VIEW', 'Loading ' + index);
                nativeAdRef.current?.loadAd();
            } else {
                if (loaded) {
                    console.log('AD', 'IN VIEW', 'Loaded ' + index);
                } else {
                    console.log('AD', 'NOT IN VIEW', index);
                }
            }
        });
    };

    useEffect(() => {
        if (!loadOnMount) {
            DeviceEventEmitter.addListener(
                Events.onViewableItemsChanged,
                onViewableItemsChanged,
            );
        }

        return () => {
            if (!loadOnMount) {
                DeviceEventEmitter.removeListener(
                    Events.onViewableItemsChanged,
                    onViewableItemsChanged,
                );
            }
        };
    }, [loaded]);

    useEffect(() => {
        if (loadOnMount) {
            setLoading(true);
            setLoaded(false);
            setError(false)
            nativeAdRef.current?.loadAd();
        }
        return () => {
            setLoaded(false);
        };
    }, []);

    return (
        <View
            style={{
                backgroundColor: '#fff',
                width: '100%',
                alignItems: 'center',
            }}>
            <NativeAdView
                ref={nativeAdRef}
                onAdLoaded={onAdLoaded}
                onAdFailedToLoad={onAdFailedToLoad}
                onAdLeftApplication={onAdLeftApplication}
                onAdClicked={onAdClicked}
                onAdImpression={onAdImpression}
                onUnifiedNativeAdLoaded={onUnifiedNativeAdLoaded}
                style={{
                    width: '98%',
                    alignSelf: 'center',
                }}
                //adUnitID="----------------------"
            >
                <View
                    style={{
                        width: '100%',
                        alignItems: 'center',
                    }}>
                        </View>
                        <AdBadge
                            textStyle={{ color: "#fff", fontSize: 14, fontWeight: 'bold' }}
                        />
                        <View
                            style={{
                                marginTop: 15
                            }}>
                            <NativeMediaView
                                style={{
                                    width: "98%",
                                    height: hp("18%"),
                   
                            />
                        </View>
                        <View
                            style={{
                                width: "100%",
                                marginTop: 15,
                                paddingHorizontal: 15,
                            }}>
                            <HeadlineView
                                style={{
                                    fontWeight: "bold",
                                    fontSize: 13,
                                }}
                            />
                            <TaglineView
                                numberOfLines={2}
                                style={{
                                    fontSize: 11,
                                }}
                            />
                            <AdvertiserView
                                style={{
                                    fontSize: 10,
                                    color: "gray",
                                }}
                            />
                        </View>

                        <View style={{ position: 'absolute', bottom: 10, alignSelf: 'center' }}>
                            <CallToActionView
                                style={{
                                    alignItems: "center",
                                    borderRadius: 5,
                                    elevation: 10,
                                }}
                                textStyle={{ color: "white", fontSize: RFValue(14) }}
                            />
                        </View>
            </NativeAdView>
        </View >
    );
});
export default MediaViewAds;

**Comment by Hassan709** [comment]
@ammarahm-ed  please tell me how to mute Native media ads in react native

**Comment by Hassan709** [comment]
when i navigate to another screen native media ads not stop and i can hear volume in back of every screen...

**Comment by ammarahm-ed** [comment]
use the paused prop on NativeMediaView for this to pause the video when you navigate away.
