### ISSUE TITLE
Ads stop loading if unmount NativeAdView before it had finished downloading on iOS

### ISSUE THREAD

**Issue by yaroslavnikiforov** [ammarahm-ed/react-native-admob-native-ads#135]
On iOS if you unmount NativeAdView during loading ad is in progress ads will stop loading anymore and you need to kill the app to make it work again. The issue is only present on iOS.
Steps to reproduce: run example app on ios, open some ad, for example, Ad with Video, and press the back button immediately while it is loading.

**Comment by ammarahm-ed** [comment]
Fixed on master, reopen if face problem
