### ISSUE TITLE
Video ads are not working (tried the example app)

### ISSUE THREAD

**Issue by paddy57** [ammarahm-ed/react-native-admob-native-ads#14]
In your example i switched ad unit id to video ads, I have added the MediView from react-native-admob-native-ads, but with test ad unit id, i always get the this error message `"The ad request was successful, but no ad was returned due to lack of ad inventory."`

here is my code 

```
import React from 'react';
import { View, Platform } from 'react-native';
import NativeAdView, {
  CallToActionView,
  MediaView,
  IconView,
  HeadlineView,
  TaglineView,
  AdvertiserView,
} from 'react-native-admob-native-ads';

const NATIVE_AD_ID =
  Platform.OS === 'ios'
    ? 'ca-app-pub-3940256099942544/3986624511'
    : 'ca-app-pub-3940256099942544/2247696110';

const NATIVE_AD_VIDEO_ID =
  Platform.OS === 'ios'
    ? 'ca-app-pub-3940256099942544/2521693316'
    : 'ca-app-pub-3940256099942544/1044960115';

const App = () => {
  const _onAdFailedToLoad = event => {
    console.log(event.nativeEvent);
  };

  const _onAdLoaded = () => {
    console.log('Ad has loaded');
  };

  return (
    <View
      style={{
        height: '100%',
        width: '100%',
        justifyContent: 'center',
      }}>
      <View>
        <NativeAdView
          onAdLoaded={_onAdLoaded}
          onAdFailedToLoad={_onAdFailedToLoad}
          onUnifiedNativeAdLoaded={() => { }}
          style={{
            width: '95%',
            alignSelf: 'center',
            height: 400,
          }}
          adUnitID={NATIVE_AD_VIDEO_ID} // REPLACE WITH NATIVE_AD_VIDEO_ID for video ads.
        >
          <View
            style={{
              height: 400,
              width: '100%',
              backgroundColor: 'white',
            }}>
            <MediaView
              style={{
                backgroundColor:'red',
                width: "100%",
                height: 250,
              }}
            />

          </View>
        </NativeAdView>
      </View>
    </View>
  );
};

export default App;
```

**Comment by ammarahm-ed** [comment]
remove the app from your phone. Clear the build folder and run again after changing the Ad Unit Ids

**Comment by paddy57** [comment]
Yeah, it worked, any reason why it was not working with the previous build?

**Comment by ammarahm-ed** [comment]
@paddy57 old cached data that google admob does not like.

**Comment by shekharskamble** [comment]
@ammarahm-ed I tried above method but did not work :( be it test ids or my ad id, only media view is not loading, am I missing something?
![20200508_090915](https://user-images.githubusercontent.com/8002785/81359622-3ac75b00-910c-11ea-882f-7db83b283621.png)

**Comment by ammarahm-ed** [comment]
@shekharskamble this should not happen, are you on the latest version? And you are facing this issue on android or iOS? Set a width and height for mediaView and also give it a background color to see if it is there or or not when the ad loads

**Comment by ammarahm-ed** [comment]
@shekharskamble clone this repo and try the example app, see if the problem is there in example app too.

**Comment by shekharskamble** [comment]
@ammarahm-ed thank you so much for your reply. example app and my app-ids are working on ios but for android its still the same issue. tried changing background color and its applies. if I just enabled image ads from google ad-mob console its working there is an issue with video ads for android. I think its not from this repo. 
Great work! thank you so much for putting this together.

**Comment by VanHop94** [comment]
> @ammarahm-ed I tried above method but did not work :( be it test ids or my ad id, only media view is not loading, am I missing something? ![20200508_090915](https://user-images.githubusercontent.com/8002785/81359622-3ac75b00-910c-11ea-882f-7db83b283621.png)

Hi @shekharskamble Did you resolve this issue?
