### ISSUE TITLE
Will Ad requests be made when the device screen is turned off

### ISSUE THREAD

**Issue by aleluiah** [ammarahm-ed/react-native-admob-native-ads#140]
hi, great project. will ad requests be made when the device screen is turned off, thanks.

**Comment by ammarahm-ed** [comment]
If the app is running, yes I think so.

**Comment by aleluiah** [comment]
won't it result in violation of admob policy

**Comment by ammarahm-ed** [comment]
> won't it result in violation of admob policy

You have to handle that using `AppState`. Make sure you are on the latest version. And make sure you do not make ad requests when screen is off.
