### ISSUE TITLE
Resolving multiple pod dependencies & versions

### ISSUE THREAD

**Issue by Terfender** [ammarahm-ed/react-native-admob-native-ads#141]
Hello there,

I am trying to install both this lib for native ads and rnfirebase/admob for banner/rewarded ads.
I would love to use v0.4.0 of this lib as it solves the memory leak issue. However, when installing both pods, I get this error:

```
[!] CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":
  In Podfile:
    Google-Mobile-Ads-SDK (= 8.0.0)

    RNFBAdMob (from `../node_modules/@react-native-firebase/admob`) was resolved to 11.2.0, which depends on
      Firebase/AdMob (= 7.9.0) was resolved to 7.9.0, which depends on
        Google-Mobile-Ads-SDK (~> 7.66)
```

Do you know how I can resolve it please?
I know this is pod dependencies issue, but couldn't find a workaround and wondering if someone using my usecase and got it working.

Thanks

**Comment by comdeslezards** [comment]
I get this error too

**Comment by ammarahm-ed** [comment]
update to 0.4.1
