### ISSUE TITLE
Doesn't work with latest Mobile Ads SDK on Android (20.0.0)

### ISSUE THREAD

**Issue by yaroslavnikiforov** [ammarahm-ed/react-native-admob-native-ads#146]
After Google released SDK v20 this package stopped working as it uses the latest version.
[https://developers.google.com/admob/android/migration](https://developers.google.com/admob/android/migration)

**Comment by JoonDong2** [comment]
Use this temporarily.
https://github.com/JoonDong2/react-native-admob-native
`yarn add https://github.com/JoonDong2/react-native-admob-native`

**Comment by Bsingh2697** [comment]
inside node modules/react-native-admob-native-ads/android/build.gradle 
comment this line
implementation "com.google.android.gms:play-services-ads:+"

**Comment by Bsingh2697** [comment]
> After Google released SDK v20 this package stopped working as it uses the latest version.
> https://developers.google.com/admob/android/migration
inside node modules/react-native-admob-native-ads/android/build.gradle
comment this line
implementation "com.google.android.gms:play-services-ads:+"
or set it to 19.8.0
implementation "com.google.android.gms:play-services-ads:19.8.0"

**Comment by teamzz111** [comment]
> inside node modules/react-native-admob-native-ads/android/build.gradle
> comment this line
> implementation "com.google.android.gms:play-services-ads:+"

Did you send PR ?

**Comment by Bsingh2697** [comment]
> > inside node modules/react-native-admob-native-ads/android/build.gradle
> 
> > comment this line
> 
> > implementation "com.google.android.gms:play-services-ads:+"
> 
> 
> 
> Did you send PR ?

No

**Comment by fdobre** [comment]
PR: created https://github.com/ammarahm-ed/react-native-admob-native-ads/pull/150

Please let me know if there is anything that can be improved in the PR.

**Comment by Bsingh2697** [comment]
> PR: created https://github.com/ammarahm-ed/react-native-admob-native-ads/pull/150
> 
> 
> 
> Please let me know if there is anything that can be improved in the PR.

Thanks but as I said 19.8.0 is a better option. Coz that was the last supported version. Commenting the service can lead to some other issue. Idk yet but maybe.

**Comment by fdobre** [comment]
> > PR: created #150
> > Please let me know if there is anything that can be improved in the PR.
> 
> Thanks but as I said 19.8.0 is a better option. Coz that was the last supported version. Commenting the service can lead to some other issue. Idk yet but maybe.

@Bsingh2697   PR updated

**Comment by Bsingh2697** [comment]
> > > PR: created #150
> 
> > > Please let me know if there is anything that can be improved in the PR.
> 
> > 
> 
> > Thanks but as I said 19.8.0 is a better option. Coz that was the last supported version. Commenting the service can lead to some other issue. Idk yet but maybe.
> 
> 
> 
> @Bsingh2697   PR updated

Thanks 😊
