### ISSUE TITLE
i need a trigger for store touch event

### ISSUE THREAD

**Issue by cokepizza** [ammarahm-ed/react-native-admob-native-ads#149]
i generated issue before, but i need this functionality very much
in my application, when i swipe ad, i want to trigger store touch event, so that i can make viewer to see ads
in short, Is there any way I can get the store url or trigger a touch? Currently, I am looking for an action to give the same effect as pressing an advertisement.
I am using this great library very well, and I hope you make this feature.
If the method of triggering advertisement is diversified, it will be possible to create advertisement more flexible in this library.

**Comment by ammarahm-ed** [comment]
@cokepizza kindly send me some more information about this. Have you seen it implemented in other libraries, how? send me some video or link to an app that uses it.

**Comment by ammarahm-ed** [comment]
We do not have access to direct urls but possibly, a click event can be triggered. It depends if the SDK allows such functionality or not.

**Comment by cokepizza** [comment]
If so, is there no way to do it with your library alone without sdk support? Is there a possibility that this feature will be introduced after sdk review? I really need this feature

**Comment by ammarahm-ed** [comment]
@cokepizza no its not possible without sdk support however I think I have seen that it is possible. I will investigate.

**Comment by cokepizza** [comment]
@ammarahm-ed , Thank you! This is a must-have feature for me. If supported, I'm looking forward to seeing that I can make a much more fancy app. Thank you for your kindness and for creating an amazing library. Thanks to you, I was able to easily apply most of admob.
