### ISSUE TITLE
[Android] MoPub SDK requires an Activity context to initialize.

### ISSUE THREAD

**Issue by halaei** [ammarahm-ed/react-native-admob-native-ads#151]
I was working with admob initialization and find out there is an issue with `setRequestConfiguration()` that I don't know how to fix.

Apparently, we should pass MainActivity context to MobileAds.initialize(), but currently application context is used, which causes issues for mopub. Here is my changes so far:
```
   @ReactMethod
    public void setRequestConfiguration(ReadableMap config, Promise promise) {
        ...
        MobileAds.initialize(getReactApplicationContext(), (InitializationStatus status) -> {
            WritableMap map = Arguments.createMap();
            for (Map.Entry<String, AdapterStatus> entry: status.getAdapterStatusMap().entrySet()) {
                WritableMap info = Arguments.createMap();
                info.putString("initialization_state", entry.getValue().getInitializationState().toString());
                info.putString("description", entry.getValue().getDescription());
                map.putMap(entry.getKey(), info);
            }
            promise.resolve(map);
        });
```
Output in javascript tells me that mopub is not ready and the reason is that it requires activity context:
```
com.google.ads.mediation.mopub.MoPubMediationAdapter: {
 description: "MoPub SDK requires an Activity context to initialize.",
 initialization_state: "NOT_READY"
}
```

Passing activity context, `getReactApplicationContext().getCurrentActivity()`, fixes the issue. However, if app is started from background, e.g. by push notification, getCurrentActivity() being null causes a crash. Therefore it won't be safe to call setRequestConfiguration().

According to https://developers.google.com/admob/android/quick-start#initialize_the_mobile_ads_sdk, initialization needs to be done once. App should wait for initialization to be completed before requesting ads. In their example, initialization is called inside MainActivity.

So in a react native application, I guess we must call setRequestConfiguration() only once, and only after MainActivity is loaded. Does it mean we must call it inside the root App component? Or maybe react-native has a hook for MainActivity onCreated() event?

**Comment by ammarahm-ed** [comment]
@halaei Can you give a bit of background context to your issue? You are trying to mediate ads from MoPub SDK using this library? is that correct? A little of what I understand, you can `getReactApplicationContext().getCurrentActivity() != null` and then do everything you need inside it so that, the application does not crash. Although you may note that after a few seconds the activity will be available in the context. 

> So in a react native application, I guess we must call setRequestConfiguration() only once, and only after MainActivity is loaded. Does it mean we must call it inside the root App component? Or maybe react-native has a hook for MainActivity onCreated() event?

You can call it in `index.js` file.

**Comment by halaei** [comment]
Yes, I am trying to use MoPub via AdMob mediation. Based on Admob docs, MoPub mediation has no extra code requirements, other than adding their sdk.
I think I can send a PR here that have these changes:
1. Use activity instead of application context, if activity is loaded.
2. Add a promise parameter to `setRequestConfiguration()` java function and resolve with initialization status when initialization is complete.
3. Don't call `MobileAds.initialize()` anywhere except in `setRequestConfiguration()`. So developers must either call `setRequestConfiguration()` before requesting any ad or they can call `MobileAds.initialize()` themselves.

> You can call it in `index.js` file.

I shouldn't. Because in `index.js` `MainActivity` might not be present. The best place to call `setRequestConfiguration()` seems to be in `App.js`, in the root component's constructor.

**Comment by ammarahm-ed** [comment]
> Yes, I am trying to use MoPub via AdMob mediation. Based on Admob docs, MoPub mediation has no extra code requirements, other than adding their sdk.
> I think I can send a PR here that have these changes:
> 1. Use activity instead of application context, if activity is loaded.
> 2. Add a promise parameter to `setRequestConfiguration()` java function and resolve with initialization status when initialization is complete.
> 3. Don't call `MobileAds.initialize()` anywhere except in `setRequestConfiguration()`. So developers must either call `setRequestConfiguration()` before requesting any ad or they can call `MobileAds.initialize()` themselves.
> 
> > You can call it in `index.js` file.
> 
> I shouldn't. Because in `index.js` `MainActivity` might not be present. The best place to call `setRequestConfiguration()` seems to be in `App.js`, in the root component's constructor.

Hmm it does make sense. Converting it into a promise seems to be the safest way. Also there seems to be no benefit of calling it in index.js. Send in a PR then.
