### ISSUE TITLE
Ads gets reloaded in background

### ISSUE THREAD

**Issue by haresh4d** [ammarahm-ed/react-native-admob-native-ads#152]
I have two screens "Home Screen" and "Detail Screen". I have put a Native Ad in the home screen. Even when I navigate to detail screen the Native Ad  in the home screen gets reloaded after 60 every minute(onAdLoaded) method is called. what to do? This is generating so many impressions on admob and thats why eCPM becomes too low. Please suggest how to dispose the AdView component after navigating to another screen.

**Comment by ammarahm-ed** [comment]
@haresh4d what version of library are you using?

**Comment by haresh4d** [comment]
I am using 0.3.9. And I have to use it because I am also using react-native-admob which requires Google Mobile SDK 7.69

**Comment by ammarahm-ed** [comment]
> I am using 0.3.9. And I have to use it because I am also using react-native-admob which requires Google Mobile SDK 7.69

If you are using v0.3.9 then you need to set "refreshInterval" to a big number so it never refreshes after first loading. Or you can destroy the AdView when use navigates to next screen.

The latest version does not have this issue.

**Comment by haresh4d** [comment]
Thanks @ammarahm-ed for your reply. I have currently used a large number for refreshInterval to solve the issue. But I dont know how to destroy the AdView before navigating to another screen. Can you please share some link from where I can get it? 

Thanks for the help.

**Comment by ammarahm-ed** [comment]
Are you using `react-navigation`? If so there is a hook you can use "useFocusEffect" to detect it the screen is focused or not. Although it might affect performance a bit since it will cause rerender of whole screen.

Also test the `refreshInterval` workaround to see if it is actually working.

**Comment by haresh4d** [comment]
```refreshInterval``` is a perfect workaround. It is working. After this soluions the impressions have drastically reduced. I think this is the best solution till I can use the latest version.
