### ISSUE TITLE
react-native-vector-icons

### ISSUE THREAD

**Issue by alexmngn** [ammarahm-ed/react-native-admob-native-ads#159]
react-native-vector-icons is a library adding a huge amount of fonts/icons that are not needed for most projects.
Have it as a peer dependency is making most app 1MB bigger just to use a few small icons. 
Would be worth looking into removing this peer dependency to use anything smaller, even maybe simple pngs might be better. 

One better option would be to let anyone decide the icons they want to use by passing the icon as JSX props like this:

```
export default function StarView({
  style = undefined,
  stars,
  FullIcon,
  HalfIcon,
  EmptyIcon,
  passRef,
  ...passThroughProps
}) {
```

**Comment by ammarahm-ed** [comment]
You can exclude the icons you do not want. You should check docs for react-native-vector-icons. Although i will make this configurable in a future release. If you would like to send a PR, please do.
