### ISSUE TITLE
[IOS] Component 'RNGADMediaView' re-registered direct event 'topVideoEnd' as a bubbling event

### ISSUE THREAD

**Issue by pqminh997** [ammarahm-ed/react-native-admob-native-ads#161]
Error while running app. Please help me

//version
"react-native-admob-native-ads": "0.4.1"

//Podfile
pod 'Google-Mobile-Ads-SDK', '7.69.0'
pod 'GoogleMobileAdsMediationFacebook', '6.2.1.0'

![Screen Shot 2021-05-12 at 13 40 13](https://user-images.githubusercontent.com/58838161/117930298-07736980-b328-11eb-8865-6d821c16d9b4.png)

**Comment by FairWageFreelancing** [comment]
same here - bump.

**Comment by FairWageFreelancing** [comment]
Try adding the following to your AppDelegate.m

#import <GoogleMobileAds/GoogleMobileAds.h>

and put this...

[[GADMobileAds sharedInstance] startWithCompletionHandler:nil];

in... 

@implementation AppDelegate
- (BOOL)application:(UIApplication *)application    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {  // Initialize Google Mobile Ads SDK  [[GADMobileAds sharedInstance] startWithCompletionHandler:nil];
  return YES;}
@end

Doing the proper installation fixed the error for me.

**Comment by ammarahm-ed** [comment]
Provide some detail to reproduce the problem.

**Comment by abbasmoosavi** [comment]
@JinHao-L 
This error still exists, please help me!

**Comment by JinHao-L** [comment]
@abbasmoosavi
I think will have to wait for the owner to make a new release. You can make a temporary patch for it in the mean time

**Comment by ammarahm-ed** [comment]
> @abbasmoosavi
> I think will have to wait for the owner to make a new release. You can make a temporary patch for it in the mean time

The issue is fixed on master branch. You can use it until a new version is released

**Comment by abbasmoosavi** [comment]
> > @abbasmoosavi
> > I think will have to wait for the owner to make a new release. You can make a temporary patch for it in the mean time
> 
> The issue is fixed on master branch. You can use it until a new version is released

And in master branch exist some problems in iOS
