### ISSUE TITLE
Blank ads in the version of 0.4.1

### ISSUE THREAD

**Issue by ajoykarmakar** [ammarahm-ed/react-native-admob-native-ads#167]
After update to the latest version of this library the ad I got completely blank only ad badge is showing. How can I fix this? or should I need to use the old version of the library? 

package - 
```
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-admob-native-ads": "0.4.1",
```

**Comment by ammarahm-ed** [comment]
Read the documentation -> Migration guide for 0.4.0+ version of library
