### ISSUE TITLE
Firebase cloud messaging and analysis consent

### ISSUE THREAD

**Issue by aleluiah** [ammarahm-ed/react-native-admob-native-ads#168]
do i need to show another consent form apart from ads consent form, to users in eea when using analytics and cloud messaging in my project or do they ad consent covers all firebase platform products example firebase analytics and cloud messaging

**Comment by ammarahm-ed** [comment]
I am not sure about that. You should check the respective docs etc for each feature to see what kind of consent you need for each or if only the ads consent is enough
