### ISSUE TITLE
 Invariant Violation: requireNativeComponent: "MediaView" was not found in the UIManager

### ISSUE THREAD

**Issue by paddy57** [ammarahm-ed/react-native-admob-native-ads#17]
I am getting this error 
"react": "16.8.6",
"react-native": "0.60.5",

`Invariant Violation: Invariant Violation: Invariant Violation: requireNativeComponent: "MediaView" was not found in the UIManager`

![Screenshot_20200428-122058_Stumbler](https://user-images.githubusercontent.com/22058036/80456628-8e3aeb80-894b-11ea-8d9c-6cddad530c8c.jpg)

**Comment by ammarahm-ed** [comment]
Can you reproduce this error in the Example App?

**Comment by paddy57** [comment]
Can you reproduce this error in the Example App? --> No, I'm not able to reproduce 
 clear your build folder, and node_modules folder then run yarn again. --> Done this, still getting `requireNativeComponent: "MediaView" was not found in the UIManager` 
I'm using
"react": "16.8.6",
"react-native": "0.60.5",
 "react-native-admob-native-ads": "^0.2.6",
 "react-native-admob": "git+https://git@github.com/paddy57/react-native-admob.git",

**Comment by paddy57** [comment]
The issue gets resolved for me by the following step
1. removed react-native-admob (it was installed in my project already)
2. react-native link  react-native-admob-native-ads
3. delete node_module, delete package-lock.json,
4. npm install,  clean project 
5. build app
