### ISSUE TITLE
Conflict with https://github.com/react-native-video/react-native-video

### ISSUE THREAD

**Issue by ninacoder-info** [ammarahm-ed/react-native-admob-native-ads#170]
Conflict with https://github.com/react-native-video/react-native-video

![59310973-9e7fa480-8c6d-11e9-8bc5-9be4080dec32](https://user-images.githubusercontent.com/63708869/120070783-5eae6380-c0b6-11eb-819c-e18d23fd3a50.png)

Sadly I need to use both of them :(

**Comment by joseym90** [comment]
I have the same Issue

**Comment by ammarahm-ed** [comment]
fixed on master
