### ISSUE TITLE
Use of undeclared identifier 'kDFPSimulatorID'

### ISSUE THREAD

**Issue by teamzz111** [ammarahm-ed/react-native-admob-native-ads#172]
I'm running latest versions of react native admob-native-ads,

reactnative 0.64 
<img width="427" alt="Captura de Pantalla 2021-05-31 a la(s) 11 39 35 a  m" src="https://user-images.githubusercontent.com/37392536/120221968-e1453900-c204-11eb-897c-b5d5275148e0.png">

<img width="1220" alt="Captura de Pantalla 2021-05-31 a la(s) 11 39 10 a  m" src="https://user-images.githubusercontent.com/37392536/120221929-d25e8680-c204-11eb-8d14-462731777ed4.png">

`
    };
    
    if ([[config allKeys] containsObject:@"testDeviceIds"]) {
        NSArray *testDevices = RNAdMobProcessTestDevices([config valueForKey:@"testDeviceIds"],kDFPSimulatorID);
        [[[GADMobileAds sharedInstance] requestConfiguration] setTestDeviceIdentifiers:testDevices];
    };
}
`

**Comment by juceda** [comment]
I confirm that. It happened to me too, with XCode 12.4.

**Comment by neocative** [comment]
+1

I am on Xcode Version 12.5 and RN 0.63.2

**Comment by ammarahm-ed** [comment]
Seems like you have installed v8 of Google Mobile ads sdk. Downgrade to 7.6x

**Comment by IyiolaOwabumowa** [comment]
Any solution?

**Comment by teamzz111** [comment]
> Seems like you have installed v8 of Google Mobile ads sdk. Downgrade to 7.6x

    react-native-admob-native-ads (from `../node_modules/react-native-admob-native-ads`) was resolved to 0.4.0, which depends on
      GoogleMobileAdsMediationFacebook was resolved to 6.4.1.0, which depends on
        Google-Mobile-Ads-SDK (>= 8.4.0)

**Comment by teamzz111** [comment]
iN ADDITION 
<img width="361" alt="Captura de Pantalla 2021-06-11 a la(s) 6 01 06 p  m" src="https://user-images.githubusercontent.com/37392536/121756224-00827700-cadf-11eb-80a2-250fa8fe6216.png">

**Comment by xsephtion** [comment]
I fixed mine by adding `pod 'Google-Mobile-Ads-SDK' , '7.69.0'` to podfile

**Comment by eastrd** [comment]
- Following the example code `pod 'Google-Mobile-Ads-SDK', '8.7.0'` didn't work
- Using others suggested `pod 'Google-Mobile-Ads-SDK', '7.69.0'` didn't work either, the same error as @teamzz111 mentioned above

**Comment by ammarahm-ed** [comment]
> - Following the example Podfile `pod 'Google-Mobile-Ads-SDK', '8.7.0'` didn't work - Same error as @teamzz111 mentioned in the title
> - Using others suggested `pod 'Google-Mobile-Ads-SDK', '7.69.0'` didn't work either - Same dependency error as @teamzz111 mentioned above

Use master branch.

**Comment by ammarahm-ed** [comment]
> > - Following the example Podfile `pod 'Google-Mobile-Ads-SDK', '8.7.0'` didn't work - Same error as @teamzz111 mentioned in the title
> > - Using others suggested `pod 'Google-Mobile-Ads-SDK', '7.69.0'` didn't work either - Same dependency error as @teamzz111 mentioned above
> 
> Use master branch, not npm to use the latest version.
