### ISSUE TITLE
Support for Interstitial Ads

### ISSUE THREAD

**Issue by haresh4d** [ammarahm-ed/react-native-admob-native-ads#173]
@ammarahm-ed, If someone can implement support for the Interstitial Ads in this library developers wont have to use different library for that. As Custom banners can be created with this library the only remaining part is Interstitial Ads. If there are possibilities, nothing wrong in exploring them.

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed, If someone can implement support for the Interstitial Ads in this library developers wont have to use different library for that. As Custom banners can be created with this library the only remaining part is Interstitial Ads. If there are possibilities, nothing wrong in exploring them.

You can make one yourself using the components provided.

**Comment by haresh4d** [comment]
Great Idea. Do you mean we should display native ad in full screen modal?

**Comment by ammarahm-ed** [comment]
> Great Idea. Do you mean we should display native ad in full screen modal? 

Yes.
