### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNGADNativeView

### ISSUE THREAD

**Issue by aftabaminzoobiapps** [ammarahm-ed/react-native-admob-native-ads#174]
issue since i Update to version `  "react-native-admob-native-ads": "^0.4.1",`
`
Invariant Violation: Tried to register two views with the same name RNGADNativeView`

**Comment by teamzz111** [comment]
+1

**Comment by teamzz111** [comment]
<img width="619" alt="Captura de Pantalla 2021-06-11 a la(s) 7 15 55 p  m" src="https://user-images.githubusercontent.com/37392536/121759027-72f85480-cae9-11eb-966c-7c9c5ee19a4d.png">

**Comment by ammarahm-ed** [comment]
fixed on master
