### ISSUE TITLE
Tried to register two views with the same name GestureHandlerRootView

### ISSUE THREAD

**Issue by paddy57** [ammarahm-ed/react-native-admob-native-ads#18]
My project already have  "react-native-gesture-handler": "^1.5.6",
 "react": "16.8.6",
 "react-native": "0.60.5",

and when i installed react-native-admob-native-ads i get the following error 
![Screenshot_20200428-123455_Stumbler](https://user-images.githubusercontent.com/22058036/80457524-140b6680-894d-11ea-9863-81841b1e78f9.jpg)

**Comment by paddy57** [comment]
Delete your package-lock.json or yarn.lock, delete node_modules, run npm install or yarn again
this solved above error for me

**Comment by rogerkerse** [comment]
I had the same issue but for me updating `react-native-gesture-handler` to the same version as this libraries package.json refers to worked (1.6.1)
