### ISSUE TITLE
Video not pausing when navigating another page ( tried the Paused prop)

### ISSUE THREAD

**Issue by dev007github** [ammarahm-ed/react-native-admob-native-ads#180]
Native video ad not pausing when navigating another page....when navigating to a page, true passed in the given prop pause...but ad not pausing...please help..

**Comment by dev007github** [comment]
Anyone know solution? Thanks in advance..

**Comment by dev007github** [comment]
Please help admin...Iam stuck here

**Comment by ammarahm-ed** [comment]
@dev007github which platform? iOS or Android?

**Comment by ammarahm-ed** [comment]
Does not work however it is implemented correctly. for now closing.
