### ISSUE TITLE
Use of undeclared identifier 'kDFPSimulatorID'

### ISSUE THREAD

**Issue by aidanshilling** [ammarahm-ed/react-native-admob-native-ads#181]
Anytime I try to build on iOS I get this error. I have installed everything based on docs and followed the instructions [here](https://developers.google.com/admob/ios/quick-start). The error appears on line 38 of RNAdmodNativeAdsManager.

**Comment by ammarahm-ed** [comment]
@aidanshilling Check example, you have to used fixed version of Google Mobile Ads library with is `7.xx`. The error is thrown because you have installed newer version which is not supported

**Comment by teamzz111** [comment]
@ammarahm-ed it's a big problem if you are using firebase :/

**Comment by ammarahm-ed** [comment]
@teamzz111 Fixed on master
