### ISSUE TITLE
[Android] Handler is sometimes null when removeCallbacks() calls

### ISSUE THREAD

**Issue by wjaykim** [ammarahm-ed/react-native-admob-native-ads#186]
Stack Trace:
`Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void android.os.Handler.removeCallbacks(java.lang.Runnable)' on a null object reference
com.ammarahmed.rnadmob.nativeads.RNAdmobNativeView.setNativeAd
com.ammarahmed.rnadmob.nativeads.RNAdmobNativeView$3.onNativeAdLoaded`

**Comment by ammarahm-ed** [comment]
Fixed.
