### ISSUE TITLE
Unknown type name 'DFPRequest'

### ISSUE THREAD

**Issue by avrutisavaliya-logistic** [ammarahm-ed/react-native-admob-native-ads#192]
![Screenshot 2021-07-19 at 12 29 32 PM](https://user-images.githubusercontent.com/68277221/126116647-6c865892-ba1f-4e3f-a68a-9df609b866e3.png)

Unknown type name 'DFPRequest' 
![Screenshot 2021-07-19 at 12 30 23 PM](https://user-images.githubusercontent.com/68277221/126116799-3f63b753-c4c1-4a95-bb45-c0a65d0e8c28.png)
![Screenshot 2021-07-19 at 12 31 10 PM](https://user-images.githubusercontent.com/68277221/126116830-a217f76f-ece4-4e8b-b5c5-51687e1b9da7.png)

can anyone help me to figure this out

**Comment by wjaykim** [comment]
Add `pod 'Google-Mobile-Ads-SDK' , '7.69.0'` to your podfile.
Support for Google Mobile Ads SDK Version 8.x is currently not supported in this package.
