### ISSUE TITLE
NSUserTrackingUsageDescription [IOS]

### ISSUE THREAD

**Issue by cristea2017** [ammarahm-ed/react-native-admob-native-ads#194]
after cloning this repo :  git clone https://github.com/ammarahm-ed/react-native-admob-native-ads.git
app is crashing at start.

To solve this you need to add NSUserTrackingUsageDescription key in your info.plist

**Comment by wjaykim** [comment]
Is this issue is related to the example app?

**Comment by cristea2017** [comment]
> Is this issue is related to the example app?

YES

**Comment by wjaykim** [comment]
Fixes are added to #195 and will be merged
