### ISSUE TITLE
No type or protocol named 'GADUnifiedNativeAdLoaderDelegate'. 

### ISSUE THREAD

**Issue by davidarnaub7** [ammarahm-ed/react-native-admob-native-ads#196]
I've followed the guideline step by step. However after installing pods, cleaning the build folder the project does not compile on Ios (I don't try to compile it in Android yet).

Any idea?

**Comment by cristea2017** [comment]
> I've followed the guideline step by step. However after installing pods, cleaning the build folder the project does not compile on Ios (I don't try to compile it in Android yet).
> 
> Any idea?

provide more details, show us a screenshot or smth that will help us  #_#

**Comment by wjaykim** [comment]
https://github.com/ammarahm-ed/react-native-admob-native-ads/issues/192#issuecomment-884187512
