### ISSUE TITLE
Is it possible to implement Native Ads with Class component instead of Hook?

### ISSUE THREAD

**Issue by munhyok** [ammarahm-ed/react-native-admob-native-ads#197]
First of all, I would like to thank @ammarahm-ed  for creating this library.
I am writing code with Class component, not Hook However, I am having a lot of trouble because there is no example written with a Class component. Can you show an example of implementing it with a Class component?

This is the code I've been writing so far.

<NativeAdView
                                  style={{
                                    width: "95%",
                                    alignSelf: "center",
                                    height: 412,
                                  }}

                                  //ref={} //HERE!!
                                  adUnitID={adUnitID} // TEST adUnitID
                                  onAdLoaded={this.onAdLoaded}
                                  onAdFailedToLoad={this.onAdFailedToLoad}
                                  //enableTestMode={true}
                                  
                                  delayAdLoading={1000}
                                > 

                           .....
                                </NativeAdView>

But I don't know how to do the Ref part here.

In the example
```
const AdView = () => {
  // Each NativeAdView component needs to have its own ref, you cannot use the same ref for multiple ads. 
  const nativeAdViewRef = useRef();

  React.useEffect(() => {
    nativeAdViewRef.current?.loadAd();
  }, []);

<NativeAdView
      ref={nativeAdViewRef}
      adUnitID="ca-app-pub-3940256099942544/2247696110"
    >
      <View>/* All other ad components */</View>
    </NativeAdView>
```

Is there any way to implement the same function as a Class component as in the example?

**Comment by ammarahm-ed** [comment]
> First of all, I would like to thank @ammarahm-ed  for creating this library.
> I am writing code with Class component, not Hook However, I am having a lot of trouble because there is no example written with a Class component. Can you show an example of implementing it with a Class component?
> 
> This is the code I've been writing so far.
> 
> 
> <NativeAdView
>                                   style={{
>                                     width: "95%",
>                                     alignSelf: "center",
>                                     height: 412,
>                                   }}
> 
>                                   //ref={} //HERE!!
>                                   adUnitID={adUnitID} // TEST adUnitID
>                                   onAdLoaded={this.onAdLoaded}
>                                   onAdFailedToLoad={this.onAdFailedToLoad}
>                                   //enableTestMode={true}
>                                   
>                                   delayAdLoading={1000}
>                                 > 
> 
>                            .....
>                                 </NativeAdView>
> 
> 
> But I don't know how to do the Ref part here.
> 
> In the example
> ```
> const AdView = () => {
>   // Each NativeAdView component needs to have its own ref, you cannot use the same ref for multiple ads. 
>   const nativeAdViewRef = useRef();
> 
>   React.useEffect(() => {
>     nativeAdViewRef.current?.loadAd();
>   }, []);
> 
> <NativeAdView
>       ref={nativeAdViewRef}
>       adUnitID="ca-app-pub-3940256099942544/2247696110"
>     >
>       <View>/* All other ad components */</View>
>     </NativeAdView>
> ```
> 
> 
> Is there any way to implement the same function as a Class component as in the example?

You can simply define ref in constructor.

```js
actionSheetRef= createRef();

Then later
ref={this.actionSheetRef}
```
