### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by AlexanderLevinQU** [ammarahm-ed/react-native-admob-native-ads#198]
I am failing to install react native ad mobs:

Has anyone faced this issue?

The following build commands failed:
	CompileC /Users/alexlevin/Library/Developer/Xcode/DerivedData/lokal-ezmbwaelnnmrtvdaznfohlxxqtqm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-admob-native-ads.build/Objects-normal/x86_64/RNAdmobNativeAdsManager.o /Users/alexlevin/dev/lokal/node_modules/react-native-admob-native-ads/ios/RNAdmobNativeAdsManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

I am getting this error when trying to start through Xcode:
Use of undeclared identifier 'kDFPSimulatorID'

But I am using the pods from the example:

  pod 'Google-Mobile-Ads-SDK', '8.7.0'
  pod 'GoogleMobileAdsMediationFacebook', '6.5.1.0'

**Comment by CapiPato** [comment]
Did you know how to fix it?, or any new on this?

**Comment by ammarahm-ed** [comment]
Fixed v0.5.0
