### ISSUE TITLE
Any plans to make it further customizable?

### ISSUE THREAD

**Issue by perrosnk** [ammarahm-ed/react-native-admob-native-ads#2]
First of all congratulations for this packagee. It was something that was really missing from the community and I believe there will be great interest in it.

I wanted to ask you if you have any plans to make it further customizable in order to be able to adapt the ad to the app design, something like [this](https://github.com/callstack/react-native-fbads#native-ads). 
By the way react-native-fbads doesn't seem to be maintenained

**Comment by ammarahm-ed** [comment]
Well what they are doing is pretty clever though. I think it can be achieved here too, all we need is to let the native side know what is the id of each view we will use. Initially I wanted something like that but couldn't grab the idea fully. So I will look into react-native-fbads code and see what we can take from there to make our native ads work as we want them to.

**Comment by perrosnk** [comment]
That would be awesome! I think a lot of people are waiting for a library to support native ads on react native.

**Comment by ammarahm-ed** [comment]
Well lets see what we can make of it. If it can be done, that would be great. Are the fbads customizable like normal react native views?

**Comment by perrosnk** [comment]
Yes, you basically receive [these](https://github.com/callstack/react-native-fbads#2-create-your-component) information and you construct your own views.
I don't know if it's because of this, but they have a huge blocker [issue](https://github.com/callstack/react-native-fbads/issues/172) and views are not logged.

**Comment by ammarahm-ed** [comment]
The issue seems to be more related to facebook ads so its more about testing and trying it out. Maybe AdMob SDK will not have such a problem.

**Comment by perrosnk** [comment]
Indeed you have done a great job. Thanks for that!
I believe that this library has great potential for the community, so I will be waiting for more updates in the future

**Comment by ammarahm-ed** [comment]
i have started working on this, lets see where it takes us

**Comment by ammarahm-ed** [comment]
Implementation on android is complete in the dev branch. I will work on the ios side now. Hope to have the new version uploaded by monday. Things look promising.

**Comment by ammarahm-ed** [comment]
iOS implementation is complete too. Going to do some tests and rewrite the docs.

**Comment by ammarahm-ed** [comment]
Okay, its ready now but I need someone to test it. So if you can, clone this repo. switch to dev branch. go to example folder and run the project on ios an android. If you face an issue report here.

**Comment by ammarahm-ed** [comment]
new version released. this issue is closing.

**Comment by perrosnk** [comment]
Just wanted to say thank you @ammarahm-ed. I have tested and used the library in production and it works perfectly! Well done!
