### ISSUE TITLE
Problem with test banner add initialization.

### ISSUE THREAD

**Issue by dolb** [ammarahm-ed/react-native-admob-native-ads#20]
Hello,

I wanted to give your module a try starting with a simple banner in the application. I wanted to add a simple banner to my RN app using test banner adUnitId, which according to AdMob documentation is ca-app-pub-3940256099942544/6300978111 (https://developers.google.com/admob/android/test-ads).

The problem is, that nothing was displayed, to I added onAdFailedToLoad callback with a simple logger, and what I have is:

```{"error": {"message": "Internal error, an invalid response was received from the ad server."}}```

Any idea what seems to be the problem? My module version is latest 0.2.6.

**Comment by ammarahm-ed** [comment]
@dolb You need to used **Native-Advanced Ad Unit Ids** only. These are not banner ads, these are Native Advanced ads where you can create the ads as you would like.

**Comment by dolb** [comment]
Ok, thanks for the clarification on this part :) Please consider this issue closed then :+1:
