### ISSUE TITLE
Pod install: Error installing GoogleMobileAdsMediationFacebook - curl: (22) The requested URL returned error: 403 Forbidden

### ISSUE THREAD

**Issue by GuillemetS** [ammarahm-ed/react-native-admob-native-ads#204]
Hello,

I try to add your library in my project but the pod install script don't working

I re-try in another empty project (in case there is a conflict with another package) but I have the same error

![Capture d’écran 2021-08-16 à 15 14 49](https://user-images.githubusercontent.com/6207052/129570656-bcf34407-f68c-459b-8dfb-67659d7336b7.png)

Do you have an idea ?

**Comment by ammarahm-ed** [comment]
Fixed v0.5.0
