### ISSUE TITLE
Use .png images

### ISSUE THREAD

**Issue by LayThankTon** [ammarahm-ed/react-native-admob-native-ads#207]
First of all, your project is awesome, thanks a lot!
i would like to ask if it is possible to use star.png images instead of react-native-vector-icons library. I think using the library just to use a few characters is a waste of resources. Do you think it's reasonable? Icons in .svg format can be provided at https://icon-sets.iconify.design/?query=star and I can assist in converting .svg to .png to your desired size. What's your opinion?

**Comment by ammarahm-ed** [comment]
The only reasonable modification to the current StarView would be to be able to provide your own <Icon/> Component which will be used directly instead of using icons. However I think most apps will be using at least one type of icon from react-native-vector-icon library.

**Comment by LayThankTon** [comment]
Yes, a good reason is to use your Component directly and independently.
In my case, I used a set of several dozen icons in .png format, and maintaining or modifying them was intuitive and easy.
it's just an option, so if you plan to make this change in the future, let me know.
thanks so much!

**Comment by ammarahm-ed** [comment]
I will add support for it in future. For now I am closing this issue.
