### ISSUE TITLE
Component 'RNGADNativeView' re-reigistered bubbling event 'topSizeChange' as a direct event.

### ISSUE THREAD

**Issue by haresh4d** [ammarahm-ed/react-native-admob-native-ads#209]
I am getting this error since tomorrow. Please help.
![Simulator Screen Shot - iPhone 12 mini - 2021-09-03 at 09 54 18](https://user-images.githubusercontent.com/12708202/131950489-6e39121f-4998-4fe9-8cd4-238d130841d6.png)

**Comment by haresh4d** [comment]
Got the solution. I was using react-native-admob-next library which is also registering the same events as bubbliing event so it caused an issue.

**Comment by ammarahm-ed** [comment]
I will fix this in the next version

**Comment by kookkkookk** [comment]
I would like to ask, is there a solution after this?
I have the same problem, but the AdMob library I use [@invertase/react-native-google-ads](https://github.com/invertase/react-native-google-ads)
![simulator_screenshot_B1788456-52AD-40C5-BB9A-E245C8AA35B2](https://user-images.githubusercontent.com/16489567/147441218-fe053fba-4a07-4333-a74c-0d41c287b170.png)

**Comment by RNvivekvision** [comment]
> I would like to ask, is there a solution after this? I have the same problem, but the AdMob library I use [@invertase/react-native-google-ads](https://github.com/invertase/react-native-google-ads) & AdManager library [react-native-ad-manager](https://www.npmjs.com/package/react-native-ad-manager) ![simulator_screenshot_B1788456-52AD-40C5-BB9A-E245C8AA35B2](https://user-images.githubusercontent.com/16489567/147441218-fe053fba-4a07-4333-a74c-0d41c287b170.png)

i am getting the same problem. i have integrated FBSDK, after that i got error like "Component 'RNGADNativeView' re-registered bubbling event 'topAdLoaded' as a direct event" 

Could you please share your package.json file here?
