### ISSUE TITLE
[Question]Portraits or Landscape ads

### ISSUE THREAD

**Issue by paddy57** [ammarahm-ed/react-native-admob-native-ads#21]
Is there any way to know ads are portraits or landscape ads?
I have looked on official docs from AdMob for Native ads haven't found anything related to it.
Reason - I want to set the height of mediaview component according to landscape/portrait ads

**Comment by ammarahm-ed** [comment]
I think maybe we can know the width and height of the image on android. on iOS I am not sure if there is any such information. Since the MediaView also renders video and we cannot know the exact size of the video, its dimensions, it might not be possible but I will look into to, maybe we can get that info from the video also.

**Comment by ammarahm-ed** [comment]
Okay, I checked, we can get to know the aspectRatio of the Media that is loaded with which we can set the exact width and height of the MediaView, i will add this in the next version i hope

**Comment by paddy57** [comment]
You mean to check type of child mediaView , if its imageView then to get its height, Somethign like this 
  ```
mediaView.setOnHierarchyChangeListener(new ViewGroup.OnHierarchyChangeListener() {
            @Override
            public void onChildViewAdded(View parent, View child) {
                if (child instanceof ImageView) {
                    ImageView imageView = (ImageView) child;
                    DisplayMetrics displayMetrics = new DisplayMetrics();
                    WindowManager windowManager = (WindowManager) getContext().getSystemService(Context.WINDOW_SERVICE);
                    if (windowManager != null) {
                        windowManager.getDefaultDisplay().getMetrics(displayMetrics);
                    }
                    int imageHeight = imageView.getDrawable().getIntrinsicHeight();
                    Log.d("videoAD", String.valueOf(imageHeight));
                }
            }
            @Override
            public void onChildViewRemoved(View parent, View child) {
            }
        });
```

**Comment by paddy57** [comment]
I think it can be done like this

Inside RNNativeWrapper.java

after ad loads, we can access image height and send it as param 
so we can get them in callback onUnifiedNativeAdLoaded
` args.putInt("imageHeight", nativeAd.getMediaContent().getMainImage().getIntrinsicHeight());
`

Console log
```
2020-04-29 21:50:40. D/ReactNativeJS: 'videoAD load', { icon: 'https://lh3.googleusercontent.com/proxy/vbMqbwgZTdo4lrHTh9AEEEtBq0au14B1JuxrHIsf7h6JGwcJt14CORcACLvxFe1CPoCZSRiPeRzGLpWMnRcy3FYwFRShkOF30hZovitYDLk2fREoRKM7auk=w600-h600-n-e7-rw-v1',
      images: [ 'https://lh3.googleusercontent.com/proxy/a6MAbCYJ0a9op9RS2AeGChJ_hMdFOUsi1u1F-KYgi9GG_aPST3pCFz9BcThBKoebNmcE9xfqOQLlVt0A-Vtt5q5VXT7G-PpG48TxUfbOE1tJyipL5mLnh8D-=w1081-h565-n-e7-rw-v1' ],
      imageHeight: 565,
      price: null,
      video: false,
      callToAction: 'Visit Site',
      advertiser: 'tournoy-gmbh.leadsy.app',
      tagline: 'Our expert team provides amazing home remodeling',
      headline: 'Test Ad : Talk to our experts' }

```
what say ?

**Comment by ammarahm-ed** [comment]
I think this would be unnecessary, all we need to do is know the aspectRatio of the mediaContent of the nativeAd and send it to React Native. then use that to set the width and height of MediaView because it will work for both image and video. The above method is good but sometimes the MediaView will load a video add, then this will not work.

**Comment by paddy57** [comment]
Yeah, it will not work if we get video, do let me know if you find solution to get aspectRatio of mediaContent and send to RN ✌🏻

**Comment by ammarahm-ed** [comment]
@paddy57 I found the solution, I will add it in the next release

**Comment by ammarahm-ed** [comment]
I have added this, check the new version.
