### ISSUE TITLE
How to setup facebook and other mediation networks?

### ISSUE THREAD

**Issue by iLevye** [ammarahm-ed/react-native-admob-native-ads#211]
Is there any document that I can follow for the Facebook Mediation setup?

Do I need to add any pod for ios or dependency for android?

Do I need to add anything like Facebook business ID to Info.plist or AndroidManifest.xml ?

There are a lot of documents, versions, changes about this topic and it is really confusing thing for who implements this for the first time.

**Comment by ammarahm-ed** [comment]
Setup mediation on Admob Account for Facecbook Ads. Follow the complete guide. Ads will show up from facebook.

**Comment by iLevye** [comment]
There are no additional steps for Facebook ads.
