### ISSUE TITLE
App is crashing on android RN 0.65.1

### ISSUE THREAD

**Issue by SergiOnGit** [ammarahm-ed/react-native-admob-native-ads#217]
App is building but crashes as soon as I open it.

```
"react-native": "0.65.1",
"react-native-admob-native-ads": "0.5.0"
```
**Firebase logged error:**
```bash
Fatal Exception: java.lang.VerifyError
Verifier rejected class expo.modules.ads.admob.PublisherBannerViewManager: android.view.View expo.modules.ads.admob.PublisherBannerViewManager.createViewInstance(android.content.Context) failed to verify: android.view.View expo.modules.ads.admob.PublisherBannerViewManager.createViewInstance(android.content.Context): [0x4] can't resolve returned type 'Reference: android.view.View' or 'Unresolved Reference: expo.modules.ads.admob.PublisherBannerView' (declaration of 'expo.modules.ads.admob.PublisherBannerViewManager' appears in /data/app/~~JWJ1tV7nGNd2G-N6HEhmkg==/app.perfectposture-cClImmciKfRoOzkiYvFhQg==/base.apk!classes2.dex)
```

I guess it has problem with expo ads, which I am using in this project.
react-native-admob-native-ads 0.4.1 version doesn't have this problem. It only happens with 0.5.0

Can anyone help?

**Comment by ammarahm-ed** [comment]
The error seems to be coming from expo ads library. I don't see any mention of this library or any of it's classes etc the error log.

**Comment by ammarahm-ed** [comment]
> The error seems to be coming from expo ads library. I don't see any mention of this library or any of it's classes etc the error log. 

The only reason i understand for this would be that expo ads are using older version of google admob. 

The solution is to remove expo ads and use `react-native-admob/admob` library.

**Comment by SergiOnGit** [comment]
@ammarahm-ed You are right. I removed expo ads and now it works.
