### ISSUE TITLE
not working with expo

### ISSUE THREAD

**Issue by beingtarkeshwar** [ammarahm-ed/react-native-admob-native-ads#22]
hey,
I have been looking for such a library for long time.
so, first of all thanks for your great work.

issue is this library is not working with expo.
will you explain how can we use it in expo app.

**Comment by ammarahm-ed** [comment]
We have added no support for expo. Read the expo docs to know how to eject your project to use Native Modules. Expo does not allow usage of Native Modules Unless you have ejected your project.
