### ISSUE TITLE
expo bearer with native ads

### ISSUE THREAD

**Issue by devGuerra** [ammarahm-ed/react-native-admob-native-ads#222]
Hello, 

this version has support with expo bearer ?

i getting this error, try run link but not works

![image](https://user-images.githubusercontent.com/6579736/137997540-60b97c75-9b3a-4129-b6ae-78ae08cc1579.png)

**Comment by luigimannoni** [comment]
Same issue with Expo 43, does not work either with bare workflow or as a ejected project.
There's not an explicit way to eject the project after Expo 38 (or 40) but you can do it forcefully by using `expo eject` but the guys at Expo don't recommend it.

Also `react-native link` won't help...

I've recreated a quick repo showing the issue, checkout `master` branch for the Expo Bare Workflow version, checkout `ejected` branch for the Expo-ejected version.

https://github.com/luigimannoni/expo-bug-rn-native-admob-ads

**Comment by ammarahm-ed** [comment]
@luigimannoni I will investigate this soon.
