### ISSUE TITLE
Typescript issues

### ISSUE THREAD

**Issue by bobbyjcolley** [ammarahm-ed/react-native-admob-native-ads#224]
Hi RNAMA!

I've noticed an issue where the typescript typings for the NativeMediaView component callbacks are slightly off.

https://github.com/ammarahm-ed/react-native-admob-native-ads/blob/master/index.d.ts#L434-L438

I didn't see anything which leads me to think that these should be arrow functions which do not return a value. This would be the fix:

```typescript
onVideoProgress?: (progress: {
      duration: string;
      currentTime: string;
    }) => void;
onVideoMute?: (muted: boolean) => void;
```

**Comment by ammarahm-ed** [comment]
Hey thanks for pointing out and sending a PR. There are some ts issues, I think they can be resolved. Rewriting in typescript isn't an option at the moment.

You can set both to not required in index.d.ts file as they are not needed.
