### ISSUE TITLE
Cannot find interface declaration for 'GADNativeAdView', superclass of 'RNGADNativeView'; did you mean 'GADNativeAd'?

### ISSUE THREAD

**Issue by anhdo9797** [ammarahm-ed/react-native-admob-native-ads#229]
I'm getting this error:

![Screen Shot 2021-11-11 at 11 05 57](https://user-images.githubusercontent.com/60549336/141235189-0b4ee905-0d33-4a76-92b7-be9d80b4c440.png)

My dependencies: {
 "react-native": "0.64.2",
 "@react-native-firebase/admob": "^11.5.0",
 "@react-native-firebase/app": "^11.5.0",
 "react-native-admob-native-ads": "^0.5.0",
}

please help me !

**Comment by ammarahm-ed** [comment]
Does not work alongside `@react-native-firebase/admob` because it is outdated. Use something else for other ad formats. Maybe the library i have put in readme.

**Comment by szymonzalarski98** [comment]
@anhdo9797 Hi, did you resolve the issue?
