### ISSUE TITLE
[Bug] Few Ads are not clickable in List

### ISSUE THREAD

**Issue by sufyan297** [ammarahm-ed/react-native-admob-native-ads#23]
Hello @ammarahm-ed ,

I am displaying Ads in List, now all ads are displaying correctly. But the problem is few ads are not clickable and it is acting weirdly like first Ad displayed is not clickable then second Ad is clickable then 3rd is not clickable and so on idk what's happening

I have made an separate Repository, Please have a look into it.
https://github.com/sufyan297/react-native-test-native-ad

![Screenshot_20200503-132003](https://user-images.githubusercontent.com/836773/80908978-f4f04880-8d41-11ea-85cf-861bc0d2256f.jpg)

**Comment by ammarahm-ed** [comment]
@sufyan297 I will test this and see. However there should only one ad in the list at one time. You should add the ads to the list dynamically as the user scrolls.

**Comment by ammarahm-ed** [comment]
I am fixing this issue hopefully

**Comment by ammarahm-ed** [comment]
This has been fixed in 0.2.8, please update and open the issue if you face the problem.

**Comment by sufyan297** [comment]
@ammarahm-ed It affects the performance, the app becomes laggy now.

v0.2.8
https://photos.app.goo.gl/KVHBzKFP9jujXXdb7

v0.2.2
https://photos.app.goo.gl/PdcahPHZoyDsiAQ48

**Comment by ammarahm-ed** [comment]
@sufyan297 The implementation has changed as compared to v0.2.2 earlier. The issue with performance is noticeable and it has been reported before. It occurs when more than one ad is rendered on the same screen. The only solution for this at the moment is to make sure there is only one ad rendered in your list at one time, like updating the list dynamically to show the ad where the user stops. I am still looking into this and I have not found a solution yet to this. Even in your test example, the app was running very slow on 0.2.7. 

I think it can be done easily if you know the scrollOffset, you can know at what index the user is currently, then update the list with an ad item there.

**Comment by ammarahm-ed** [comment]
@sufyan297 I have found the culprit, will update to 0.2.9 soon with fix for this rendering issue

**Comment by sufyan297** [comment]
@ammarahm-ed Thank you so much man, You Rock 👍

**Comment by ammarahm-ed** [comment]
@sufyan297 It has been fixed, also you don't need to use `delayAdLoading` prop anymore I think.
