### ISSUE TITLE
IOS build failed in version 0.6.0 

### ISSUE THREAD

**Issue by FayyazAliKhan1** [ammarahm-ed/react-native-admob-native-ads#231]
react-native-admob-native-ads IOS build issue on version 0.6.0 working fine in android Thanks for it, but this version fails the build on IOS, 
"react": "17.0.1",
 "react-native": "0.64.2"
CocoaPods installed the 0.6.0 successfully
<img width="573" alt="issue" src="https://user-images.githubusercontent.com/46970238/141454567-cbf5a36f-9800-4d0b-9831-e0dee56bae6f.png">
,
Thanks 😊

**Comment by Ali72** [comment]
I sent a pull request for this bug

> react-native-admob-native-ads IOS build issue on version 0.6.0 working fine in android Thanks for it, but this version fails the build on IOS, "react": "17.0.1", "react-native": "0.64.2" CocoaPods installed the 0.6.0 successfully <img alt="issue" width="573" src="https://user-images.githubusercontent.com/46970238/141454567-cbf5a36f-9800-4d0b-9831-e0dee56bae6f.png"> , Thanks 😊

**Comment by ammarahm-ed** [comment]
Thanks for the fix @Ali72 I am closing this.

**Comment by zoobibackups** [comment]
> 6.9.0.1

after donwgrading I have these issues 

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADAdLoader


Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADMultipleAdsAdLoaderOptions


Showing Recent Messages
Undefined symbol: _OBJC_METACLASS_$_GADNativeAdView



Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADCustomEventExtras



Showing Recent Messages
Undefined symbol: _GADSimulatorID



Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADCustomEventExtras

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADNativeAdMediaAdLoaderOptions

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADNativeAdViewAdOptions
