### ISSUE TITLE
Android build fails on gradle 7.0+

### ISSUE THREAD

**Issue by wjaykim** [ammarahm-ed/react-native-admob-native-ads#235]
Android app build fails when project's gradle version is >= 7.0.

**Comment by ammarahm-ed** [comment]
@wjaykim Did you investigate why that is happening?

**Comment by wjaykim** [comment]
https://github.com/ammarahm-ed/react-native-admob-native-ads/blob/d4309d2e350e6606a8a6cc8dd5b80d4deaf54713/android/build.gradle#L30

Above line gives error.
And after applying [this change](https://stackoverflow.com/a/69100971), another error occurs, maybe related to line after [this line](https://github.com/ammarahm-ed/react-native-admob-native-ads/blob/d4309d2e350e6606a8a6cc8dd5b80d4deaf54713/android/build.gradle#L72).
Are those code necessary? I have no knowledge about gradle, but I haven't see those codes in other react native native modules.

**Comment by ammarahm-ed** [comment]
@wjaykim I have fixed this on master. You can test and let me know.

**Comment by wjaykim** [comment]
It works.
