### ISSUE TITLE
Error on Mac m1 chip

### ISSUE THREAD

**Issue by SergiOnGit** [ammarahm-ed/react-native-admob-native-ads#237]
Running Xcode throws error

`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GADFBNetworkExtras", referenced from:
      objc-class-ref in libreact-native-admob-native-ads.a(RNGADNativeView.o)
ld: symbol(s) not found for architecture arm64`

Can anyone help?

**Comment by hernanmateo** [comment]
I'm getting this error after upgrading to react 0.66.4 to M1 Max chip.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/1542900/146182622-ca2d1405-adf6-4964-9cf6-e8310562b52f.png">

**Comment by szymonzalarski98** [comment]
> I'm getting this error after upgrading to react 0.66.4 with a new M1 Max chip.
> 
> <img alt="image" width="439" src="https://user-images.githubusercontent.com/1542900/146182622-ca2d1405-adf6-4964-9cf6-e8310562b52f.png">
> 
> RNAdmobNativeAdsManager.m
> 
> <img alt="image" width="705" src="https://user-images.githubusercontent.com/1542900/146182876-5af28602-f5ee-4b76-b02b-7a149b8228d2.png">

I have the same issue, have you resolved it?

**Comment by ammarahm-ed** [comment]
@szymonzalarski98 Can you try the master branch and see if you get the same issue?

**Comment by ammarahm-ed** [comment]
Maybe this issue is because you are using older version go Google Mobile Ads Sdk Library. Try running `pod install --repo-update` which might fix this

**Comment by hernanmateo** [comment]
Hello, the constant kGAMSimulatorID was deprecated in the latest version of Google Mobile Ads SDK (v8.13.0)

https://developers.google.com/admob/ios/rel-notes

**Comment by ammarahm-ed** [comment]
@hernanmateo you can use the next version of library by installing the master branch which uses latest version of mobile ads sdk and ad preloading. However note that it uses ad repositories to load ads and it is not documented properly. However you can read the index.d.ts file to get an idea.

**Comment by SergiOnGit** [comment]
@ammarahm-ed How can i install version from master branch? Yarn opens version selection where latest is 0.5.0. This error still exists and needs to be fixed.

**Comment by ammarahm-ed** [comment]
@SergiOnGit 

```
yarn add https://github.com/ammarahm-ed/react-native-admob-native-ads.git
```

**Comment by ammarahm-ed** [comment]
@SergiOnGit Just updating the lib won't work. You will need to install latest version o "Google Mobile Ads Sdk" in pods. Please refer to the docs. Then run `pod installl --repo-update`.

**Comment by SergiOnGit** [comment]
@ammarahm-ed Sure I have updated pods. I was checking with simulator. Now i have tested it with real device and have no problem. So looks like it's an issue with simulators.

**Comment by SergiOnGit** [comment]
It works with real device, so I'm closing.

**Comment by rogerkerse** [comment]
Premature closing. I am also trying to build onto simulator and it is failing with same error. Pod repo update and going for master branch doesn't help

**Comment by haresh4d** [comment]
> https://github.com/ammarahm-ed/react-native-admob-native-ads.git

I have used master branch and then pod install --repo-update but still having the same issue.
