### ISSUE TITLE
Documentation issue for iOS installation

### ISSUE THREAD

**Issue by jamesxabregas** [ammarahm-ed/react-native-admob-native-ads#240]
Hi, I just wanted to point out an issue in the documentation on `Getting Started > Installation`.

Under the **iOS Setup Guide** heading it says that I should follow the [Google Mobile Ads SDK](https://developers.google.com/admob/ios/quick-start#import_the_mobile_ads_sdk) installation guide. 
When I click that link and follow the guide the first item it covers is the pods that I need to add. 
It says:

```
pod 'Google-Mobile-Ads-SDK'
```

So I added this and followed the rest of the guide.

Then when I tried to build, I get a build time error:

```
ld: framework not found FacebookAdapter
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Your migration guide gave me the answer here. I needed to also add `pod 'GoogleMobileAdsMediationFacebook'` to my pod file, but this wasn't immediatley obvious because I am first time installer and wasn't migrating from a previous version. I spent a while trying to figure out what was going on and nearly gave up on this library before I came across this. I'd suggest just adding the following instructions to the **iOS Setup** part of the **Installation** page just to make things easier for other first time users.

```
Add these to your Podfile.

pod 'Google-Mobile-Ads-SDK'
pod 'GoogleMobileAdsMediationFacebook'
````

**Comment by ammarahm-ed** [comment]
@jamesxabregas In the next version of this library, adding facebook mediation is optional. Maybe that's why it is missing from docs but you are right. This should be mentioned.

**Comment by ammarahm-ed** [comment]
Added this to docs. Closing

**Comment by kyle-belle** [comment]
> Added this to docs. Closing

i think i see what you mean but isn't it a little weird to have it in the migration guide. For new users of the lib they may not check this page as they aren't migrating and it seems like an optional step only if upgrading from previous versions

**Comment by zoobibackups** [comment]
> 6.9.0.1

after donwgrading I have these issues 

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADAdLoader


Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADMultipleAdsAdLoaderOptions


Showing Recent Messages
Undefined symbol: _OBJC_METACLASS_$_GADNativeAdView



Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADCustomEventExtras



Showing Recent Messages
Undefined symbol: _GADSimulatorID



Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADCustomEventExtras

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADNativeAdMediaAdLoaderOptions

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADNativeAdViewAdOptions
