### ISSUE TITLE
Facebook Adapter not found

### ISSUE THREAD

**Issue by faustoct** [ammarahm-ed/react-native-admob-native-ads#242]
Ld /Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/viby.app/viby normal (in target 'viby' from project 'viby')
    cd /Users/fausto/Projects/coding/viby/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios11.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/Base64 -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/BoringSSL-GRPC -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/CodePush -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/DoubleConversion -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/EXAdsFacebook -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/EXApplication -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/EXConstants -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/EXErrorRecovery -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/EXFont -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/EXImageLoader -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/EXImagePicker -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/EXKeepAwake -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/EXLinearGradient -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/EXPermissions -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/ExpoModulesCore -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/FBReactNativeSpec -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/FBSDKCoreKit -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/FirebaseABTesting -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/FirebaseAuth -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/FirebaseCore -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/FirebaseCoreDiagnostics -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/FirebaseDatabase -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/FirebaseDynamicLinks -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/FirebaseFirestore -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/FirebaseFunctions -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/FirebaseInAppMessaging -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/FirebaseInstallations -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/FirebaseInstanceID -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/FirebaseMessaging -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/FirebaseRemoteConfig -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/FirebaseStorage -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/Folly -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/GTMSessionFetcher -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/GoogleDataTransport -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/GoogleUtilities -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/JWT -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/PromisesObjC -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RCTTypeSafety -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RNAdMob -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RNCAsyncStorage -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RNCMaskedView -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RNFBAnalytics -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RNFBApp -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RNFBAuth -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RNFBDatabase -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RNFBDynamicLinks -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RNFBFirestore -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RNFBFunctions -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RNFBInAppMessaging -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RNFBMessaging -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RNFBRemoteConfig -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RNFBStorage -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RNGestureHandler -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RNReanimated -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RNScreens -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/RNShare -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/React-Core -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/React-CoreModules -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/React-RCTAnimation -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/React-RCTBlob -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/React-RCTImage -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/React-RCTLinking -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/React-RCTNetwork -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/React-RCTSettings -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/React-RCTText -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/React-RCTVibration -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/React-cxxreact -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/React-jsi -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/React-jsiexecutor -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/React-jsinspector -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/ReactCommon -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/SSZipArchive -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/Stripe -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/StripeCore -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/StripeUICore -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/UMAppLoader -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/Yoga -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/abseil -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/appcenter-analytics -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/appcenter-core -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/appcenter-crashes -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/gRPC-C++ -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/gRPC-Core -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/glog -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/leveldb-library -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/nanopb -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/react-native-admob-native-ads -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/react-native-geolocation -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/react-native-gps-state -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/react-native-netinfo -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/react-native-safe-area-context -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/react-native-slider -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/react-native-view-shot -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/react-native-webview -L/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/stripe-react-native -F/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos -F/Users/fausto/Projects/coding/viby/ios/Pods/../../node_modules/@unimodules/core/ios -F/Users/fausto/Projects/coding/viby/ios/Pods/../../node_modules/@unimodules/react-native-adapter/ios -F/Users/fausto/Projects/coding/viby/ios/Pods/../../node_modules/expo-contacts/ios -F/Users/fausto/Projects/coding/viby/ios/Pods/../../node_modules/expo-file-system/ios -F/Users/fausto/Projects/coding/viby/ios/Pods/../../node_modules/expo-location/ios -F/Users/fausto/Projects/coding/viby/ios/Pods/../../node_modules/expo-notifications/ios -F/Users/fausto/Projects/coding/viby/ios/Pods/../../node_modules/expo-splash-screen/ios -F/Users/fausto/Projects/coding/viby/ios/Pods/../../node_modules/expo-structured-headers/ios -F/Users/fausto/Projects/coding/viby/ios/Pods/../../node_modules/expo-updates/ios -F/Users/fausto/Projects/coding/viby/ios/Pods/AppCenter/AppCenter-SDK-Apple -F/Users/fausto/Projects/coding/viby/ios/Pods/AppCenterReactNativeShared/AppCenterReactNativeShared -F/Users/fausto/Projects/coding/viby/ios/Pods/FBAudienceNetwork/Static -F/Users/fausto/Projects/coding/viby/ios/Pods/FirebaseAnalytics/Frameworks -F/Users/fausto/Projects/coding/viby/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current -F/Users/fausto/Projects/coding/viby/ios/Pods/GoogleAppMeasurement/Frameworks -F/Users/fausto/Projects/coding/viby/ios/Pods/GoogleUserMessagingPlatform/Frameworks/Release -F/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/AppCenter -F/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/AppCenterAnalytics -F/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/AppCenterCrashes -F/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/AppCenterReactNativeShared -F/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/EXContacts -F/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/EXFileSystem -F/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/EXLocation -F/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/EXNotifications -F/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/EXSplashScreen -F/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/EXStructuredHeaders -F/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/EXUpdates -F/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/FirebaseAnalytics -F/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurement -F/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/GoogleMobileAds -F/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/UMCore -F/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/UMReactNativeAdapter -F/Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/UserMessagingPlatform -filelist /Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Intermediates.noindex/viby.build/Debug-iphoneos/viby.build/Objects-normal/arm64/viby.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Intermediates.noindex/viby.build/Debug-iphoneos/viby.build/Objects-normal/arm64/viby_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Intermediates.noindex/viby.build/Debug-iphoneos/viby.build/Objects-normal/arm64/viby.swiftmodule -ObjC -lBase64 -lBoringSSL-GRPC -lCodePush -lDoubleConversion -lEXAdsFacebook -lEXApplication -lEXConstants -lEXErrorRecovery -lEXFont -lEXImageLoader -lEXImagePicker -lEXKeepAwake -lEXLinearGradient -lEXPermissions -lExpoModulesCore -lFBReactNativeSpec -lFBSDKCoreKit -lFirebaseABTesting -lFirebaseAuth -lFirebaseCore -lFirebaseCoreDiagnostics -lFirebaseDatabase -lFirebaseDynamicLinks -lFirebaseFirestore -lFirebaseFunctions -lFirebaseInAppMessaging -lFirebaseInstallations -lFirebaseInstanceID -lFirebaseMessaging -lFirebaseRemoteConfig -lFirebaseStorage -lFolly -lGTMSessionFetcher -lGoogleDataTransport -lGoogleUtilities -lJWT -lPromisesObjC -lRCTTypeSafety -lRNAdMob -lRNCAsyncStorage -lRNCMaskedView -lRNFBAnalytics -lRNFBApp -lRNFBAuth -lRNFBDatabase -lRNFBDynamicLinks -lRNFBFirestore -lRNFBFunctions -lRNFBInAppMessaging -lRNFBMessaging -lRNFBRemoteConfig -lRNFBStorage -lRNGestureHandler -lRNReanimated -lRNScreens -lRNShare -lReact-Core -lReact-CoreModules -lReact-RCTAnimation -lReact-RCTBlob -lReact-RCTImage -lReact-RCTLinking -lReact-RCTNetwork -lReact-RCTSettings -lReact-RCTText -lReact-RCTVibration -lReact-cxxreact -lReact-jsi -lReact-jsiexecutor -lReact-jsinspector -lReactCommon -lSSZipArchive -lStripe -lStripeCore -lStripeUICore -lUMAppLoader -lYoga -labseil -lappcenter-analytics -lappcenter-core -lappcenter-crashes -lc++ -lgRPC-C++ -lgRPC-Core -lglog -liconv -licucore -lleveldb-library -lnanopb -lreact-native-admob-native-ads -lreact-native-geolocation -lreact-native-gps-state -lreact-native-netinfo -lreact-native-safe-area-context -lreact-native-slider -lreact-native-view-shot -lreact-native-webview -lsqlite3 -lstdc++ -lstripe-react-native -lxml2 -lz -framework AVFoundation -framework AppCenter -framework AppCenterAnalytics -framework AppCenterCrashes -framework AppCenterReactNativeShared -framework AudioToolbox -framework CFNetwork -framework Contacts -framework CoreGraphics -framework CoreImage -framework CoreLocation -framework CoreMedia -framework CoreTelephony -framework CoreVideo -framework EXContacts -framework EXFileSystem -framework EXLocation -framework EXNotifications -framework EXSplashScreen -framework EXStructuredHeaders -framework EXUpdates -framework FBAudienceNetwork -framework FirebaseAnalytics -framework Foundation -framework GoogleAppMeasurement -framework GoogleMobileAds -framework JavaScriptCore -framework MediaPlayer -framework MessageUI -framework MobileCoreServices -framework PassKit -framework QuartzCore -framework SafariServices -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -framework UMCore -framework UMReactNativeAdapter -framework UserMessagingPlatform -framework WebKit -weak_framework Accelerate -weak_framework Accounts -weak_framework AdSupport -weak_framework AudioToolbox -weak_framework CFNetwork -weak_framework CoreGraphics -weak_framework CoreMotion -weak_framework CoreTelephony -weak_framework FacebookAdapter -weak_framework Foundation -weak_framework GoogleMobileAds -weak_framework JavaScriptCore -weak_framework LocalAuthentication -weak_framework QuartzCore -weak_framework SafariServices -weak_framework Security -weak_framework Social -weak_framework StoreKit -weak_framework SwiftUI -weak_framework SystemConfiguration -weak_framework UIKit -weak_framework UserNotifications -weak_framework VideoToolbox -weak_framework WebKit -ObjC -lc++ -lPods-viby -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Intermediates.noindex/viby.build/Debug-iphoneos/viby.build/Objects-normal/arm64/viby_dependency_info.dat -o /Users/fausto/Library/Developer/Xcode/DerivedData/viby-gdnnyojalqxcaychaixnbedeqkrc/Build/Products/Debug-iphoneos/viby.app/viby

ld: framework not found FacebookAdapter
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Does anyone know how to fix it ? Getting this message trying to build on Xcode

**Comment by kyle-belle** [comment]
Did you ever fix this?

**Comment by faustoct** [comment]
> Did you ever fix this?

Of course sure I fucking did. `expo install expo-ads-facebook` then `pod install`. Be sure to not have a lot admob libs. I had to remove expo-ads-admob + @react-native-firebase/admob. You need only `react-native-admob-native-ads` + `react-native-admob`. 

It is running perfectly on Android and iOS. 

Good Luck

**Comment by kyle-belle** [comment]
> > Did you ever fix this?
> 
> Of course sure I fucking did. `expo install expo-ads-facebook` then `pod install`. Be sure to not have a lot admob libs. I had to remove expo-ads-admob + @react-native-firebase/admob. You need only `react-native-admob-native-ads` + `react-native-admob`.
> 
> It is running perfectly on Android and iOS.
> 
> Good Luck

lol
i ended up fixing it:
add to podfile:

pod 'GoogleMobileAdsMediationFacebook'

they have it on the migration guide in the documentation but of course not everyone will be migrating

**Comment by faustoct** [comment]
I had to do it also. 

````
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'viby' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'GoogleMobileAdsMediationFacebook'

  # Uncomment the code below to enable Flipper.
  #
  # You should not install Flipper in CI environments when creating release
  # builds, this will lead to significantly slower build times.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work.
  #
  #  use_flipper!
  #  post_install do |installer|
  #    flipper_post_install(installer)
  #  end
end
````

**Comment by adamsadiq7** [comment]
For me using GoogleMobileAdsMediationFacebook still doesn't work

**Comment by davidmarcos98** [comment]
@adamsadiq7 I was having this problem too now. It's because the framework in `GoogleMobileAdsMediationFacebook` is now called 
 `MetaAdapter` instead of `FacebookAdapter`.
Fixing  `GoogleMobileAdsMediationFacebook` to last version with `FacebookAdapter` solved it for me. 

`pod 'GoogleMobileAdsMediationFacebook',  '6.11.0.0'`

**Comment by adamsadiq7** [comment]
No wonder! that makes so much sense, thank you very much David.

**Comment by zoobibackups** [comment]
still have issue. on react-native version 69.4

**Comment by zoobibackups** [comment]
it would be better if you share the  compatible versions of both sdks
pod 'GoogleMobileAdsMediationFacebook', '6.11.0.0'
  pod 'Google-Mobile-Ads-SDK'

**Comment by DavidAPears** [comment]
Some useful info here: https://cocoapods.org/pods/GoogleMobileAdsMediationFacebook

Currently: 

'FBAudienceNetwork | = 6.12.0' is compatible with 'Google-Mobile-Ads-SDK | ~> 10.0'
 

[

**Comment by DavidAPears** [comment]
I have the same error. My set up: 

XCode (latest version): 14.3
react-native: "0.71.6"
react-native-admob-native-ads: ^0.6.0
react-native-vector-icons: ^9.2.0

When I add the following to my podfile (as per docs)

```
pod 'Google-Mobile-Ads-SDK'
pod 'GoogleMobileAdsMediationFacebook'
```

And then  `pod install --repo-update`

Pod installation works, however, running the project in XCode gives the error:

`Framework not found FacebookAdapter`

🫤 Sadly [davidmarcos98](https://github.com/davidmarcos98)'s fix didn't help

**Comment by baesumin** [comment]
+1
