### ISSUE TITLE
Release v0.6.0

### ISSUE THREAD

**Issue by ammarahm-ed** [ammarahm-ed/react-native-admob-native-ads#251]
We are almost ready for releasing v0.6.0.

- [x] Implement ad repository and preloading Thanks to @Ali72 @ha-younes72 
- [x] Upgrade to latest Google Mobile Ads Sdk on Android and iOS
- [x] Write docs for Ad Preloading & Repository Management

Issues to fix:

- [x] #209

**Comment by jorgegvallejo** [comment]
Eager to try this. Any estimate on when you all will get this out?
