### ISSUE TITLE
clang error on fresh install without Facebook adapter

### ISSUE THREAD

**Issue by skam22** [ammarahm-ed/react-native-admob-native-ads#252]
❌  ld: framework not found FacebookAdapter
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

the installation doesn't mention that Facebook is required for an fresh build without mediation, but it fails to build without Facebook.

**Comment by ammarahm-ed** [comment]
@skam22 Try the master branch

**Comment by serdargun** [comment]
Same error with master @ammarahm-ed

**Comment by ammarahm-ed** [comment]
@serdargun Delete `node_modules` folder. Clean your project.

Run
```
npm install https://github.com/ammarahm-ed/react-native-admob-native-ads.git
```
Then navigate to `ios` folder and run `pod install --repo-update`

Try to build the app now. It should build normally.

**Comment by csumrell** [comment]
> 

I tried this and am still getting the error

**Comment by ammarahm-ed** [comment]
> > 
> 
> I tried this and am still getting the error

Add Facebook Audience network to your pod file to get it working then

**Comment by dorthwein** [comment]
Downgrading 6.9.0.1 fixed my issue with this.

`pod 'GoogleMobileAdsMediationFacebook', "~> 6.9.0.1"`

Solution posted in another issue... cheers!

**Comment by zoobibackups** [comment]
> Downgrading 6.9.0.1 fixed my issue with this.
> 
> `pod 'GoogleMobileAdsMediationFacebook', "~> 6.9.0.1"`
> 
> Solution posted in another issue... cheers!

still not working
