### ISSUE TITLE
Test Ads not loading after updating compileSdkVersion to 30

### ISSUE THREAD

**Issue by arrayframe** [ammarahm-ed/react-native-admob-native-ads#253]
Test Ads works fine until project upgrade compileSdkVersion to 30.

**Current configure**

- react-native-admob-native-ads Ver 0.5.0

- I also update build.gradle in  \node_modules\react-native-admob-native-ads\android based on [this ](https://github.com/ammarahm-ed/react-native-admob-native-ads/issues/235) thread.

Project able to compile and run but Ads won't display only AdBadge Icon is showing.

**Comment by arrayframe** [comment]
@ammarahm-ed , I have no idea how to use master branch, can you guide me? and also when will you plan to next release of 0.6 Ver?

**Comment by Zloka** [comment]
@arrayframe Were you able to resolve this issue?

I am experiencing something (potentially) similar. I do not get any ads though, and the following error message:

```
{"error":{"code":3,"domain":"com.google.android.gms.ads","message":"No ad config."}}
```

I see this error message by providing a logging function to the `onAdFailedToLoad`-prop, do you get any error message(s)?
