### ISSUE TITLE
dependency is not installing

### ISSUE THREAD

**Issue by khushbukachchhi** [ammarahm-ed/react-native-admob-native-ads#258]
gradle not bulid with this dependency
compileSdk  not specified,

**Comment by Logicbuzz04** [comment]
i have same issue

**Comment by ammarahm-ed** [comment]
@khushbukachchhi Can you try master branch

**Comment by khushbukachchhi** [comment]
> 

yes,I try master branch and my error is :
                          error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
E:\Project-RN\AadharLoan\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:29: error: package com.ammarahmed.rnadmob.nativeads does not exist
import com.ammarahmed.rnadmob.nativeads.RNAdmobNativePackage;
                                       ^
E:\Project-RN\AadharLoan\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:100: error: cannot find symbol
      new RNAdmobNativePackage(),
          ^
  symbol:   class RNAdmobNativePackage
  location: class com.facebook.react.PackageList
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by khushbukachchhi** [comment]
I solve this problem

**Comment by Rbkyada** [comment]
any update i facing same issues ?
