### ISSUE TITLE
Error - No ad config

### ISSUE THREAD

**Issue by Zloka** [ammarahm-ed/react-native-admob-native-ads#260]
This is not really a bug report, more so a request for help, thanks for this library!

I had been using it just fine for some time in development, but all of a sudden I seem to just get this error message:

```
{"error":{"code":3,"domain":"com.google.android.gms.ads","message":"No ad config."}}
```

I don't really understand why. Previously, I was getting test ads just fine. Now I cannot seem to get any, and I haven't changed my configuration. I was wondering if this is something a user of this library has ran into before?

**Comment by Zloka** [comment]
Notice #253 exists too, this might be a duplicate, though my case seems a tad different as I get no ads at all and an error message, whereas the author of that issue reportedly sees an "ad badge".

**Comment by ammarahm-ed** [comment]
Read this:
https://stackoverflow.com/questions/64299247/no-ad-config-on-onadfailedtoload-method-while-trying-to-load-ads
