### ISSUE TITLE
RNGADNativeView.m Build Failed in iOS

### ISSUE THREAD

**Issue by Logicbuzz04** [ammarahm-ed/react-native-admob-native-ads#262]
* BUILD FAILED *

The following build commands failed:
        CompileC /Users/imac/Library/Developer/Xcode/DerivedData/LiveLine-dyhhmsghrjqemqcwhbismighpxyj/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-admob-native-ads.build/Objects-normal/x86_64/RNGADNativeView.o /Volumes/Data/Chirag/LiveLine/node_modules/react-native-admob-native-ads/ios/RNGADNativeView.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-admob-native-ads' from project 'Pods')
(1 failure)

**Comment by Logicbuzz04** [comment]
if I use specific version of Google mobile ads like, 
pod 'Google-Mobile-Ads-SDK', ' 8.11.0' 

the error change with
** BUILD FAILED **


The following build commands failed:
        Ld /Users/imac/Library/Developer/Xcode/DerivedData/LiveLine-dyhhmsghrjqemqcwhbismighpxyj/Build/Products/Debug-iphonesimulator/LiveLine.app/LiveLine normal (in target 'LiveLine' from project 'LiveLine')
(1 failure)

**Comment by hoangdaicntt** [comment]
I have submitted an update to fix this #266

**Comment by Logicbuzz04** [comment]
@hoangdaicntt Thanks for answering

My problem solve with adding ( pod 'GoogleMobileAdsMediationFacebook', '6.5.1.0' ) in podfile
