### ISSUE TITLE
com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

### ISSUE THREAD

**Issue by ahtisham-gsoftconsulting** [ammarahm-ed/react-native-admob-native-ads#273]
react native version 0.68
error
com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

**Comment by ammarahm-ed** [comment]
Fixed on master

**Comment by minhchienwikipedia** [comment]
@ammarahm-ed please upgrade version as well
