### ISSUE TITLE
Not compatible with react-native-google-mobile-ads

### ISSUE THREAD

**Issue by wditechy** [ammarahm-ed/react-native-admob-native-ads#277]
Hi you are doing a great job to support Native Ads in ReactNative, Thank you.
Please help us to fix, need a compatibility with react-native-google-mobile-ads, any plan to release a latest one?

**Comment by ammarahm-ed** [comment]
@wditechy Does the master branch work for you?

```
npm install https://github.com/ammarahm-ed/react-native-admob-native-ads.git
```

**Comment by wditechy** [comment]
Thanks @ammarahm-ed
