### ISSUE TITLE
Android styling not working on v0.2.9

### ISSUE THREAD

**Issue by JosephCon1998** [ammarahm-ed/react-native-admob-native-ads#28]
I'm having a problem of android not rendering the children of NativeAdView properly. I saw an older issue that had the same problem and it said was fixed in v0.2.4, but I'm still getting the issue. Any help?

![Screen Shot 2020-05-22 at 3 03 23 AM](https://user-images.githubusercontent.com/17093807/82640849-51c07f80-9bd9-11ea-9897-4160749b3b8f.png)

The left is iOS 13.4.1 and the right is API 29 for Android.

The pink is the CallToActionView. If that wasn't there you'd see the HeadlineView and TaglineView but they are on top of each other and can't be styled properly.

**Comment by ammarahm-ed** [comment]
@JosephCon1998 can you reproduce this in the example??

**Comment by JosephCon1998** [comment]
@ammarahm-ed I ran the example and it did work as expected. I'm pretty confused. I tried to create a whole new project see if it worked but now my android simulator keeps crashing :/ I'm gonna do some more testing and see if I find anything. 

Here's a list of my dependencies in case you notice something about one of them that is causing the issue.

![Uploading Screen Shot 2020-05-24 at 12.27.34 AM.png…]()

**Comment by ammarahm-ed** [comment]
@JosephCon1998 Nothing seems strange here. Its a strange issue you are facing. Try creating ad in a different screen in your app maybe... does it always render incorrectly? have you tried the example with your own design for ad?

**Comment by JosephCon1998** [comment]
@ammarahm-ed I ran the example again and the example you gave works fine. Then I copy and pasted my code into the example and its giving the same problem I had on my app. Here's a pic of the simulators with my code copy and pasted into your project.

![Screen Shot 2020-05-25 at 10 36 04 AM](https://user-images.githubusercontent.com/17093807/82822426-c44c8c00-9e73-11ea-9b64-4772218f0ea3.png)

Here's a link to my App.js
https://gofile.io/d/qeAiwC

There isn't anything I can tell about my code that is different from your code in your example, yet mine is broken and yours works fine.

**Comment by ammarahm-ed** [comment]
I will take a look, still it is strange.

**Comment by ammarahm-ed** [comment]
Okay, I fixed it. Firstly I don't get why you were using `flexDirection` on `NativeAdView`. It does not work well with the custom native components. Here is how I fixed it. I basically wrapped all of it in a `View` as you can see and add the `styles` to it.

```jsx
import React from 'react';
import { View, StyleSheet, Text, Platform } from 'react-native';

import NativeAdView, {
  CallToActionView,
  IconView,
  HeadlineView,
  TaglineView,
  AdvertiserView,
  AdBadge,
  ImageView,
  MediaView,
  PriceView,
  StarRatingView,
  StoreView,
} from 'react-native-admob-native-ads';

const MyAd = (props) => {
  return (
    <View style={[styles.root]}>
      <NativeAdView style={styles.nativeAdView} enableTestMode>
        <View
        style={[styles.containerView]}
        >

     
        <View style={styles.infoColumn}>
          <HeadlineView style={[styles.headline]} />
          <TaglineView style={[styles.tagline]} />
        </View>

        <View style={styles.iconColumn}>
           <IconView style={styles.iconView} />
          <CallToActionView
            style={[styles.callToAction, { backgroundColor: 'red' }]}
            textStyle={[styles.callToActionText]}
          /> 
        </View>
        </View>
      </NativeAdView>
    </View>
  );
};

export default MyAd;

const styles = StyleSheet.create({
  root: {
    width: '100%',
    borderRadius: 10,
    marginBottom: 10,
    padding: 10,
  },
  containerView: {
    width: '100%',
    paddingVertical:10,
    flexDirection:'row',
  },  
  nativeAdView: {
    width: '100%',
 
  },
  iconView: {
    width: 100,
    height: 70,
    borderRadius: 5,
  },
  iconColumn: {
    flex: 0.4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoColumn: {
    flex: 0.6,
  },
  headline: {
    fontSize: 20,
    fontFamily: 'SFProDisplay-Bold',
  },
  tagline: {
    marginTop: 5,
  },
  callToAction: {
    width: 100,
    height: 35,
    marginTop: 5,
  },
  callToActionText: {
    fontFamily: 'SFProDisplay-Bold',
  },
});

```

**Comment by rogerkerse** [comment]
I have exactly the same issue with flexDirection row that everything is covered by the call to action button, i try more, but thus far wrapping everything inside another view doesn't seem to work
