### ISSUE TITLE
Issue with GoogleMobileAdsMediationFacebook

### ISSUE THREAD

**Issue by SergiOnGit** [ammarahm-ed/react-native-admob-native-ads#284]
ITMS-90863: Apple silicon Macs support issue - The app links with libraries that are not present on Mac:
@rpath/libfbobjc_ios-sdk_ads_src_FBAudienceNetwork_FBAudienceNetworkRelease.dylib

Looks like macs don't support 'GoogleMobileAdsMediationFacebook'. Can I remove this package? Or it is required and why?

What can I do to fix this?

**Comment by ammarahm-ed** [comment]
@SergiOnGit Have you added `GoogleMobileAdsMediationFacebook` to your podfile?

**Comment by SergiOnGit** [comment]
> @SergiOnGit Have you added `GoogleMobileAdsMediationFacebook` to your podfile?
> 
> It's required because without it facebook native banner ads can't be shown. They require special configuration. And it's strange that it's not working on M1 Mac. Maybe you are missing out on some configuration. Have you tried to build on a real device?

Yes I have added GoogleMobileAdsMediationFacebook to my Podfile. I remember this was working maybe for 1-2 months ago. I tried on a real device and it crashes at startup. I think because of this. Development works fine. If I don't use facebook native banner then can I remove GoogleMobileAdsMediationFacebook from my podfile?

**Comment by ammarahm-ed** [comment]
@SergiOnGit Technically you should be able to remove it and it should work fine.

**Comment by haresh4d** [comment]
If I remove GoogleMobileAdsMediationFacebook following error is thrown when I run the app.

` ld: framework not found FacebookAdapter`

**Comment by SergiOnGit** [comment]
@ammarahm-ed Can you point us how to remove GoogleMobileAdsMediationFacebook? Removing just from Podfile throws error.

**Comment by haresh4d** [comment]
Finally, I was able to run my app on Simulator by not using `@react-native-admob/admob`  and replacing it with `react-native-google-mobile-ads`

**Comment by ammarahm-ed** [comment]
> Finally, I was able to run my app on Simulator by not using `@react-native-admob/admob`  and replacing it with `react-native-google-mobile-ads`

So the issue was with the admob library. Not this one?

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed Can you point us how to remove GoogleMobileAdsMediationFacebook? Removing just from Podfile throws error.

I think then you will have to remove it by patching the library. I think there's some bug with excluding the library which i will fix when I get some time.

**Comment by haresh4d** [comment]
> > Finally, I was able to run my app on Simulator by not using `@react-native-admob/admob`  and replacing it with `react-native-google-mobile-ads`
> 
> So the issue was with the admob library. Not this one?

@ammarahm-ed I was solving the issue #256 and for that I removed both `react-native-admob-native-ads` and `@react-native-admob/admob`. Then I installed `react-native-google-mobile-ads` and app started running in simulator without any errors. After that I installed `react-native-admob-native-ads` and everything went just fine. But the realease build crashed on startup because of `@rpath/libfbobjc_ios-sdk_ads_src_FBAudienceNetwork_FBAudienceNetworkRelease.dylib` was not found. So I downgraded the GoogleMobileAdsMediationFacebook to version 6.9.0.1 that solved all my problems.

**Comment by SergiOnGit** [comment]
@ammarahm-ed I don't know how it was related, but after updating expo from 45.0.4 to 45.0.5 it was fixed. I have bare workflow.

**Comment by freeworldshadow** [comment]
> 

don't know why,but it workds,thx

**Comment by zoobibackups** [comment]
ld: framework not found FacebookAdapter react-native 69.4

**Comment by zoobibackups** [comment]
> > > Finally, I was able to run my app on Simulator by not using `@react-native-admob/admob`  and replacing it with `react-native-google-mobile-ads`
> > 
> > 
> > So the issue was with the admob library. Not this one?
> 
> @ammarahm-ed I was solving the issue #256 and for that I removed both `react-native-admob-native-ads` and `@react-native-admob/admob`. Then I installed `react-native-google-mobile-ads` and app started running in simulator without any errors. After that I installed `react-native-admob-native-ads` and everything went just fine. But the realease build crashed on startup because of `@rpath/libfbobjc_ios-sdk_ads_src_FBAudienceNetwork_FBAudienceNetworkRelease.dylib` was not found. So I downgraded the GoogleMobileAdsMediationFacebook to version 6.9.0.1 that solved all my problems.

I have same issue with react-native version 69.4. the library doest not working fine

**Comment by zoobibackups** [comment]
> 6.9.0.1

after donwgrading I have these issues 

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADAdLoader


Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADMultipleAdsAdLoaderOptions


Showing Recent Messages
Undefined symbol: _OBJC_METACLASS_$_GADNativeAdView



Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADCustomEventExtras



Showing Recent Messages
Undefined symbol: _GADSimulatorID



Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADCustomEventExtras

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADNativeAdMediaAdLoaderOptions

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADNativeAdViewAdOptions

**Comment by zoobibackups** [comment]
> 6.9.0.1

after donwgrading I have these issues 

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADAdLoader


Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADMultipleAdsAdLoaderOptions


Showing Recent Messages
Undefined symbol: _OBJC_METACLASS_$_GADNativeAdView



Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADCustomEventExtras



Showing Recent Messages
Undefined symbol: _GADSimulatorID



Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADCustomEventExtras

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADNativeAdMediaAdLoaderOptions

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADNativeAdViewAdOptions

**Comment by zoobibackups** [comment]
> 6.9.0.1

after donwgrading I have these issues 

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADAdLoader


Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADMultipleAdsAdLoaderOptions


Showing Recent Messages
Undefined symbol: _OBJC_METACLASS_$_GADNativeAdView



Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADCustomEventExtras



Showing Recent Messages
Undefined symbol: _GADSimulatorID



Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADCustomEventExtras

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADNativeAdMediaAdLoaderOptions

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADNativeAdViewAdOptions

**Comment by zoobibackups** [comment]
> 6.9.0.1

after donwgrading I have these issues 

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADAdLoader


Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADMultipleAdsAdLoaderOptions


Showing Recent Messages
Undefined symbol: _OBJC_METACLASS_$_GADNativeAdView



Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADCustomEventExtras



Showing Recent Messages
Undefined symbol: _GADSimulatorID



Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADCustomEventExtras

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADNativeAdMediaAdLoaderOptions

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADNativeAdViewAdOptions
