### ISSUE TITLE
How to autoplay Google native ads without having to click play button

### ISSUE THREAD

**Issue by deepakkumar089551** [ammarahm-ed/react-native-admob-native-ads#285]
How to autoplay Google native ads without having to click play button

**Comment by RajeshStark** [comment]
@deepakkumar089551 @arimandaharsha did you find any solution for this?

**Comment by RajeshStark** [comment]
this issue already closed here please check : https://github.com/ammarahm-ed/react-native-admob-native-ads/issues/73
