### ISSUE TITLE
Error showing ad with Production IDs

### ISSUE THREAD

**Issue by iphonic** [ammarahm-ed/react-native-admob-native-ads#289]
Hi, Have used the library to set up ads in our project successfully, it works great with TestIDs from google. But when we replace the test ad ids with Production IDs created 4 days back, the ad section shows **Error showing ad** see screenshot below.. In log, all works fine, but we are receiving 

`<Google> <Google:HTML> The ad request returned a no fill for the particular slot.`

![IMG_0C5D343B2F17-1](https://user-images.githubusercontent.com/5745637/174311813-316cd4fd-4166-435b-9de0-be628819c91d.jpeg)

What could be the reason behind this?

**Comment by ammarahm-ed** [comment]
Ad ids are new. wait.

**Comment by iphonic** [comment]
@ammarahm-ed It's been 6 days, and surprisingly it is working on Android, not on iOS..

**Comment by ammarahm-ed** [comment]
Maybe you missed something related to configuration on iOS. That's my best guess. You should recheck all the steps, ad ids, app ids, skadnetwork ids etc to see if that helps. Also just to let you know, you must generate separate ids for iOS app and Playstore app on Admob console.

**Comment by iphonic** [comment]
Yes I have generated separate id for iOS and Android, I don't think there is an issue with configuration as the moment I change the ad ids with test ids, the ads starts showing, but with our ids it shows `Error showing ad` in iOS but works on Android with its id, created using the same process linked with app stores.

Can it be because of the Test Device setup? Because we don't have any for iOS.
