### ISSUE TITLE
[iOS] Use of undeclared identifier 'GADAdLoaderAdTypeNative'

### ISSUE THREAD

**Issue by qhoarau** [ammarahm-ed/react-native-admob-native-ads#290]
iOS build fails when builiding my app with the following error : Use of undeclared identifier 'GADAdLoaderAdTypeNative' ; did you mean 'kGADAdLoaderAdTypeNative'?

And when I replace "GADAdLoaderAdTypeNative" with "kGADAdLoaderAdTypeNative" as it is said, it works.

Version : 
Xcode : 13.4.1
react-native : 0.68.2
react-native-admob-native-ads: ^0.6.0,

**Comment by zoobibackups** [comment]
> 6.9.0.1

after donwgrading I have these issues 

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADAdLoader


Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADMultipleAdsAdLoaderOptions


Showing Recent Messages
Undefined symbol: _OBJC_METACLASS_$_GADNativeAdView



Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADCustomEventExtras



Showing Recent Messages
Undefined symbol: _GADSimulatorID



Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADCustomEventExtras

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADNativeAdMediaAdLoaderOptions

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_GADNativeAdViewAdOptions

**Comment by zoobibackups** [comment]
any solution for this

**Comment by cap1-0** [comment]
@zoobibackups  @qhoarau  @henrik-d  Have you found a solution yet?

**Comment by ammarahm-ed** [comment]
Fixed in v0.6.4.
