### ISSUE TITLE
The requested repo is not registered

### ISSUE THREAD

**Issue by medonagy45** [ammarahm-ed/react-native-admob-native-ads#291]
Hi , 
I am getting the following error on the onAdFailedToLoad
`AD FAILED The requested repo is not registered`
platform: android

**Comment by medonagy45** [comment]
I have figured it out All I have to do is to remove `repository` prop as i didn't register one

**Comment by gorkemunluyurt** [comment]
I'm experiencing the same problem. Can you please describe how you solved it?

**Comment by medonagy45** [comment]
All you need to do is to remove the last repository property from the adview 

> <NativeAdView
      ref={nativeAdRef}
      onAdLoaded={onAdLoaded}
      onAdFailedToLoad={onAdFailedToLoad}
      onAdLeftApplication={onAdLeftApplication}
      onAdClicked={onAdClicked}
      onAdImpression={onAdImpression}
      onNativeAdLoaded={onNativeAdLoaded}
      refreshInterval={60000 * 2}
      style={{
        width: '98%',
        alignSelf: 'center',
        backgroundColor: 'transparent',
      }}
      videoOptions={{
        customControlsRequested: true,
      }}
      // adUnitID={type === 'image' ? adUnitIDs.image : adUnitIDs.video} // REPLACE WITH NATIVE_AD_VIDEO_ID for video ads.
      `repository={type === 'image' ? 'imageAd' : 'videoAd'}`
    >

**Comment by gorkemunluyurt** [comment]
Hello! Thank you for fixing the error. But the ads are still not being displayed. What could be the reason for this? Here is my code:<NativeAdView
      style={{ borderRadius: 10, width: wp(44), height: wp(47), marginBottom: wp(2) }}
      ref={nativeAdViewRef}
      adUnitID="ca-app-pub-3940256099942544/2247696110"
      onAdFailedToLoad={(e) => {
        console.log(e)
      }}
    />

**Comment by medonagy45** [comment]
Hi , 
The `NativeAdView ` is the container for the ad please check the attached example in the repo itself

**Comment by gorkemunluyurt** [comment]
I apologize for the inconvenience. Despite the onadloaded function running, the ads are still not showing. Does anything come to mind as a reason for this? Thank you.

**Comment by gorkemunluyurt** [comment]
thank you 👍
