### ISSUE TITLE
[iOS] [Invariant Violation: requireNativeComponent: "RNGADImageView" was not found in the UIManager.]

### ISSUE THREAD

**Issue by renatomserra** [ammarahm-ed/react-native-admob-native-ads#292]
Getting this error since i updated to the latest

```[Invariant Violation: requireNativeComponent: "RNGADImageView" was not found in the UIManager.]```

Seems to be IconView that is breaking this

Any clues on how to fix?

Thank you

**Comment by RenatoSerra22** [comment]
Seems to be IconView that is breaking this

**Comment by okinawaa** [comment]
face same issue 😢

**Comment by RohitBansal272** [comment]
Any update on this?
