### ISSUE TITLE
[Android] Error connecting on latest version

### ISSUE THREAD

**Issue by renatomserra** [ammarahm-ed/react-native-admob-native-ads#294]
On the latest version upgrade and moving to preloading, on Android my impressions dropped to zero and getting 

{"error":{"code":0,"domain":"com.google.android.gms.ads","message":"Error while connecting to ad server: Failed to connect to googleads.g.doubleclick.net/:::443"}}

Working fine on iOS

**Comment by MueezHaider** [comment]
Same issue have any solution

**Comment by renatomserra** [comment]
Nop, i uninstalled this package and now just using banner ads from the common admob library. Looks ugly but works well

**Comment by ammarahm-ed** [comment]
Fixed in v0.7.3
