### ISSUE TITLE
Ads not loading on Android

### ISSUE THREAD

**Issue by sethcwhiting** [ammarahm-ed/react-native-admob-native-ads#295]
I'm having issues with ads loading on Android. As you can see, they load fine on iOS:
![Simulator Screen Shot - iPhone 12 - 2022-07-06 at 13 06 11](https://user-images.githubusercontent.com/2145601/177605639-5d677466-cbe6-422d-abfd-cf05bfc372a3.png)

But nothing shows up on Android:
![Screenshot_1657127144](https://user-images.githubusercontent.com/2145601/177605670-8463b07d-78ef-4eb2-9c54-c6f39aad6a5d.png)

The crazy colors are just to show where things should be showing up.

Here's the relevant code:

in my `App.tsx` file:

```
  AdManager.registerRepository({
    name: "testingAds123",
    adUnitId: NATIVE_AD_ID,
    numOfAds: 3,
    nonPersonalizedAdsOnly: false,
    videoOptions: {
      mute: false,
    },
    expirationPeriod: 3600000, // in milliseconds (optional)
    mediationEnabled: false,
    mediaAspectRatio: "portrait",
    enableTestMode: true,
  }).then((result) => {
    console.log("registered: ", result);
  });
  ```

My component:

```
import React, { useEffect, useRef, FC, memo, MutableRefObject } from "react";
import { Dimensions, StyleSheet, View, Animated } from "react-native";
import NativeAdView, {
  CallToActionView,
  HeadlineView,
  TaglineView,
  IconView,
  NativeMediaView,
} from "react-native-admob-native-ads";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import colors from "~theme/colors";
import typography from "~theme/typography";

const { width, height } = Dimensions.get("window");

const GoogleAdPost: FC = () => {
  const { bottom } = useSafeAreaInsets();
  const nativeAdViewRef = useRef<NativeAdView>();

  useEffect(() => {
    nativeAdViewRef?.current?.loadAd();
  }, []);

  return (
    <Animated.View style={{ height }}>
      <NativeAdView
        ref={nativeAdViewRef as MutableRefObject<NativeAdView>}
        repository="testingAds123"
        style={styles.container}
      >
        <View style={styles.safeContainer}>
          <NativeMediaView style={styles.media} />
        </View>
        <View style={styles.mainView}>
          <View style={{ ...styles.footerView, bottom: 60 + bottom }} testID="attributesView">
            <View style={{ marginBottom: 20 }}>
              <IconView style={styles.icon} />
              <HeadlineView style={styles.postDescriptionText} />
              <TaglineView style={styles.descriptionViewLarge} />
              <CallToActionView style={styles.cta} textStyle={styles.ctaText} />
            </View>
          </View>
        </View>
      </NativeAdView>
    </Animated.View>
  );
};

export default memo(GoogleAdPost);
```

**Comment by sethcwhiting** [comment]
Another quick update: I changed my adUnitId to the test id in the docs (`ca-app-pub-3940256099942544~3347511713`) and got a different error message:

```
{
    "error": {
        "code": 1,
        "domain": "com.google.android.gms.ads",
        "message": "Error building request URL."
    }
}
```

**Comment by RenatoSerra22** [comment]
I've also seen a drastic decrease in impressions on android, while ios with about the same DAU is much higher

**Comment by sethcwhiting** [comment]
Another quick update: That 2nd adUnitId from the AdMob docs didn't work for iOS, but the 1st one from the react-native-admob-native-ads docs did, so... I'm assuming `"Invalid template ID: -1"` might be the better error to have? I'm still not sure how to resolve it though.

**Comment by MamoshiSE** [comment]
Did you find any solution to this? I am encountering the exact same issue when trying to preload the ads.

**Comment by sethcwhiting** [comment]
@MamoshiSE I did resolve this a while ago. Sorry for not updating here. I think what happened was that I was trying to use the same ID in my `android/app/src/main/AndroidManifest.xml` file as in my `App.tsx` file. They shouldn't match. You get the one for your `AndroidManifest.xml` from AdMob, and the one for your `App.tsx` from the docs.
