### ISSUE TITLE
Comple errors on react-native 0.69.1

### ISSUE THREAD

**Issue by aleluiah** [ammarahm-ed/react-native-admob-native-ads#298]
Hi, thanks for the library this package and other installed package give a lot of compile errors in react-native 0.69.1 that otherwise would have worked for lower react native versions like 0.64.2.

**Comment by aleluiah** [comment]
for example method toList() is not found in react native 0.69.1 but compiles on react-native 0.64.2

**Comment by zoobibackups** [comment]
ld: framework not found FacebookAdapter
