### ISSUE TITLE
Native Ad Custom Style Functionality?

### ISSUE THREAD

**Issue by JoonJoon123** [ammarahm-ed/react-native-admob-native-ads#3]
Hi @ammarahm-ed 

Awesome job with the easy implementation! But, the native ad template does not match my app. Can you add customization functionality like [https://github.com/callstack/react-native-fbads](url) so that there is further customization available. 

Thanks in Advance.

**Comment by ammarahm-ed** [comment]
Well I will look into it, can you give me an idea on how you want it to look like and what is not working for you specifically?

**Comment by ammarahm-ed** [comment]
However the native ads are currrently customizable to some degree, do explain it a little more. I have seen fbads, that seems complicated but I will look into how it works.
