### ISSUE TITLE
Hi, am getting an error that says invariant violation View config not found for name mediaview

### ISSUE THREAD

**Issue by aleluiah** [ammarahm-ed/react-native-admob-native-ads#30]
Hi, thanks for the great project, but am getting an error that says invariant violation iew config not found for name mediaview and Nativeadview.
![IMG_20200525_115518](https://user-images.githubusercontent.com/65899491/82807988-e4cf1300-9e80-11ea-8f29-2b2e72c79dd7.jpg)

**Comment by aleluiah** [comment]
am running this from an ejected expo project

**Comment by aleluiah** [comment]
![IMG_20200525_151121](https://user-images.githubusercontent.com/65899491/82831737-25df1b80-9eb1-11ea-8c7c-9ef03711d79f.jpg)

**Comment by ammarahm-ed** [comment]
https://docs.expo.io/expokit/expokit/#changing-native-dependencies

Have you followed this guide to link your project properly? 

The error is showing because Its unable to detect he native components

**Comment by aleluiah** [comment]
thanks bro, resolved the issue on bare react native project without using expo

**Comment by ammarahm-ed** [comment]
I am closing this
