### ISSUE TITLE
iOs: problem with GADNativeAdView and 'GADNativeAdLoaderDelegate' (cannot find)

### ISSUE THREAD

**Issue by vuhongson-01** [ammarahm-ed/react-native-admob-native-ads#303]
![Screen Shot 2022-08-15 at 09 30 47](https://user-images.githubusercontent.com/103438906/184567643-b962d4b3-7fcd-4131-8a96-1897b585d439.png)

This is my problem, this API has any error with my project, can't not find GADNativeAdView, GADNativeAdLoaderDelegate, GAMRequest, adRequest,... in RNGADNativeView.h and RNGADNativeView.m, what can I do ?:(((

**Comment by dipamshujindal1993** [comment]
I am also facing the same problem.
 "react-native-admob-native-ads": "^0.6.0",
 "@react-native-firebase/admob": "^11.5.0",
    "@react-native-firebase/app": "^11.2.0",
"react": "17.0.1",
    "react-native": "0.64.0",
How can i fix this issue?

![Screenshot 2022-08-16 at 10 54 19 AM](https://user-images.githubusercontent.com/58145191/184804079-6943c3ec-4fad-432b-80d5-a7d27b5f0a2e.png)

**Comment by vuhongson-01** [comment]
> I am also facing the same problem. "react-native-admob-native-ads": "^0.6.0", "@react-native-firebase/admob": "^11.5.0", "@react-native-firebase/app": "^11.2.0", "react": "17.0.1", "react-native": "0.64.0", How can i fix this issue?
> 
> ![Screenshot 2022-08-16 at 10 54 19 AM](https://user-images.githubusercontent.com/58145191/184804079-6943c3ec-4fad-432b-80d5-a7d27b5f0a2e.png)

DON'T USE google-firebase-admob because this is suport in v11.5.0 => in IOs, google SDK is out date. your can use the library is suggested in react-native-admob-native-ads READ.me
