### ISSUE TITLE
Custom targeting not working on iOS

### ISSUE THREAD

**Issue by mwh1r** [ammarahm-ed/react-native-admob-native-ads#306]
Firstly, nice library 👏 

I have custom targeting setup for ads and it works on Android but not iOS.

[Docs](https://ammarahm-ed.github.io/react-native-admob-native-ads/docs/nativeadview/targetingoptions-6#targets) define type for `targets` as array of `Target:{ key: boolean, value: string | Array<string> }` so have something like the following:
```js
<NativeAdView
    ref={ref}
    targetingOptions={{
      targets: [
        { key: 'key1', value: 'value1' },
        { key: 'key2', value: 'value2' },
      ],
    }}
    adUnitID={adUnitID}>
    ...
</NativeAdView>
```

 Looking at the native code, i can see the [Android code](https://github.com/ammarahm-ed/react-native-admob-native-ads/blob/master/android/src/main/java/com/ammarahmed/rnadmob/nativeads/Utils.java#L21) seems to handle the `targets` prop based on the type - but the [iOS code](https://github.com/ammarahm-ed/react-native-admob-native-ads/blob/master/ios/RNAdMobManager/RNGADNativeView.m#L109) does not seem to do the same sort of logic.
 
 So taking that into account, i changed `targets` to something like the following and sure enough it worked on iOS:
 
 ```js
<NativeAdView
    ref={ref}
    targetingOptions={{
      targets:
        Platform.OS === 'android'
          ? [
              { key: 'key1', value: 'value1' },
              { key: 'key2', value: 'value2' },
            ]
          : { key1: 'value1', key2: 'value2' },
    }}
    adUnitID={adUnitID}>
    ...
</NativeAdView>
```
 
 Am i missing something here or is this indeed an issue?

**Comment by ammarahm-ed** [comment]
Fixed in v0.6.5
