### ISSUE TITLE
error when I try to launch the example with react-native run-android

### ISSUE THREAD

**Issue by Gio1378** [ammarahm-ed/react-native-admob-native-ads#31]
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: spawn ./gradlew ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by ammarahm-ed** [comment]
@Gio1378 give executable & read/write permission to ./gradlew file in android folder of the example

**Comment by Gio1378** [comment]
Build was done successfully, 🙂

**Comment by rithiksachdev** [comment]
What is command that you used @Gio1378 ??

**Comment by Gio1378** [comment]
Sorry @ammarahm-ed, I don’t remember what kind of command I’ve used.
