### ISSUE TITLE
issue with react-native-google-mobile-ads

### ISSUE THREAD

**Issue by AftabUfaq** [ammarahm-ed/react-native-admob-native-ads#310]
Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:8-29:68 to override.

**Comment by techday84** [comment]
Hi @AftabUfaq, Do you have react-native-google-mobile-ads and react-native-admob-native-ads working in the same app?

**Comment by zoobibackups** [comment]
@techday84 yes i am using both in same project.

**Comment by AftabUfaq** [comment]
the latest version is now fine,
