### ISSUE TITLE
[Android] onAdImpression and onAdClicked doesn't work properly

### ISSUE THREAD

**Issue by wonderlul** [ammarahm-ed/react-native-admob-native-ads#317]
# Issue

onAdImpression and onAdClicked events are not being invoked immediately. 

## Description

We have a problem with tracking impression and clicks. Let's say we display an ad and onAdImpression event is not being triggered. If we open the ad, onAdClicked event is not being triggered as well (onAdOpened works properly). What changes the situation is setting the app to background and then back to active. Then onAdImpression will be triggered. Also onAdClicked is starting to work after. I noticed similar behaviour on debug build, when those events are starting to work just after dismissing debug warning.

## Extras

Everything works fine for customFormatAd or on iOS. Issue only occurs for nativeAd on Android.

## Question
What could be the issue?

Looking forward to hearing from you!

If any additional informations are required, please let me know.

Best regards!

**Comment by andresribeiro** [comment]
I'm having the same problem, but setting the app to background and then back to active doesn't make it work. None of the on* props are working, except onNativeAdLoaded. I'm using FlashList, but it also doesn't work with FlatList neither outside the list.

### Library version
0.6.0

### React Native version

0.71.3

### Platform

Android (I haven't tested with iOS)

**Comment by andresribeiro** [comment]
This issue only affects ads preloaded by a repository

**Comment by ammarahm-ed** [comment]
Fixed in v0.7.3.
