### ISSUE TITLE
`onAdFailedToLoad` and `CallToActionView` TS types are wrong

### ISSUE THREAD

**Issue by IB3N** [ammarahm-ed/react-native-admob-native-ads#319]
# Issue 

The TS type of `onAdFailedToLoad` (Issue 1) and `CallToActionView ` (Issue 2) are slightly wrong. Please see the following code and my console logs for further info.

### My implementation

```typescript
const captureException = (e: { error: { message: string } }) => {
  console.error(e);
  console.log(e.error.message);
  Sentry.captureException(new Error(e.error.message));
};

<NativeAdView
  onAdFailedToLoad={captureException}
  ...restOfProps
  />
```

### Terminal output

```bash
ERROR  {"error": {"code": 3, "domain": "com.google.android.gms.ads", "message": "No ad config."}}
LOG  No ad config.
```

![Screenshot 2022-12-28 at 15 55 50](https://user-images.githubusercontent.com/62890543/209838601-352c2d29-1fc3-44c5-af08-98e4854783ef.png)

### Format of received error

```json
{
  "error": {
    "code": 3,
    "domain": "com.google.android.gms.ads",
    "message": "No ad config."
  }
}
```

This log is from Android but the same is true on iOS.

## Suggestion

The typescript type definition file `react-native-admob-native-ads/index.d.ts` should be updated to include the top level `error` key

```typescript
// react-native-admob-native-ads/index.d.ts

// Current
onAdFailedToLoad?: (error: { message: string }) => void;

/// Fixed - NTH add `domain` and `code` keys 
onAdFailedToLoad?: (error: { error: { message: string } }) => void;
```

## Issue 2 - `CallToActionView`

`CallToActionView` handles the prop `buttonAndroidStyle` https://github.com/ammarahm-ed/react-native-admob-native-ads/blob/49faf7c8874901224c4ddbe0a689a5ebda3bba18/src/CallToActionView.js#L12-L18

But this is not contained within the TS definitions

```typescript
// react-native-admob-native-ads/index.d.ts
export function CallToActionView(props: NestedTextProps): JSX.Element;
...
type NestedTextProps = {
  style?: StyleProp<ViewStyle>;
  textStyle?: TextStyle;
  allCaps?: boolean;
  allowFontScaling?: boolean;
};
```

### Suggestion 

Add `buttonAndroidStyle` to the typescript definitions

**Comment by ammarahm-ed** [comment]
Both issues have been fixed in v0.6.4
