### ISSUE TITLE
ANDROID: error: { message: 'The ad request was successful, but no ad was returned due to lack of ad inventory.'

### ISSUE THREAD

**Issue by pperron** [ammarahm-ed/react-native-admob-native-ads#32]
Hi,
just installed your demo app on ANDROID and get this when the app finish loading (it triggers the 'onAdFailedToLoad'):
``error:` { message: 'The ad request was successful, but no ad was returned due to lack of ad inventory.'``

I was using your lib in my project and had that problem, so I downloaded your demo app to verify what I was doing wrong, but get the same problem on the demo app too... 

Since 'adUnitID' is set to a demo ID (ca-app-pub-3940256099942544/1044960115), it should always return a content to display no ?

Tried with the adUnitID "ca-app-pub-3940256099942544/2247696110" and get same result or the ad only shows the mediaView content with no IconView, HeadlineView, TaglineView, AdvertiserView or  CallToActionView text content...

Any idea what is happening ? 

Thanks !

**Comment by pperron** [comment]
Just did an other test and installed the demo app on the Android emulator (Pixel 2 API 25 x86 running Android 7.1.1) and has the same result. For the real device, I'm using a Samsung Galaxy Tab A 2019 tablet, so Android OS is recent...

**Comment by ammarahm-ed** [comment]
@pperron did you test the demo app? I have no such issue in the demo app. Try it out there. The lack of inventory error occurs due to server not returning the ads, its not related to this library. You can clear the build folders etc and try again, remove the app from your phone/emulator then install fresh.

**Comment by pperron** [comment]
Hi,
yes I was using the demo app for my testing. Tested the IOS version on my Iphone 11 and was working OK, stopped and restarted the app and get the ad displayed each time. Right now I'M trying to compile my project with your lib for IOS, getting some errors, will finish make it work and see if integrated to my project it is working OK.

After that will come back to Android to see if still have the problem. That way I will know if my network is responsible for some reason (will take that possibility off the problem list at least !).

I working on that tonight, so will keep you informed.

Thanks !

**Comment by perrosnk** [comment]
@pperron Have you found any solution?

I am having the same problem.

**Comment by pperron** [comment]
@perrosnk I have been testing on IOS to see if I have same problem. So far I tested the example app and it was working OK. Then waisted long time to make my project (that in using in part the lib but was not the cause of me having problems to compile) compile for IOS. When I succedded, the ads were displaying OK too. Working again on that tonight, will see if I have time to get back to the Android version to see if problem still there.

Would be useful to know if any other users have the same problem for the Android version...

**Comment by albertocubero** [comment]
I using only Android and I have Admob configured:
- React Native 0.61.5 version like the example
- Always removing the App in the simulator and removing the build folder in android folder.

I did 2 tests (in simulator, mac) 
- using my Admob configuration:
        - In my app: NOT show Ads
        - In Example app: YES, show Ads
- using the example Admod configuration:
        - In my app: NOT show Ads
        - In Example app: YES, show Ads

I have followed all the needed steps, I have reviewed all the example gradle configuration files, etc. and with the same configuration and I don't understand why with the same Admod IDs in the example I get Ads and in my app don't.

**Comment by ammarahm-ed** [comment]
@albertocubero delete your app from the phone/clean build folders. Thats the only way I have fixed it ever. in android folder run `./gradlew clean` and run build again

**Comment by yaroslavnikiforov** [comment]
It loads on Android only ones after installing the app (use this unit id: ca-app-pub-3940256099942544/1044960115). After I have the same error. Only with this test native video unit id. If I delete the app and install it again it will load.

**Comment by yaroslavnikiforov** [comment]
So this happens if you don't immediately render the ad components inside the NativeAdView, for example:
`
<NativeAdView>
   {isVisible && <MediaView />}
</NativeAdView>
`

**Comment by patrickbattisti** [comment]
Same issue. It loads on Android only ones after installing the app, after I have the same error "The ad request was successful, but no ad was returned due to lack of ad inventory."

**Comment by Birat77** [comment]
Same issue here too. Ad loads for given example ad on the documentation example, doesn't work for other created ads
