### ISSUE TITLE
Feature request: Create Expo plugin

### ISSUE THREAD

**Issue by cbridges1** [ammarahm-ed/react-native-admob-native-ads#321]
Hello, Is anyone working on a plugin to support a custom EAS build in Expo? I can submit a PR for the changes I have if not. Please let me know if you or anyone else is interested @ammarahm-ed .

**Comment by RoccoDocco** [comment]
Hey, did you already create a config plugin? If yes, could you post it here? Thank you.

**Comment by cbridges1** [comment]
@RoccoDocco Sure thing. The pull request can be found [here](https://github.com/ammarahm-ed/react-native-admob-native-ads/pull/323).
