### ISSUE TITLE
Android does not compile

### ISSUE THREAD

**Issue by davidarnaub7** [ammarahm-ed/react-native-admob-native-ads#322]
..node_modules/react-native-admob-native-ads/android/src/main/java/com/ammarahmed/rnadmob/nativeads/Utils.java:11: error: cannot find symbol
import com.google.ads.mediation.facebook.FacebookAdapter;
                                        ^
  symbol:   class FacebookAdapter
  location: package com.google.ads.mediation.facebook

The app compiles correctly for IOS. But in Android this message appears.

Any idea?

**Comment by mrkgmr** [comment]
I have the same error since I udpdated to RN 0.71.0. In 0.70.4 it worked.

**Comment by haresh4d** [comment]
Run following command in your project directory:

`sed -i.backup 's/com.google.ads.mediation:facebook:6.+/com.google.ads.mediation:facebook:6.11.0.0+/g' node_modules/react-native-admob-native-ads/android/build.gradle`

**Comment by cbridges1** [comment]
Please see the comment in [this](https://github.com/ammarahm-ed/react-native-admob-native-ads/pull/323#issuecomment-1472993523) pull request to see if it resolves your issue.

**Comment by vaibhavgadekar** [comment]
> sed -i.backup 's/com.google.ads.mediation:facebook:6.+/com.google.ads.mediation:facebook:6.11.0.0+/g' node_modules/react-native-admob-native-ads/android/build.gradle

Working fine with this solution, Thanks @haresh4d

**Comment by ammarahm-ed** [comment]
This has been fixed in v0.6.3. Please update.
