### ISSUE TITLE
[Network Mediation] Logging impressions on FB audience network

### ISSUE THREAD

**Issue by perrosnk** [ammarahm-ed/react-native-admob-native-ads#33]
I have followed the Google's [guide](https://developers.google.com/admob/android/mediation/facebook) to integrate Facebook Audience Network.

I am receiving ads from fb but no impressions or clicks are logged when the ads appear on a Flatlist.

According to [this](https://developers.google.com/admob/android/mediation/facebook#impression_and_click_tracking) the FB Audience SDK is responsible for reporting the impressions.

There is an open [issue](https://github.com/callstack/react-native-fbads/issues/172) in this library for this issue and according to this [comment](https://github.com/callstack/react-native-fbads/issues/172#issuecomment-497807968), a `NativeAdLayout ` wrapper is responsible for this.

Does anybody have any idea on how this issue can be solved in `react-native-admob-native-ads`?

@ammarahm-ed thank you once again for this great library!

**Comment by perrosnk** [comment]
I would like to present some more findings:

1. Impressions on Android devices are logged correctly comparing the report from Google and Facebook
2. Impressions on iOS devices probably are not logged correctly. Facebook reports 1/3 of Google's reported impressions

**Comment by ammarahm-ed** [comment]
implementation is exactly the same on both platforms, have you tried the `onAdImpression` event to see if it is being called etc?

**Comment by perrosnk** [comment]
As a side note, logging impressions and clicks with test ads seems to work fine, but this might be because this event (as far as I understand) is triggered by Admob and not FB SDK. 
It might be that the FB SDK is not triggering those events and so are not logged as impressions and clicks on the FB account

**Comment by ammarahm-ed** [comment]
Fixed on master
