### ISSUE TITLE
[onAdFailedToLoad] [The requested repo is not registered]

### ISSUE THREAD

**Issue by duytn-zens** [ammarahm-ed/react-native-admob-native-ads#331]
Hi all , i've currently worked with native ads mob , and it take me to onAdFailedToLoad ( i'm using test ids ) .

AD][FAILED]: {"error": {"code": 3, "domain": "", "message": "The requested repo is not registered"}}

i'm very glad if someone can support me with this issue .

**Comment by renatomserra** [comment]
@duytn-zens did you find a solution?
