### ISSUE TITLE
Panresponder gestures are not working

### ISSUE THREAD

**Issue by nannish** [ammarahm-ed/react-native-admob-native-ads#333]
I have a panresponder where i use interpolate to animate the view with multiple items.
in between the items, i am loading the native ad using react-native-admob-native-ads package.
ads are loading but my gestures are no longer working once the NativeAdView is loaded.
Kindly suggest if there is any work around for this.

**Comment by IB3N** [comment]
I'm having a similar issue too. Given a normal `<View />` component, the solution might be to set [pointerEvents](https://reactnative.dev/docs/view#pointerevents) to `"box-none"` like so  `<NativeAdView pointerEvents="box-none" ... />`. `box-none` means that the parent component does not handle touch events but it's children can, like the `<CallToActionView />` would need to do.

I don't think this is available. @ammarahm-ed - might there be a way to add the `pointerEvents` prop to the NativeAdView?

**Comment by rdjuric** [comment]
Maybe extending `ReactViewGroup` instead of `LinearLayout` in the NativeAdView could help with this? @ammarahm-ed

**Comment by ammarahm-ed** [comment]
Provide a reproducible example.

**Comment by kasp416h** [comment]
Was this solved? I am having a similar issue with react-native-deck-swiper, where on android i am unable to swipe the NativeAdView with deck swiper. But works on iOS.

**Comment by kasp416h** [comment]
> Maybe extending `ReactViewGroup` instead of `LinearLayout` in the NativeAdView could help with this? @ammarahm-ed

did you try ReactViewGroup?
