### ISSUE TITLE
requireNativeComponent: "RNGADNativeView" was not found in the UIManager.

### ISSUE THREAD

**Issue by mhr996** [ammarahm-ed/react-native-admob-native-ads#336]
I'm using this library in my expo app (SDK 47), everything was fine during the installation and set-up, but once I add the `<NativeAdView>` component, it crashes and gives this error, what could be the problem?

full error: 

 ERROR  Invariant Violation: requireNativeComponent: "RNGADNativeView" was not found in the UIManager.

This error is located at:
    in RNGADNativeView (created by NativeAdView)
    in NativeAdView (created by ItemSeparatorComponent)
    in RCTView (created by View)

**Comment by ammarahm-ed** [comment]
Try v0.6.3 and follow installation steps. The library now supports expo.

**Comment by mhr996** [comment]
@ammarahm-ed will do, thank you so much

**Comment by stefanatanasovmk** [comment]
Hey,

I've tried using `v0.6.6` of `react-native-admob-native-ads` but still get the same error:

`ERROR  Invariant Violation: requireNativeComponent: "RNGADNativeView" was not found in the UIManager.`

I tried even to downgrade the `react-native-admob-native-ads` to `v0.6.3` as you suggested here, but still didn't work.

I'm using:
 "react-native": "0.71.7"
 "expo": "48.0.6"

**Comment by mhr996** [comment]
@stefanatanasovmk rebuild your development environment apk then try again
