### ISSUE TITLE
[AD][FAILED]: undefined. | Ad Not Loaded 

### ISSUE THREAD

**Issue by dipakjayswal** [ammarahm-ed/react-native-admob-native-ads#338]
When Load Ad it is now showing. and giving an undefined error. for both platforms.

![Screenshot 2023-07-16 at 6 23 00 PM](https://github.com/ammarahm-ed/react-native-admob-native-ads/assets/9650303/847c987e-be5c-4dda-b225-645f365be78d) ![Screenshot 2023-07-16 at 6 23 22 PM](https://github.com/ammarahm-ed/react-native-admob-native-ads/assets/9650303/0f6f9067-d841-43f2-a043-5c0ca09644f6)

**Comment by gilbertolenzi** [comment]
You need to change the onAdFailedToLoad function to Logger('AD', 'FAILED', event.message);

the existing example has event.error.message which returns empty.
