### ISSUE TITLE
Ad_impression event does not fire consistently in Firebase DebugView

### ISSUE THREAD

**Issue by rojakcode** [ammarahm-ed/react-native-admob-native-ads#340]
I implemented the native advanced format on a scroll feed. I did a number of tests in Firebase DebugView. Whenever the ad appears in the viewport, the ad_impression event should fire. However, it does so inconsistently in my case. Since we are paid according to impressions and the clicks that happen on them, that means devs lose out on ad revenue.

**Comment by nannish** [comment]
Facing the same issue on android devices. with 0.6.6 version.
onAdImpression event is not firing at all
Please suggest

**Comment by sontruongna** [comment]
I did a little hacking by putting an empty ScrollView and automatically scrolling when onAdLoaded. onAdImpression fired, but it's not perfect

**Comment by ammarahm-ed** [comment]
Fixed in v0.7.3
