### ISSUE TITLE
How to Handle "Stop Seeing this Ad" and "Why This ad? " 

### ISSUE THREAD

**Issue by ganeshtak** [ammarahm-ed/react-native-admob-native-ads#342]
Do we have any options for "Stop Seeing this Ad" and "Why This ad? ".
Or if this library provides any of these options?
According to google ad Choice is mandatory and any idea for personalized ads..

**Comment by JP6720** [comment]
i am getting same issue. i found one proeprty adchoicesPlacement but button is not showing

**Comment by ammarahm-ed** [comment]
Such things are added by admob automatically to the adview if needed.
