### ISSUE TITLE
 Default paused and muted not working in NativeMediaView

### ISSUE THREAD

**Issue by nirmalsinhrathodcygnet** [ammarahm-ed/react-native-admob-native-ads#344]
According to documentation I am using paused and muted in NativeMediaView but whatever I set (true/false) its not effected in video ads.

I am using "0.6.6" version of library.

**Comment by nirmalsinhrathodcygnet** [comment]
Hey, If anyone have any clue for this problem then kindly share here.

**Comment by krupal811** [comment]
Exactly same issue for me also, i am using muted = true. but its not works for me

**Comment by ammarahm-ed** [comment]
Whether ads will mute or not is controlled by the sdk, not us.
