### ISSUE TITLE
[AD][FAILED]: The operation couldn’t be completed. ( error 3.)

### ISSUE THREAD

**Issue by YubinKim16** [ammarahm-ed/react-native-admob-native-ads#346]
My app is failing to load native ads and is returning this error:

[AD][FAILED]: The operation couldn’t be completed. ( error 3.)

I have searched for what it means but I can't find a single post about this error code.

Does anyone know what this error means?

**Comment by hz-sanaullah** [comment]
@YubinKim16  Any news?

**Comment by csumrell** [comment]
i am also getting this error and ads just show a  : ( instead

**Comment by martinchamrad** [comment]
Same here. Anyone figured this out?

**Comment by martinchamrad** [comment]
Figured it out. Make sure you implement it the same way as in the example here:
https://github.com/ammarahm-ed/react-native-admob-native-ads/blob/master/example/index.js

**Comment by ammarahm-ed** [comment]
Fixed in v0.7.2
