### ISSUE TITLE
Enable donations

### ISSUE THREAD

**Issue by perrosnk** [ammarahm-ed/react-native-admob-native-ads#35]
I find this library so useful that I would be happy to donate for supporting the project because it's really useful for me. I also believe that is is very much needed by the community too as it is the only project in react-native that supports native ads.

**Comment by ammarahm-ed** [comment]
I will add funding.xml soon. Thank you!

**Comment by ammarahm-ed** [comment]
I have added FUNDING.yml file, you can see the sponsor button now
