### ISSUE TITLE
I have added adchoicesPlacement but adchoices icon is not showing

### ISSUE THREAD

**Issue by JP6720** [ammarahm-ed/react-native-admob-native-ads#350]
i have added             
adChoicesPlacement={AdOptions.adChoicesPlacement.TOP_LEFT}
paramter in NativeAdview but adchoices icon is not showing.

here is my code.

  `<NativeAdView
            ref={nativeAdRef}
            onAdLoaded={onAdLoaded}
            adChoicesPlacement={AdOptions.adChoicesPlacement.TOP_LEFT}
            onAdFailedToLoad={onAdFailedToLoad}   
 onAdLeftApplication={onAdLeftApplication}
            onAdClicked={onAdClicked}
            onAdImpression={onAdImpression}
            onNativeAdLoaded={onNativeAdLoaded}
            refreshInterval={60000 * 2}
            style={{
              width: '100%',
              height: showWhyThisAdModal ? 80 : 330,
            }}
            videoOptions={{
              customControlsRequested: true,
            }}
            mediationOptions={{
              nativeBanner: true,
            }}
            adUnitID={type === 'image' ? adUnitIDs.image : adUnitIDs.video} // REPLACE WITH NATIVE_AD_VIDEO_ID for video ads.
            repository={type === 'image' ? 'imageAd' : 'videoAd'}
          >

<View
                style={{
                  width: '100%',
                  padding: 12,
                  paddingHorizontal: 0,
                }}
              >
                {/* <TouchableOpacity
                  onPress={() => {
                    setShowWhyThisAdModal(true);
                  }}
                  style={{
                    width: 16,
                    position: 'absolute',
                    top: 0,
                    zIndex: 1,
                    left: 0,
                    height: 20,
                  }}
                >
                  <Image
                    resizeMode="contain"
                    source={imagePath.adChoice}
                    style={{
                      width: 16,
                      height: 16,
                    }}
                  />
                </TouchableOpacity> */}
                <View
                  style={{
                    height: moderateScale(55),
                    width: '100%',
                    flexDirection: 'row',
                    alignItems: 'center',
                    paddingLeft: 24,
                    opacity: loading || error || !loaded ? 0 : 1,
                    maxWidth: '100%',
                    backgroundColor: '#010101',
                    justifyContent: 'space-between',
                  }}
                >
                  <IconView
                    style={{
                      width: 50,
                      height: 50,
                      borderRadius: 100,
                    }}
                  />
                  <View style={{ flex: 1 }}>
                    <View
                      style={{
                        flexDirection: 'row',
                        alignItems: 'center',
                        paddingLeft: 10,
                        paddingBottom: 5,
                      }}
                    >
                      <HeadlineView
                        hello="abc"
                        style={{
                          color: '#fff',
                          flex: 1,
                          fontFamily: fonts.robotoRegular,
                          paddingEnd: moderateScale(6),
                          fontWeight: '700',
                          fontSize: moderateScale(18),
                        }}
                      />
                    </View>
                    <AdBadge
                      style={{
                        backgroundColor: 'yellow',
                        width: 25,
                        height: 20,
                        marginLeft: 10,
                        borderWidth: 1,
                        borderRadius: 4,
                        position: 'relative',
                        justifyContent: 'center',
                        alignItems: 'center',
                      }}
                      textStyle={{
                        fontSize: 12,
                        color: 'black',
                      }}
                    />
                  </View>
                  <CallToActionView
                    style={[
                      {
                        minHeight: 35,
                        justifyContent: 'center',
                        alignItems: 'center',
                        maxWidth: 100,
                        width: 80,
                        marginEnd: 10,
                        backgroundColor: Colors.lightBlue,
                      },
                      Platform.OS === 'ios'
                        ? {
                            backgroundColor: Colors.lightBlue,
                            borderRadius: 10,
                          }
                        : {},
                    ]}
                    // buttonAndroidStyle={{
                    //   backgroundColor: Colors.lightBlue,
                    //   borderRadius: 10,
                    //   borderColor: Colors.lightBlue,
                    //   borderWidth: 1,
                    // }}
                    allCaps
                    textStyle={{
                      fontSize: 13,
                      flexWrap: 'wrap',
                      textAlign: 'center',
                      color: 'white',
                      paddingTop:
                        Platform.OS === 'android' ? moderateScale(18) : 0,
                      paddingRight:
                        Platform.OS === 'android' ? moderateScale(12) : 0,
                    }}
                  />
                </View>
                <View style={{ padding: 15, paddingHorizontal: 0 }}>
                  <ImageView
                    style={{
                      width: '100%',
                      height: 230,
                      resizeMode: 'cover',
                    }}
                  />
                </View>
              </View>
</NativeAdView>`

**Comment by raiyanihiren** [comment]
Any solution then please suggest same issue

**Comment by ammarahm-ed** [comment]
AdChoices only show in production ads. It's managed by the google mobile ads sdk itself.
