### ISSUE TITLE
Invalid template ID: -1 affecting 40% of android user base

### ISSUE THREAD

**Issue by renatomserra** [ammarahm-ed/react-native-admob-native-ads#352]
I keep getting the following error in Android for about 40% of my users for a year.
I believe it started when i moved to preloading model.
Id really like to fix this :)

{"code":0,"domain":"com.google.android.gms.ads","message":"Invalid template ID: -1"}

Any help will be greatly appreciated

**Comment by renatomserra** [comment]
seems its the initialization.

2 types of errors:

- Failed to Create adaptar
- Failed to initialize adapter. com.google.ads.mediation.admob.AdMobAdapter does not implement the initialize() method.

@ammarahm-ed any idea? 🙏

**Comment by RoyalBosS-Ayush** [comment]
Facing same on real device. Any Update?

**Comment by renatomserra** [comment]
didnt manage to fix it, think this repo is no longer maintained unfortunetly

**Comment by ammarahm-ed** [comment]
Kindly provide an example to reproduce the issue.

**Comment by renatomserra** [comment]
i cant reproduce this on a simulator, only happens to some users, but seems most users have this issue.
