### ISSUE TITLE
[Question] Requested size

### ISSUE THREAD

**Issue by wonderlul** [ammarahm-ed/react-native-admob-native-ads#354]
Hello Everyone,

Not a bug, just a question from me. Do you know where "Requested sizes" is coming from? There is no prop responsible for that yet using AdManager delivery tools I see that requested sizes is 320x50.

![Screenshot 2023-11-22 at 10 35 03](https://github.com/ammarahm-ed/react-native-admob-native-ads/assets/56554355/f04d4643-c560-4a10-a894-dfe396b81a34)

If any additional information is needed, please tell. Looking forward to hearing from you.

Best regards

**Comment by ammarahm-ed** [comment]
You can use `mediaAspectRatio` to control this but this is mostly automatic.
