### ISSUE TITLE
 ERROR  Ad failed to load {"code": 0, "domain": "com.google.android.gms.ads", "message": "Internal error."}

### ISSUE THREAD

**Issue by MueezHaider** [ammarahm-ed/react-native-admob-native-ads#360]

**Comment by RNvivekvision** [comment]
i got the same issue in android emulator. then i run project in real android device. It works perfectly.

Try to run in real android device.

**Comment by MueezHaider** [comment]
Thanks for that info

**Comment by MueezHaider** [comment]
> i got the same issue in android emulator. then i run project in real android device. It works perfectly.
> 
> Try to run in real android device.

Does that mean to run simulator on real android phone or it means after deploying it?

**Comment by mustafaerken** [comment]
When i try to load test ad i get this error on Android:
{"error": {"code": 0, "domain": "com.google.android.gms.ads", "message": "Internal error."}}

**Comment by minhchienwikipedia** [comment]
Any solution?

**Comment by mustafaerken** [comment]
I have fixed this problem with changing emulator API 31 to API 30.
If you have a different API like me, just change it to API 30 and try again.

@dev007github thanks for your help.

**Comment by ammarahm-ed** [comment]
Fixed in v0.7.2
