### ISSUE TITLE
"code": 0, "domain": "com.google.android.gms.ads", "message": "Internal error."

### ISSUE THREAD

**Issue by mustafaerken** [ammarahm-ed/react-native-admob-native-ads#362]
Native Ads works fine on IOS but Android gives the error on the title.

<img width="691" alt="Screen Shot 2024-03-17 at 2 46 40 PM" src="https://github.com/ammarahm-ed/react-native-admob-native-ads/assets/25222561/148f1d10-fe48-439e-b39b-6f9cb9b28d7e">

**Comment by minhchienwikipedia** [comment]
Same, I got the same issue, can we have any solution?

**Comment by mustafaerken** [comment]
I have fixed this problem with changing emulator API 31 to API 30.
If you have a different API like me, just change it to API 30 and try again.

@dev007github thanks for your help.

**Comment by haresh4d** [comment]
having the same issue my Emulator API is 34. is there any other solution? as I have to test in API 34 only.

**Comment by ammarahm-ed** [comment]
Fixed in v0.7.2

**Comment by lyccccc1piano** [comment]
Must run on a real android device.
This error will only be displayed in the emulator.
