### ISSUE TITLE
Component 'RNGADNativeView' re-registered bubbling event 'topAdLoaded' as a direct event

### ISSUE THREAD

**Issue by RNvivekvision** [ammarahm-ed/react-native-admob-native-ads#367]
![Simulator Screenshot - iPhone 15 Pro - 2024-04-26 at 11 21 14](https://github.com/ammarahm-ed/react-native-admob-native-ads/assets/160696318/742b2f3e-3946-4aa4-b759-a187af2aded9)

### package.json
    "@mobeuv/react-native-check-ip": "^1.3.0",
    "@react-native-async-storage/async-storage": "^1.22.3",
    "@react-native-firebase/analytics": "^20.0.0",
    "@react-native-firebase/app": "^20.0.0",
    "@react-native-firebase/crashlytics": "^20.0.0",
    "@react-native-masked-view/masked-view": "^0.3.1",
    "@react-navigation/drawer": "^6.6.15",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/stack": "^6.3.29",
    "@reduxjs/toolkit": "^2.2.1",
    "patch-package": "^8.0.0",
    "postinstall-postinstall": "^2.1.0",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-admob-native-ads": "^0.6.6",
    "react-native-date-picker": "^4.4.2",
    "react-native-device-info": "^10.13.1",
    "react-native-element-dropdown": "^2.10.4",
    "react-native-fbads": "^7.1.1",
    "react-native-fbsdk-next": "^13.0.0",
    "react-native-gesture-handler": "^2.15.0",
    "react-native-google-mobile-ads": "^13.5.0",
    "react-native-localization": "^2.3.2",
    "react-native-rate": "^1.2.12",
    "react-native-reanimated": "^3.8.1",
    "react-native-restart": "^0.0.27",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "^3.29.0",
    "react-native-share": "^10.2.0",
    "react-native-splash-screen": "^3.3.0",
    "react-native-tracking-transparency": "^0.1.2",
    "react-native-vector-icons": "^10.0.3",
    "react-redux": "^9.1.0"

i am getting this error in ios only while installing react-native-admob-native-ads version 0.6.6.

i have patch this library which is as follows.

![Screenshot 2024-04-26 at 12 46 41 PM](https://github.com/ammarahm-ed/react-native-admob-native-ads/assets/160696318/0f334e81-d8c8-4d6b-a621-6529672bead3)

Whenever i run the project in ios, at the start i am getting this error and if i dismiss this, it does not gives error at all.
this error is thrown at the first time when app is opened.

Please give solution or update the library for ios.

**Comment by RNvivekvision** [comment]
Hii, is there any update to solve this issue.

whenever i integrate fbsdk, i got this error

Why???

**Comment by ammarahm-ed** [comment]
Another library is trying to incorrectly register the same event as a bubbling event. Not an issue with this library.
