### ISSUE TITLE
Expo EAS Build Not Working

### ISSUE THREAD

**Issue by digibuilders** [ammarahm-ed/react-native-admob-native-ads#368]
Patch #363 has been integrated into the master branch of GitHub, yet it hasn't been reflected as a new release version on NPM. Consequently, attempts to build using this package with EAS Build continue to result in errors. EAS Build generates a fresh instance of each downloaded package, directly sourcing them from NPMjs. As a consequence, the same iOS error persists when attempting to initiate a build with this package.

A straightforward resolution would involve updating the package version to '0.6.7' and executing 'npm publish' on the current library with issue #363 addressed. This library is indispensable for managing AdMob Native Ads, and its absence prevents the deployment of my app to production with customized banner ads.

Your prompt resolution of this matter would be immensely appreciated. Alternatively, I welcome any suggestions for workarounds that may be available. Thank you for your attention to this issue.

**Comment by dev-arekusandoru** [comment]
to use the latest version of the code in your project, rather than installing the package, link straight to the master branch
`npm install ammarahm-ed/react-native-admob-native-ads#master`
