### ISSUE TITLE
Could this tiny "i" in the corner be styled?

### ISSUE THREAD

**Issue by rogerkerse** [ammarahm-ed/react-native-admob-native-ads#37]
![image](https://user-images.githubusercontent.com/571171/84006367-45794800-a977-11ea-8123-51b7bf32d0bc.png)
Is it possible to style this? or move it around?

**Comment by ammarahm-ed** [comment]
Right now its not possible, hopefully i will add it in the next release.

**Comment by KVinS** [comment]
@ammarahm-ed  Many would have had just the choice of color design.
Light / Dark / Gray
I understand that this icon should stand out and just want a white background instead of gray.

**Comment by ammarahm-ed** [comment]
It has no background, why is it black? For me it is always white.. Maybe you have added some color etc to main app theme on native side??

**Comment by KVinS** [comment]
> It has no background, why is it black? For me it is always white.. Maybe you have added some color etc to main app theme on native side??

I'm talking about the background "i"

**Comment by ammarahm-ed** [comment]
It cannot be changed, it is an image recieved from admob server.

**Comment by ammarahm-ed** [comment]
closing. the customization that was possible has been added for **v0.3.0**

**Comment by JP6720** [comment]
why i am not seeing this i icon?
