### ISSUE TITLE
How to reload the ad when navigate the screen or kill the app and then reopen the app the ad is reload and when click on ad and then reopen the app show new ad

### ISSUE THREAD

**Issue by zoobibackups** [ammarahm-ed/react-native-admob-native-ads#371]
How I reload the ad in react native Admob native ads

**Comment by LukasMod** [comment]
I completely don't understand the title of your issue, but you can rebuild the react element by changing its `key` prop on some condition, like focus.

**Comment by ammarahm-ed** [comment]
Use the view ref to trigger ad reload. `nativeAdViewRef.current?.loadAd()`
