### ISSUE TITLE
error while updating property 'requestnonpersonalizedadsonly' of a view managed by : rngadnativeview 

### ISSUE THREAD

**Issue by pradhyumansinh9849** [ammarahm-ed/react-native-admob-native-ads#374]

**Comment by zoobibackups** [comment]
same issue

**Comment by haresh4d** [comment]
Everybody is stuck here but there is no solution. If anyone has idea about how to solve it please spare some time.

**Comment by haresh4d** [comment]
Following fixed for me:

Change build.gradle line 56 from :

implementation "com.google.android.gms:play-services-ads:${safeExtGet('googlePlayServicesAdsVersion', '20.+')}"

to

implementation "com.google.android.gms:play-services-ads:${safeExtGet('googlePlayServicesAdsVersion', '23.+')}"

**Comment by zoobibackups** [comment]
for me fixed that issue is comment these lines in 
if (config.hasKey("requestNonPersonalizedAdsOnly")) {
           // Utils.setRequestNonPersonalizedAdsOnly(config.getBoolean("requestNonPersonalizedAdsOnly"), adRequest);
        } in node modules -> react native admob native ads ->RNAdMobUnifiedAdQueueWrapper.java
 public void setRequestNonPersonalizedAdsOnly(boolean npa) {
       // Utils.setRequestNonPersonalizedAdsOnly(npa, adRequest);

    }comment these line in  node modules -> react native admob native ads ->RNAdMobNativeView.java

**Comment by ammarahm-ed** [comment]
Fixed in v0.7.2
