### ISSUE TITLE
Error While Opening ad in Android for React Native New architecture

### ISSUE THREAD

**Issue by Bhavya-Makadia** [ammarahm-ed/react-native-admob-native-ads#375]
After enabling the new architecture and adding the package to interops layer, the android app got built but when I tried to load the ad it is throwing errors 
"dispatchCommand called without surfaceld - Fabric dispatchCommand must be called through Fabric JSI API " or else this 
" Exception in HostFunction: com.facebook.react.bridge.UnexpectedNativeTypeException: expected Array, got a null"

And for IOS I am getting 
"Linker command failed with exit code 1 (use -v to see invocation)"
RN version : 0.73.6

<img width="315" alt="Screenshot 2024-07-02 at 12 48 26 PM" src="https://github.com/ammarahm-ed/react-native-admob-native-ads/assets/64064622/bd0d0572-0bde-4e33-bebc-0ea01a933641">
<img width="323" alt="Screenshot 2024-07-01 at 7 47 42 PM" src="https://github.com/ammarahm-ed/react-native-admob-native-ads/assets/64064622/584c69f5-4d1f-481e-ab32-0527e75a9eb8">

**Comment by ammarahm-ed** [comment]
New arch is not supported.
