### ISSUE TITLE
CallToActionView throws error when it doesn't have style

### ISSUE THREAD

**Issue by FSPinho** [ammarahm-ed/react-native-admob-native-ads#376]
Thanks fo your amazing work!

I identified the following issue:
When the \<CallToActionView /> has no style, it throws the error bellow. It's easily fixed by providing any style to it, even empty.

<img width="552" alt="image" src="https://github.com/user-attachments/assets/6aefc43c-a730-4ffc-af8e-a07a42b8db29">

So I think it simply miss a undefined check before doing the above check on `.elevation`. 

I'd love to send a PR if I have some free time soon.

**Comment by ammarahm-ed** [comment]
Fixed in v0.7.2
