### ISSUE TITLE
Ad impressions and clicks

### ISSUE THREAD

**Issue by harshal2030** [ammarahm-ed/react-native-admob-native-ads#38]
Hi! I am experiencing a strange issue. onImpression is called when user click ads and return back from the link and onClick is not called when user click ads

**Comment by ammarahm-ed** [comment]
When the ad is rendered on the screen, `onImpression` is not called until the user starts interacting, clicking stuff or scrolling, then the `onImpression` is registered. `onClick` usually works. Do you see the ads clicked etc in your AdMob console?

**Comment by harshal2030** [comment]
I am working with test ID for now for testing. yeah, onImpression get called while scrolling but onClick doesn't get called when ad get clicked

**Comment by ammarahm-ed** [comment]
This is fixed in **v.0.3.5**

**Comment by harshal2030** [comment]
okk, thanks for this awesome package

**Comment by Rohit3523** [comment]
@ammarahm-ed I am getting the same issue in latest version when i native ad parent component have flex: 1 or height in style
