### ISSUE TITLE
Installation guide wrong package

### ISSUE THREAD

**Issue by perrosnk** [ammarahm-ed/react-native-admob-native-ads#4]
Thank you so much for this library.
Unfortunately I don't know how to send a pull request but the installation guide seems wrong. It refers to `react-native-action-sheet`

**Comment by ammarahm-ed** [comment]
I cant find it to be wrong anywhere. It refers to the right place, I have checked.

**Comment by ammarahm-ed** [comment]
I just fixed it. Sorry i didnt see it before. I have pushed the new version
