### ISSUE TITLE
testDevices should not be a prop

### ISSUE THREAD

**Issue by halaei** [ammarahm-ed/react-native-admob-native-ads#44]
As described in https://developers.google.com/admob/android/test-ads, the process of setting test device ids can be done only once, and after that all the ads, no matter if native, or banner, or other types, will be test ads. However, in this package the NativeAdView components have a testDevices prop, with the default of empty array. So I need to set the prop everywhere in the code I need an ad, instead of calling a function just once, e.g. in App.js or index.js. This is a bit inefficient and causes problems when using this package alongside other AdMob related react native packages.

I suggest to remove testDevices prop from NativeAdView and instead expose a function like the following, not only to fix the mentioned problems, but also to have full support of [RequestConfiguration.Builder](https://developers.google.com/android/reference/com/google/android/gms/ads/RequestConfiguration.Builder):
```java
@ReactMethod
// This is just a pseudocode for java without type validation and all the necessary castings: 
public void setRequestConfiguration(ReadableMap config) {
	RequestConfiguration configuration = new RequestConfiguration.Builder();
	if (config.hasKey("maxAdContentRating")) {
		configuration.setMaxAdContentRating(config.getString("maxAdContentRating"));
	}
	if (config.hasKey("tagForChildDirectedTreatment")) {
		configuration.setTagForChildDirectedTreatment(config.getInt("tagForChildDirectedTreatment"));
	}
	if (config.hasKey("tagForUnderAgeOfConsent")) {
		configuration.setTagForUnderAgeOfConsent(config.getInt("TagForUnderAgeOfConsent"));
	}
	if (config.hasKey("testDeviceIds")) {
		configuration.setTestDeviceIds(config.getArray("testDeviceIds"));
	}

	MobileAds.setRequestConfiguration(configuration.build());
}
```

**Comment by ammarahm-ed** [comment]
I think we can do it with a Native Module already present in the project and loading our configuration on app start. I will add this in the next release in a few days.

**Comment by ammarahm-ed** [comment]
This has been implemented for **v0.3.0**

**Comment by halaei** [comment]
@ammarahm-ed Thank. But I guess you haven't yet remove testDevices prop. The default value is an empty array which cancels out any previous calls to setRequestConfiguration.
If you like to keep the prop, maybe setting the default to null instead of an empty array and not calling setRequestConfiguration when prop is null can help.

**Comment by halaei** [comment]
https://github.com/ammarahm-ed/react-native-admob-native-ads/blob/c78aaeae8262e4640765365c37dc0426b1dc2355/src/index.js#L126
