### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by viveKing21** [ammarahm-ed/react-native-admob-native-ads#46]
after install this library
i'm not able to run app on android [react-native run-android]
` Task :app:mergeDexDebug FAILED`

showing this can anyone please help me

**Comment by ammarahm-ed** [comment]
Please share the complete log & tell what is your react-native version.

**Comment by sayem314** [comment]
#### Enable Multidex

Open the `android/app/build.gradle` file. Under `dependencies` we need to add the module, and then enable it within the `defaultConfig`:

```
android {
    defaultConfig {
        // ...
        multiDexEnabled true
    }
    // ...
}

dependencies {
  implementation 'com.android.support:multidex:1.0.3'
}
```

Once added, rebuild your application:
```shell
cd android && ./gradlew clean && cd ../
yarn react-native run-android
```
