### ISSUE TITLE
 white space when it doesn't return ads

### ISSUE THREAD

**Issue by techday84** [ammarahm-ed/react-native-admob-native-ads#47]
Hi, I have tried the library and the ads appear with my id correctly, but sometimes when it doesn't return an ad it render a blank space with the same widht and height that the ad. How could I make sure that if there is no ad, it doesn't render that space?  Thanks in advance.

**Comment by ammarahm-ed** [comment]
Use the events on the view to handle cases where ad is not returned, and hide the NativeAd using state.

**Comment by techday84** [comment]
Hi, I try to do this, but If the ads doesn't show, it render a white  space
and when it occours never pass into onAdFailedToLoad event.
