### ISSUE TITLE
Can this package support React Native 0.55.4 ?

### ISSUE THREAD

**Issue by tlweiii6465** [ammarahm-ed/react-native-admob-native-ads#58]
Hi, im using react native 0.55.4, can this package support it?

**Comment by ammarahm-ed** [comment]
I haven't tested it with older versions, you can try and let me know. You will have to manually link the library.

**Comment by tlweiii6465** [comment]
Thanks for your reply, can i have step of manually link to this package?

**Comment by tlweiii6465** [comment]
Thanks for your reply, can you let me know what is the step for manual link this package to library?
