### ISSUE TITLE
ads overlap sometime 

### ISSUE THREAD

**Issue by huyhai** [ammarahm-ed/react-native-admob-native-ads#67]
![Screenshot_20200829-101245_2](https://user-images.githubusercontent.com/10529783/91627287-a2b5f000-e9e0-11ea-8b80-fda10b14cd58.png)
i put native ads inside Flatlist, sometime this happen. Cannot reproduce for now

**Comment by ammarahm-ed** [comment]
delay the ad loading, check the example app.

**Comment by huyhai** [comment]
> delay the ad loading, check the example app.

 yes it's work, thank you, close for now
