### ISSUE TITLE
Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by jaeyoonlim** [ammarahm-ed/react-native-admob-native-ads#68]
Thank you for your nice module.
I want to suggest idea that check NativeAdView is mounted before update ad

**ISSUE**

Can't refresh ad in FlatList

```
 ERROR    Warning: Can't perform a React state update on an unmounted component. 
This is a no-op, but it indicates a memory leak in your application. 
To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in NativeAdView (at NativeAdsText.js:20)
    ...
```

**IDEA**

```
...

export class NativeAdView extends Component {
  constructor(props) {
    super(props);
    this.state = {
      nativeAd: null,
      nativeAdView: null,
      delayRender: true,
    };
    this.nativeAdRef;
    this.currentId = 0;
    this.delayDuration = 0;
    this._isMounted = false;
  }

...

  updateAd(ad) {
    if (this._isMounted) {
      this.setState({
        nativeAd: ad,
      });
    }
  }

  componentDidMount() {
    this._isMounted = true;

 ...

  }

  componentWillUnmount() {
    this._isMounted = false;
  }

...
```

Like this.
If is it okay, I will write pull request.
Thank you!

**Comment by mrousavy** [comment]
If the `updateAd` function is called before the component is mounted, then that update gets lost, no?

**Comment by jaeyoonlim** [comment]
@mrousavy Right, 
If NativeAdView is in FlatList as a item, Can't update ad.

**Comment by mrousavy** [comment]
We could implement a small queue-like system, where the ad first gets set as a normal property (like `useRef`) and then `componentDidMount` reads that ref and sets it to state. If the ad gets updated **after** the component gets mounted, it just writes directly to the state.

**Comment by jaeyoonlim** [comment]
This bug is not about that,
Can't update ad when ```NativeAdView``` is **unmounted** in ```FlatList```, not the first mount.
