### ISSUE TITLE
MediaView with video doesn't play on load in Android

### ISSUE THREAD

**Issue by Niveditha29** [ammarahm-ed/react-native-admob-native-ads#73]
Thank you for this great package.

This is the code used to render video ad.

` <NativeAdView
        onAdLoaded={_onAdLoaded}
        onAdFailedToLoad={_onAdFailedToLoad}
        onAdLeftApplication={() => {
          console.log('ad has left the application');
        }}
        onAdClicked={_onAdClicked}
        onAdImpression={_onAdImpression}
        onUnifiedNativeAdLoaded={_onUnifiedNativeAdLoaded}
        style={styles.nativeAdViewBox}
        adUnitID={NATIVE_AD_VIDEO_ID}
      >
        <View style={styles.adMediaViewBox}>
            <MediaView style={styles.adMediaView} />
        </View>
    </NativeAdView>`

On load, only the image is rendered even though there is video url. When I navigate from other app to this, the video starts playing.

React Native version: 0.62.0
react-native-admob-native-ads: 0.3.6

**Comment by ammarahm-ed** [comment]
Wrap it in a ScrollView. See the example app. Video plays when an interaction is detected, usually that does not happen in the React Native Views.

**Comment by bhavikgajera92** [comment]
Hi @ammarahm-ed 
Thank you for this awesome package.

I have checked example app code regarding the above issue @Niveditha29 posted. I do have same kind of issue in my App as well. If I run the app on broadband internet connection then upon slight scroll the video starts to play/sometimes autoplay as well. But If I run the app on mobile internet then upon slight scroll or phone rotate it does not play(Auto play also do not works). I have to click on play icon to start the ad video.

What should be the possible solutions for this, please suggest ?

React Native version: 0.62.0
react-native-admob-native-ads: 0.3.6

Thanks

**Comment by yaroslavnikiforov** [comment]
I have the same issue. To start the video on Android need to trigger the scroll event (when connected to wifi). And with mobile internet need to press start button.

**Comment by ammarahm-ed** [comment]
That is because ads have built in feature to save data on Mobile Data. Not an issue.

**Comment by ArnabXD** [comment]
So how do I make video ads work in a modal? I already tried a fullscreen modal with React Navigation and wrapped it with a ScrollView but nothing changed.  Video isn't showing up even after trying to scroll. So I did attach a ref to ScrollView and Triggered `scrollTo()` inside `onNativeAdLoaded`. Still, it doesn't show up. I tried the example app which works completely fine.

My Code 

```tsx
import React, { useEffect, useState, useRef } from 'react';
import { View, Dimensions, ScrollView } from 'react-native';
import NativeAdView, {
	AdvertiserView,
	CallToActionView,
	HeadlineView,
	IconView,
	StarRatingView,
	StoreView,
	TaglineView,
	NativeMediaView,
} from 'react-native-admob-native-ads';
import { useTheme } from 'react-native-paper';
import { Ad } from '@edbyss/ads';
import { Loader } from '@edbyss/components';

const { width } = Dimensions.get('screen');

interface InterstitialProps {
	onVideoEnd?: () => void;
	onFailedToLoad?: () => void;
}

export const InterStitialAd = ({
	onVideoEnd = () => {},
	onFailedToLoad = () => {},
}: InterstitialProps) => {
	const { colors } = useTheme();
	const [loading, setLoading] = useState(true);
	const [nativeLoading, setNativeLoading] = useState(true);
	const [aspRatio, setAstRatio] = useState(1.5);
	const [paused, setPaused] = useState(true);
	const adsRef = useRef<NativeAdView>({} as NativeAdView);
	const scroll = useRef<ScrollView>({} as ScrollView);

	useEffect(() => {
		adsRef.current?.loadAd();
		scroll.current.scrollTo({ y: 1 });
	}, [adsRef]);

	return (
		<ScrollView ref={scroll} style={{ flex: 1 }}>
			<NativeAdView
				ref={adsRef}
				style={{
					flex: 1,
					alignSelf: 'center',
					backgroundColor: colors.surface,
				}}
				videoOptions={{
					customControlsRequested: true,
				}}
				adUnitID={Ad.video}
				mediationOptions={{ nativeBanner: false }}
				targetingOptions={{}}
				onAdLoaded={() => {
					setLoading(false);
				}}
				onNativeAdLoaded={event => {
					setAstRatio(event.aspectRatio);
					setNativeLoading(false);
					setPaused(paused);
				}}
				onAdFailedToLoad={onFailedToLoad}
				mediaAspectRatio="portrait"
			>
				<View
					style={{
						width: width - 20,
						alignItems: 'center',
					}}
				>
					{!loading && (
						<View
							style={{
								height: 100,
								width: width - 20,
								flexDirection: 'row',
								justifyContent: 'space-between',
								alignItems: 'center',
								paddingHorizontal: 10,
								opacity: 1,
							}}
						>
							<IconView
								style={{
									width: 60,
									height: 60,
									borderRadius: 6,
								}}
							/>
							<View
								style={{
									width: '60%',
									maxWidth: '60%',
									paddingHorizontal: 6,
								}}
							>
								<HeadlineView
									style={{
										fontWeight: 'bold',
										fontSize: 13,
										color: colors.text,
									}}
								/>
								<TaglineView
									numberOfLines={2}
									style={{
										fontSize: 11,
										color: colors.text,
									}}
								/>
								<AdvertiserView
									style={{
										fontSize: 10,
										color: 'gray',
									}}
								/>

								<View
									style={{
										flexDirection: 'row',
										alignItems: 'center',
									}}
								>
									<StoreView
										style={{
											fontSize: 12,
											color: colors.text,
										}}
									/>
									<StarRatingView
										size={12}
										fullIconColor="orange"
										emptyIconColor="gray"
										style={{
											width: 65,
											marginLeft: 10,
										}}
									/>
								</View>
							</View>

							<CallToActionView
								style={{
									minHeight: 40,
									paddingHorizontal: 12,
									justifyContent: 'center',
									alignItems: 'center',
									elevation: 10,
									maxWidth: 100,
									width: 80,
								}}
								buttonAndroidStyle={{
									backgroundColor: colors.primary,
									borderRadius: 5,
								}}
								allCaps
								textStyle={{
									fontSize: 13,
									flexWrap: 'wrap',
									textAlign: 'center',
									color: 'white',
								}}
							/>
						</View>
					)}
				</View>
				{nativeLoading ? (
					<View style={{ height: 150 }}>
						<Loader size={25} />
					</View>
				) : (
					<NativeMediaView
						style={{
							width: '100%',
							height: width / aspRatio,
							backgroundColor: 'white',
						}}
						onVideoEnd={onVideoEnd}
						paused={paused}
					/>
				)}
			</NativeAdView>
		</ScrollView>
	);
};

```

My React Native Version : `0.65.1`
react-native-admob-native-ads : `^0.5.0`

**Comment by ammarahm-ed** [comment]
> So how do I make video ads work in a modal? I already tried a fullscreen modal with React Navigation and wrapped it with a ScrollView but nothing changed.  Video isn't showing up even after trying to scroll. So I did attach a ref to ScrollView and Triggered `scrollTo()` inside `onNativeAdLoaded`. Still, it doesn't show up. I tried the example app which works completely fine.
> 
> My Code 
> 
> ```tsx
> import React, { useEffect, useState, useRef } from 'react';
> import { View, Dimensions, ScrollView } from 'react-native';
> import NativeAdView, {
> 	AdvertiserView,
> 	CallToActionView,
> 	HeadlineView,
> 	IconView,
> 	StarRatingView,
> 	StoreView,
> 	TaglineView,
> 	NativeMediaView,
> } from 'react-native-admob-native-ads';
> import { useTheme } from 'react-native-paper';
> import { Ad } from '@edbyss/ads';
> import { Loader } from '@edbyss/components';
> 
> const { width } = Dimensions.get('screen');
> 
> interface InterstitialProps {
> 	onVideoEnd?: () => void;
> 	onFailedToLoad?: () => void;
> }
> 
> export const InterStitialAd = ({
> 	onVideoEnd = () => {},
> 	onFailedToLoad = () => {},
> }: InterstitialProps) => {
> 	const { colors } = useTheme();
> 	const [loading, setLoading] = useState(true);
> 	const [nativeLoading, setNativeLoading] = useState(true);
> 	const [aspRatio, setAstRatio] = useState(1.5);
> 	const [paused, setPaused] = useState(true);
> 	const adsRef = useRef<NativeAdView>({} as NativeAdView);
> 	const scroll = useRef<ScrollView>({} as ScrollView);
> 
> 	useEffect(() => {
> 		adsRef.current?.loadAd();
> 		scroll.current.scrollTo({ y: 1 });
> 	}, [adsRef]);
> 
> 	return (
> 		<ScrollView ref={scroll} style={{ flex: 1 }}>
> 			<NativeAdView
> 				ref={adsRef}
> 				style={{
> 					flex: 1,
> 					alignSelf: 'center',
> 					backgroundColor: colors.surface,
> 				}}
> 				videoOptions={{
> 					customControlsRequested: true,
> 				}}
> 				adUnitID={Ad.video}
> 				mediationOptions={{ nativeBanner: false }}
> 				targetingOptions={{}}
> 				onAdLoaded={() => {
> 					setLoading(false);
> 				}}
> 				onNativeAdLoaded={event => {
> 					setAstRatio(event.aspectRatio);
> 					setNativeLoading(false);
> 					setPaused(false);
> 				}}
> 				onAdFailedToLoad={onFailedToLoad}
> 				mediaAspectRatio="portrait"
> 			>
> 				<View
> 					style={{
> 						width: width - 20,
> 						alignItems: 'center',
> 					}}
> 				>
> 					{!loading && (
> 						<View
> 							style={{
> 								height: 100,
> 								width: width - 20,
> 								flexDirection: 'row',
> 								justifyContent: 'space-between',
> 								alignItems: 'center',
> 								paddingHorizontal: 10,
> 								opacity: 1,
> 							}}
> 						>
> 							<IconView
> 								style={{
> 									width: 60,
> 									height: 60,
> 									borderRadius: 6,
> 								}}
> 							/>
> 							<View
> 								style={{
> 									width: '60%',
> 									maxWidth: '60%',
> 									paddingHorizontal: 6,
> 								}}
> 							>
> 								<HeadlineView
> 									style={{
> 										fontWeight: 'bold',
> 										fontSize: 13,
> 										color: colors.text,
> 									}}
> 								/>
> 								<TaglineView
> 									numberOfLines={2}
> 									style={{
> 										fontSize: 11,
> 										color: colors.text,
> 									}}
> 								/>
> 								<AdvertiserView
> 									style={{
> 										fontSize: 10,
> 										color: 'gray',
> 									}}
> 								/>
> 
> 								<View
> 									style={{
> 										flexDirection: 'row',
> 										alignItems: 'center',
> 									}}
> 								>
> 									<StoreView
> 										style={{
> 											fontSize: 12,
> 											color: colors.text,
> 										}}
> 									/>
> 									<StarRatingView
> 										size={12}
> 										fullIconColor="orange"
> 										emptyIconColor="gray"
> 										style={{
> 											width: 65,
> 											marginLeft: 10,
> 										}}
> 									/>
> 								</View>
> 							</View>
> 
> 							<CallToActionView
> 								style={{
> 									minHeight: 40,
> 									paddingHorizontal: 12,
> 									justifyContent: 'center',
> 									alignItems: 'center',
> 									elevation: 10,
> 									maxWidth: 100,
> 									width: 80,
> 								}}
> 								buttonAndroidStyle={{
> 									backgroundColor: colors.primary,
> 									borderRadius: 5,
> 								}}
> 								allCaps
> 								textStyle={{
> 									fontSize: 13,
> 									flexWrap: 'wrap',
> 									textAlign: 'center',
> 									color: 'white',
> 								}}
> 							/>
> 						</View>
> 					)}
> 				</View>
> 				{nativeLoading ? (
> 					<View style={{ height: 150 }}>
> 						<Loader size={25} />
> 					</View>
> 				) : (
> 					<NativeMediaView
> 						style={{
> 							width: '100%',
> 							height: width / aspRatio,
> 							backgroundColor: 'white',
> 						}}
> 						onVideoEnd={onVideoEnd}
> 						paused={paused}
> 					/>
> 				)}
> 			</NativeAdView>
> 		</ScrollView>
> 	);
> };
> 
> ```
> 
> My React Native Version : `0.65.1`
> react-native-admob-native-ads : `^0.5.0`

Do not use flex on ScrollView. Set a fixed height for NativeAdView. Set a fixed max for ScrollView greater than NativeAdView.  For example if NativeAdView is 250 then ScrollView can be 251. Then trigger scroll so it will actually move a little and video will play.
