### ISSUE TITLE
CallToActionView button not working need to check 

### ISSUE THREAD

**Issue by neghani** [ammarahm-ed/react-native-admob-native-ads#75]

**Comment by manuhook** [comment]
Do you use react-native-navigation ?

**Comment by ammarahm-ed** [comment]
Provide some information?

**Comment by urunky** [comment]
In my case, I haved fixed the version of 'react-native-gesture-handler' '**1.6.1'**. not '^1.6.1' in package.json. 
and  then, delete package-lock.json and node-modules directories 
reinstall all node-modules 
CallToActionView works again.

**Comment by kabus202** [comment]
same for me, not working   "react-native-gesture-handler": "^1.8.0", 

but the any other click in the ad is working just fine

**Comment by neghani** [comment]
Sorry for late in reply, I had to drop the framework from my project, because mutliple compnent(from other frameworks) regrstration were duplicated.

The issue was with my code, so closing with this commment
