### ISSUE TITLE
Using this library alongside React Native Firebase for other ad formats

### ISSUE THREAD

**Issue by bartzy** [ammarahm-ed/react-native-admob-native-ads#76]
Thank you for this awesome library!

I was wondering if it's possible to use both this library and React Native Firebase (https://rnfirebase.io/admob/usage) in the following way:
1. Show Interstitial, Banner & Rewarded Video ads by using React Native Firebase
2. Show Native ads from react-native-admob-native-ads.

Will that include two versions of the AdMob SDK in the binary? Will it interrupt anything?

My app is both for iOS and Android.

**Comment by pedro-tentaculo** [comment]
Hi @bartzy I also have the same question. Can you tell me if you have tried to setup both libraries in the same project yet?

**Comment by ammarahm-ed** [comment]
@bartzy They will work together

**Comment by mdtechcs** [comment]
I am facing compatibility issues. https://github.com/ammarahm-ed/react-native-admob-native-ads/issues/234
I would be really thankful if anyone have any idea.

**Comment by ammarahm-ed** [comment]
> I am facing compatibility issues. https://github.com/ammarahm-ed/react-native-admob-native-ads/issues/234
> I would be really thankful if anyone have any idea. 

Use the library provided in readme instead

**Comment by mdtechcs** [comment]
> > I am facing compatibility issues. #234
> > I would be really thankful if anyone have any idea.
> 
> Use the library provided in readme instead

you mean https://github.com/react-native-admob/admob ? I think issue is that firebase and react-native-admob-native-ads are conflicting

**Comment by ammarahm-ed** [comment]
The conflict can't be fixed. Since firebase uses older version of admob and this lib uses the latest.
