### ISSUE TITLE
Suggestion: integrate with Appodeal

### ISSUE THREAD

**Issue by dylancom** [ammarahm-ed/react-native-admob-native-ads#77]
Appodeal is a mediation network which has a React Native package: https://github.com/appodeal/react-native-appodeal
Currently most ad formats are available to React Native, except for "Native Ads".

I'm not sure how reusable the code in this package is but this would have the potential to easily display Native ads from many networks: "Admob, AppLovin, BidMachine, Facebook, Flurry, InMobi, MyTarget and Startapp".

**Comment by ammarahm-ed** [comment]
Great idea, Currently we are stuck of FB-Mediation, some bug I tried to fix but still lingering around. I dont have admob account to check what is causing the issue. If we are able to fix that, we can put support for more networks.

**Comment by ammarahm-ed** [comment]
@dylancom you can test the master branch as it supports mediation now hopefully. Facebook is working. Haven't tested other mediation networks but they should.
