### ISSUE TITLE
[Flatlist] always request when scorlling

### ISSUE THREAD

**Issue by magneutron** [ammarahm-ed/react-native-admob-native-ads#79]
After embed ads into flatlist, when I scrolling the flatlist, it would re-render ads , request again and again.
Any method to prevent that problem to pervent duplicate request?

**Comment by ammarahm-ed** [comment]
@magneutron no way to stop it yet I think. We need to implement ad-preloading on native code to fix this issue.

**Comment by magneutron** [comment]
This is a temporary solution
https://stackoverflow.com/questions/56921293/rendering-admob-banner-within-react-native-flatlist-items

**Comment by ammarahm-ed** [comment]
@magneutron good workaround, I hope it is working for you. A proper solution will come soon.

**Comment by perrosnk** [comment]
I believe that another workaround is to wrap the Ad component with `React.memo`
