### ISSUE TITLE
Preloading ads

### ISSUE THREAD

**Issue by dylancom** [ammarahm-ed/react-native-admob-native-ads#8]
Is their some way to preload native ads?
It would be nice if the ad could directly show up when switching screens.

**Comment by ammarahm-ed** [comment]
Currently there is no way to do that, but I will add it. Right now I am rewriting the whole library to make it work like react-native-fbads with more customization. That is almost done. So next is preloading and ad storage for a specific period of time which will be added in the next version.

**Comment by dylancom** [comment]
@ammarahm-ed great work so far! Will contribute where I can, highly interested in this project.

**Comment by ammarahm-ed** [comment]
@dylancom any kind of help would be highly appreciated. And I am always open to ideas.

**Comment by anastely** [comment]
Hey @ammarahm-ed I'm going to use your lib very soon but When will the new version be released?

**Comment by ammarahm-ed** [comment]
@anastely I need some people to test it before it is released. It is almost ready

**Comment by anastely** [comment]
@ammarahm-ed How can I help?

**Comment by dylancom** [comment]
@ammarahm-ed Seems to work mostly fine to me. Only when I add in a testID instead of prod, I'm seeing an empty ad...

**Comment by anastely** [comment]
Hey, @dylancom How you test it?

**Comment by dylancom** [comment]
@anastely install the project like this: `npm install --save ammarahm-ed/react-native-admob-native-ads#pull/7/head and you will be able to test code from the pull request.
`

**Comment by anastely** [comment]
It just installs [these](https://i.imgur.com/fGdAR2G.png) files,
In node_modules I can see this lib but without any example folder, so what should I do to test it 😅
 _Sorry but I'm new in open source_

**Comment by dylancom** [comment]
Though of my use case where I already import it in a working project.
Anyway, you can then just clone / download the repo from here: https://github.com/ammarahm-ed/react-native-admob-native-ads/tree/dev
(the latest code is on the dev branch)

**Comment by anastely** [comment]
Well, I got empty Ad
I replace AdMob App ID in AndroidManifest with mine, and in adUnitID, Should I change something else! Or for example, Follow the interstitial implementation guide to integrate the SDK?

**Comment by ammarahm-ed** [comment]
> Seems to work mostly fine to me. Only when I add in a testID instead of prod, I'm seeing an empty ad...

Strange because I am doing all the testing on test-ads. What error are you getting in `onAdFailedToLoad`? Sometimes when changing the id, you should delete the app and reinstall it so Admob will send ads from the server, otherwise it gives error:3 or no ads in inventory.
@dylancom

**Comment by dylancom** [comment]
@ammarahm-ed Figured it works great if I use: enableTestMode

**Comment by ammarahm-ed** [comment]
@anastely You should test everything in example app and report here if you face a problem. Also newly generated Admob IDs will not return any ads so it is better to do the testing on test ads with test App-ID as I am or you can use your own App ID.

And remember you need to create **ad id for native ads** in Admob Console.

**Comment by ammarahm-ed** [comment]
@dylancom that is not a real ad. It is a placeholder that I created just for testing incase you dont have internet or some other problem to create your design easily. Ads with test app id and adUnitID should work. Are they also not working in the example app?

**Comment by dylancom** [comment]
Haven’t tried the example app. In directly testing the ads in my app.

**Comment by ammarahm-ed** [comment]
@dylancom also Ad preloading is implemented on android. Still need to implement it on iOS. its on `ad-preloading-patch` branch.

**Comment by anastely** [comment]
@ammarahm-ed I tested it in example App at the first time I don't change any Ad ID But I can't see any Ad So I go to AdMobconsole and create an AdMob App ID & ad Unit ID and use it in the example
But I got the same no ad I can see :\ and in Log, I see this message
`Internal error, an invalid response was received from the ad server
`

**Comment by ammarahm-ed** [comment]
Ads from your own Ad Unit ID will not appear currently because you just created it so do not use those in development as it will cause your AdMob Account to be banned. 

Use your own App ID and test ads:
https://developers.google.com/admob/android/test-ads

Native-Advanced or Native-Advanced-Video during development

**Comment by anastely** [comment]
Ahaa, What about AdMob App ID in AndroidManifest what Should I use?

**Comment by ammarahm-ed** [comment]
@anastely Try again with example app without making any changes to it. It should work directly, or tell me what error you are getting in `onAdFailedToLoad`.

**Comment by ammarahm-ed** [comment]
You can use your App ID. That is not a problem. @anastely

**Comment by anastely** [comment]
@ammarahm-ed Great! it works it takes time to appear 1-2min  although I don't have any issue with an internet connection

**Comment by dylancom** [comment]
@ammarahm-ed When I use the adUnitID="ca-app-pub-3940256099942544/2247696110" // TEST adUnitID, nothing show and onAdFailedToLoad is trigger. The parameter doesn't contain an error object though, if I log it shows an event: "SyntheticEvent".

**Comment by ammarahm-ed** [comment]
@dylancom is this happening in the example? because I am using the example and there, all ads are showing properly using test ids. `onAdFailedToLoad` must trigger one of these four errors:
```java
 @Override
            public void onAdFailedToLoad(int i) {
                super.onAdFailedToLoad(i);

                String errorMessage = "Unknown error";
                switch (i) {
                    case AdRequest.ERROR_CODE_INTERNAL_ERROR:
                        errorMessage = "Internal error, an invalid response was received from the ad server.";
                        break;
                    case AdRequest.ERROR_CODE_INVALID_REQUEST:
                        errorMessage = "Invalid ad request, possibly an incorrect ad unit ID was given.";
                        break;
                    case AdRequest.ERROR_CODE_NETWORK_ERROR:
                        errorMessage = "The ad request was unsuccessful due to network connectivity.";
                        break;
                    case AdRequest.ERROR_CODE_NO_FILL:
                        errorMessage = "The ad request was successful, but no ad was returned due to lack of ad inventory.";
                        break;
                }

```
and it is never empty. Atlease it should show `Unknown error`.

**Comment by dylancom** [comment]
Haven’t take a look at the example yet.
I’ve just took the code from the ReadMe and adjusted it to my styling wishes.

**Comment by ammarahm-ed** [comment]
```js

 const _onAdFailedToLoad = event => {
    console.log(event.nativeEvent);
  };

```
You should log it like this. @dylancom

**Comment by dylancom** [comment]
@ammarahm-ed Ah I see, that's returning: message: "Request Error: No ad to show."

**Comment by ammarahm-ed** [comment]
@dylancom it means the server is not returning any ad from the test-id. clean up your app and build folders then try again.

**Comment by dylancom** [comment]
@ammarahm-ed Xcode is showing this log btw everytime I show an ad: _<Google> User interactions must be disabled on the asset view to enable click handling.
userInteractionEnabled has been set to NO on <RCTTextView: 0x7ffcc4005d40; reactTag: 1457; text:  frame = (16 14; 327 14.3333); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x600000b27e80>>_

**Comment by ammarahm-ed** [comment]
This is just a warning since the views are created in React Native but we can handle this I think by setting `userInteractionEnabled` to `NO` before attaching each view.

**Comment by ammarahm-ed** [comment]
@dylancom I have handled the warning.

**Comment by dylancom** [comment]
@ammarahm-ed Yes, I can confirm they are gone now. Awesome!

**Comment by anastely** [comment]
It's time to release 🎉

**Comment by dylancom** [comment]
@ammarahm-ed The test ad IDs are different for Android / iOS btw: https://developers.google.com/admob/ios/test-ads

I found that I have to use: ca-app-pub-3940256099942544/2521693316, which is for iOS "Native Advanced Video". If i'm using the test ID for "Native Advanced", it doesn't show up though...

**Comment by ammarahm-ed** [comment]
@dylancom we should update the example with the correct ids.

**Comment by ammarahm-ed** [comment]
> Great! it works it takes time to appear 1-2min although I don't have any issue with an internet connection

@anastely It depends on the server returning the ads. Some times it does not return any ad, so a request is made after 1 minute. With ad preloading added in this week probably that problem will be gone too. So ads will show up immediately.

**Comment by dylancom** [comment]
@ammarahm-ed Do you have any ETA on when preloading would be available?
Now you have to wait like 2/3 seconds on every screen before a Native ad shows.

**Comment by ammarahm-ed** [comment]
@dylancom its work in progress. Android is complete. ios needs to be done. I want to get them ready as soon as I can. Just a bit of work load right now

**Comment by haresh4d** [comment]
> @dylancom its work in progress. Android is complete. ios needs to be done. I want to get them ready as soon as I can. Just a bit of work load right now

How can I enable Pre Loading? because right now it is taking too long to display an ad.

**Comment by bhavikgajera92** [comment]
Hi @ammarahm-ed 

At present when video ads are loading by default they are muted. How can we make them by default unmuted ?
Is there any way we can do it ?

Thanks

**Comment by bhavikgajera92** [comment]
Hi @ammarahm-ed 

At present when video ads are loading by default they are muted. How can we make them by default unmuted ?
Is there any way we can do it ?

Thanks

**Comment by ammarahm-ed** [comment]
@haresh4d  preloading has not been implemented yet. @bhavikgajera92 You will have to fork and modify the native code to do that. Right not it is not supported by the library.

**Comment by haresh4d** [comment]
@ammarahm-ed I have used this library in my few apps. Actually I am getting below 50% impressions for ad requests. Yesterday the number of ad request was 1000 and impressions were only 200. Whats the problem?

**Comment by ammarahm-ed** [comment]
@haresh4d  Because the user moves away from the screen many times in your app when ad is loaded. Lets say I go to Home, ad is loading, I tap on another screen and go there. 

Or maybe in a List, you load ads after every 10 items, now the ads are loaded but impressions are not recorded so there are more requests and less impressions.

You need to optimize this yourself.

**Comment by bartzy** [comment]
@ammarahm-ed Do you have an update regarding preloading? The library works great but without a way to preload - it currently takes 2-3 seconds to load an ad which makes it problematic for most of our usecases.

Thanks!

**Comment by ammarahm-ed** [comment]
closing this issue, opened a new one.

**Comment by zoobibackups** [comment]
I have the test ad ideas but it is giving the error below from the last 4 days. 
{"error": {"message": "The ad request was successful, but no ad was returned due to lack of ad inventory."}}

**Comment by ammarahm-ed** [comment]
It's because the server is not sending ads. Not an issue with this library.
Try to remove the app from phone. And run `. /gradlew clean` in /android
folder. Similarly clear project on iOS in xcode.

**Comment by Hassan709** [comment]
> Work in Progress:
> https://github.com/ammarahm-ed/react-native-admob-native-ads/tree/ad-preloading-patch

i want to load native media ads before ender but fail .how its possible

**Comment by Hassan709** [comment]
i am using react native ads mob to display native ads but ads load after some interval. how its possible to pre load ads?
