### ISSUE TITLE
IDFA will be unavailable by default on iOS 14

### ISSUE THREAD

**Issue by fatzhou** [ammarahm-ed/react-native-admob-native-ads#81]
Starting in iOS 14, IDFA will be unavailable by default, until the app calls the  App Tracking Transparency  framework to present the app-tracking authorization request to the end user. If an app does not present this request, the IDFA will automatically be zeroed out.

Can you add support for such case? Thanks!

**Comment by ammarahm-ed** [comment]
You can use this library, [react-native-permissions](https://github.com/zoontek/react-native-permissions/releases/tag/2.2.0l) to request for the permission on App Launch. @fatzhou
