### ISSUE TITLE
Please help me understand requirements for networks (FB and Verizon)

### ISSUE THREAD

**Issue by gabriel-tentaculo** [ammarahm-ed/react-native-admob-native-ads#84]
Hello @ammarahm-ed , 
my goal using this library is to be able to show ads from facebook and verizon media through ADB being the mediator.

I have added the library into my project with no problem using the AdView file from the examples folder:
https://github.com/ammarahm-ed/react-native-admob-native-ads/blob/master/example/AdView.js

I have changed the ID to my own ids and test ads load fine on android emulator.
The ID I'm using has only facebook and verizon registered.

Now here are some questions that I have.

1 On a real device there are no ads showing up (I'm using the real live ad ID not the test one from the file).
This results in test ads being show on the emulator but not ads showing on a real device, and on the console I get:
error.message: "The ad request was successful, but no ad was returned due to lack of ad inventory."
Is this the expected behavior?
1.a. If I want to see test ads on the real device, what is it that I have to do? (I need to check if the layout I changed is ok)

2. I see some users commenting on other issues how they have installed the FB mediation SDK. From what I understand the AD being used here uses admob as the mediator to show ads from facebook and verizon. 
Should I go through the fb sdk install proccess to get ads form facebook using this library under this setup? Or it will work out of the box using Adview file from the example mentioned above?
(here is another user - perrosnk -  commenting about this proccess: https://github.com/ammarahm-ed/react-native-admob-native-ads/issues/34#issuecomment-641135935)

2.a. In case there is a need for extra setup for facebook ads to work here through admob, is the reference above correct? 
(this is the link that the user above mention: https://developers.google.com/admob/android/mediation/facebook)

Thanks

**Comment by ammarahm-ed** [comment]
mediation is not supported at the moment

**Comment by gabriel-tentaculo** [comment]
Oh no, mediation with admob to show facebook and verizon ads are the only reason I need to implement this...
Is there something I can do to make it work by changing your library code somehow? Is there a workaround or another library you would recommend me using for this case?

**Comment by ammarahm-ed** [comment]
You can test out mediation with the library and we can fix the issues we will face. Its possible to add mediation. Might work out of the box. Check #33 and #34 issues

**Comment by gabriel-tentaculo** [comment]
Thanks for letting me know, this implementation was finished a few weeks ago but right now no mediation is being served as the partner networks are still being configured, but normal google ads are being displayed without problems.
As soon as mediation starts to be used I'll let you know if it works or not
