### ISSUE TITLE
Building fails on simulator with Xcode12 with release scheme 

### ISSUE THREAD

**Issue by kabus202** [ammarahm-ed/react-native-admob-native-ads#86]
Some problems building with the release scheme on xcode12 simulator, on real device building is working fine. 

`ld: in /Users/x/CoreApp/x/ios/Pods/GoogleAppMeasurement/Frameworks/GoogleAppMeasurement.framework/GoogleAppMeasurement(APMEExperiment_b2a748bf275090fe4fe9f58d85ea296b.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/x/CoreApp/x/ios/Pods/GoogleAppMeasurement/Frameworks/GoogleAppMeasurement.framework/GoogleAppMeasurement' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`
Maybe related to this https://github.com/firebase/firebase-ios-sdk/issues/6520

**Comment by GeorgeBarlow** [comment]
Work around: make the following adjustments below in build settings.
<img width="372" alt="Screenshot 2020-11-01 at 10 23 59" src="https://user-images.githubusercontent.com/27292008/97800334-5d09e380-1c2c-11eb-856c-fbf33b7ab1dd.png">

**This is an issue with Xcode 12 ( credited source: https://stackoverflow.com/a/64139830 )**
