### ISSUE TITLE
ImageView doesn't show the image when enableTestMode = true

### ISSUE THREAD

**Issue by peteroid** [ammarahm-ed/react-native-admob-native-ads#88]
According to the implementation [1], should we change the following line?
```diff
- images: ["https://dummyimage.com/qvga"], 
+ images: [{ url: "https://dummyimage.com/qvga" }], 
```

[1] 
https://github.com/ammarahm-ed/react-native-admob-native-ads/blob/04ebf80b0e290eb6f996f9056f63a4307a6fa6ac/src/ImageView.js#L25

**Comment by ammarahm-ed** [comment]
fixed!
