### ISSUE TITLE
 {"error": {"message": "Request Error: No ad to show."}, "target": 169} IOS

### ISSUE THREAD

**Issue by skull6225** [ammarahm-ed/react-native-admob-native-ads#89]
Hi all. I have some problems showing ads on the iPhone. Ads does not show on ios devices. On emulator ios and android ads show on test mode! On Android devices, ads(no test mode) show normal. But if I open my proj on iphone(use lightning) onAdFailedToLoad show me next error:  **{"error": {"message": "Request Error: No ad to show."}, "target": 169}**
<img width="489" alt="image" src="https://user-images.githubusercontent.com/23364557/96349723-27a4b800-10ba-11eb-8cd3-630454372478.png">
<img width="489" alt="image" src="https://user-images.githubusercontent.com/23364557/96349736-430fc300-10ba-11eb-8570-f46d34599a2e.png">
<img width="452" alt="image" src="https://user-images.githubusercontent.com/23364557/96349741-4e62ee80-10ba-11eb-8096-831c15ed9b3f.png">

**Comment by ammarahm-ed** [comment]
reproduce in example app.
