### ISSUE TITLE
Error: Unable to resolve module `./components/StarView` from `node_modules/react-native-admob-native-ads/src/StarRatingView.js`

### ISSUE THREAD

**Issue by yaroslavnikiforov** [ammarahm-ed/react-native-admob-native-ads#97]
components folder is not present in the src directory for some reason when installing v.0.3.8.

<img width="1372" alt="Screenshot 2020-11-19 at 00 22 30" src="https://user-images.githubusercontent.com/42115630/99596102-65209c00-29fe-11eb-9a25-695b692e4e7e.png">

**Comment by ammarahm-ed** [comment]
fixed on 0.3.9
