### ISSUE TITLE
Admanager not running

### ISSUE THREAD

**Issue by azcodia** [ammarahm-ed/react-native-admob-native-ads#99]
why is the test device to show the test ad status false ??
solution please

**Comment by ammarahm-ed** [comment]
explain your issue.

**Comment by azcodia** [comment]
i want to use
const config = {
  testDeviceIds: ["YOUR_TEST_DEVICE_ID"],
  maxAdContetRating: "MA",
  tagForChildDirectedTreatment: false,
  tagForUnderAgeConsent: false,
};

AdManager.setRequestConfiguration (config);

but when I check the debug status is false, how do I use it so I can use the Admob test, or this won't affect my ads,
please work it out, sorry my English is quite messy
